### ISSUE TITLE
Ability to order bookmarks manually

### ISSUE THREAD

**Issue by FunkFrog** [zombieFox/nightTab#10]
Hey! Loving the project, it works great for me. I was curious if there's any plans in the works for allowing users to manually sort the bookmarks?

**Comment by zombieFox** [comment]
Hi, glad you like the project. I have been thinking about it. However I don't know how to make that happen with vanilla JS. So I'm exploring [draggable](https://shopify.github.io/draggable/)

After I finish up some features I'm still working on (see pull requests) I will investigate further.

**Comment by zombieFox** [comment]
Feature is now live.
