### ISSUE TITLE
space between groups

### ISSUE THREAD

**Issue by BRod79** [zombieFox/nightTab#101]
It would be a great addition, if we could manage the space between groups.  This should be a fix, rather than a feature request ;).  

btw... great project!

**Comment by zombieFox** [comment]
Good feedback. If you are using the [nightTabBeta 4.0.0 ](https://zombiefox.github.io/nightTabBeta/) you can control the space between groups from `Menu > Layout > Gutter`.

**Comment by zombieFox** [comment]
This feature has been live for some time now, closing the issue.
