### ISSUE TITLE
Feature Request:  header dissapear when scrolling.

### ISSUE THREAD

**Issue by BRod79** [zombieFox/nightTab#102]
It is nice to see that it can stay, but an option to make it so it disappears when scrolling thru bookmarks would have been great.

**Comment by zombieFox** [comment]
Good feedback again. I've wanted to do this for a while. This gave me the nudge. [It's now done](https://github.com/zombieFox/nightTab/commit/2c4f9b69bd15e0912217839ee7feaba3483357c3). Will be released when 4.0.0 goes live.
