### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by mrdarkkwebss** [zombieFox/nightTab#105]
the time is wrong is there a a way you could add a option to change the time.

**Comment by Q-out** [comment]
Check the time in your OS, nightTab takes the time from there.

**Comment by mrdarkkwebss** [comment]
My time is ight not sure whats the problem. I use arch i3

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zombieFox** [comment]
@Q-out is correct, nightTab uses the browser to [get the time](https://github.com/zombieFox/nightTab/blob/master/src/js/helper.js#L140), so whatever your computer time is set to.

@mrdarkkwebss have you set up anything special on your computer which may change the time?

**Comment by mrdarkkwebss** [comment]
No, tho i do have a ton of privacy extensions so they could be fucking with your shit.

Nonetheless can you please add a option to change the time it would make nighttab even better

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by KolyaKorruptis** [comment]
Apparently the time you get this way doesn't take daylight savings into account. Nighttab is an hour late compared to my win10 clock.

**Comment by mrdarkkwebss** [comment]
Yeah same thing happened to me. I say just add a option for users to change the time it would make things much simpler because some people have weird set ups especially if your a privacy heavy person. Everyone is different i hope you can give the freedom to change the time, thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zombieFox** [comment]
I've been looking into moving over to using [momentjs](https://momentjs.com/) to improve the clock function on nightTab. This should address any daylight savings issues. 

I will aim to have it out in the 4.0.0 release.

**Comment by zombieFox** [comment]
nightTab v4.1.0 using moment.js is now live on Chrome and Firefox. 
@mrdarkkwebss can you report back if the time is working as expected please?

**Comment by KolyaKorruptis** [comment]
It's working on Chrome but not on Firefox. I should say that I hadn't checked Chrome before.
No errors in the FF console.

**Comment by zombieFox** [comment]
I'm testing nightTab 4.1.3 in Firefox 72.0b2 (64-bit):


![Kapture 2019-12-05 at 13 47 54](https://user-images.githubusercontent.com/7115017/70240891-f521f300-1765-11ea-8a0a-ad3083083de2.gif)

I'm unable to recreate the issue. [Moment.js](https://github.com/zombieFox/nightTab/blob/master/src/js/clock.js#L23) is working as expected.

**Comment by KolyaKorruptis** [comment]
Nighttab 4.1.3 on Firefox Dev Edition 72.0b2
Still one hour behind system time (Windows 10 Version 1909)

**Comment by SpiCy0** [comment]
Do you have something like privacy.resistFingerprinting enabled, that could spoof the time zone/local time? I have the same problem and suspect that this is the cause, but I'm not sure.

**Comment by SpiCy0** [comment]
I have done some testing and have isolated RFP as the cause of my problem, and since you said you ha d a lot of privacy extensions and such, you might have installed one that enables RFP.

**Comment by mrdarkkwebss** [comment]
might be

**Comment by ExpertMen** [comment]
Please, reopen this issue, @zombieFox , I have this problem too - yes I also have privacy extensions installed, and time is wrong - how do I change timezone? - I am using LM 20.3, Cinnamon, LibreWolf. While it's evening now, nightTab thinks that new day is here, while in the USA (at least) not. It thinks that it's 21 April, but right now it is only 19:34 PM, 20 April, while nightTab is telling me that it is 34 minutes of a new day.

**Comment by iam-cult** [comment]
like i said in the above comment 

this is caused by privacy.resistFingerprinting

there is no way to keep RFP enabled and still get the correct time

either disable RFP or live with it
