### ISSUE TITLE
Bug: Beta release uses same database as stable

### ISSUE THREAD

**Issue by mcorossigo** [zombieFox/nightTab#112]
Hello @zombieFox 

I'm using nightTab Web as a startpage on Firefox. It's incredibly nice!
While looking around I visited https://zombiefox.github.io/nightTabBeta/ which updated the database to version 4.0.0, and after returning to the https://zombiefox.github.io/nightTab I found it completely broken, so that I had to reset it the hard way.

The console clearly stated that the problem was the data version.
This is completely understandable.

As a suggestion, maybe you can add a dev build flag that scope the beta data under different keys from stable. It would also be nice if you could handle a little more gracefully data version mismatch, as 

> nightTab version 3.80.0
> data version 4.0.0 found less than current

seems to be the default message for an update. No idea how to handle this TBH.

I realise that this is a very edge case, so I'm just reporting it.

**Comment by zombieFox** [comment]
Thanks for the report. Are you using the [demo nightTab](https://zombiefox.github.io/nightTab/) as your startpage? I host the Demo and Beta web versions on github and browsers assign local storage per domain. So, yes, there is a good chance they will overwrite each others settings or worse break the page.

> As a suggestion, maybe you can add a dev build flag that scope the beta data under different keys from stable. It would also be nice if you could handle a little more gracefully data version mismatch, as

I'll look into this as a way to avoid it however it would be safer to use the browser addons/extensions and not rely on the demo or beta pages.

**Comment by zombieFox** [comment]
I have deleted the nightTabBeta repo as it's just not working out. I may try again in the future but for now this will prevent any future conflict in sotored data.
