### ISSUE TITLE
Bug with Bookmark content alignment on bookmark names that take more than one line

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#113]
nightTab v4.0.0
Firefox v70.0.1 on Win10

Issue: Block style Bookmarks that have names that span two or more lines (the tiles have to be tiny enough for it) don't follow Content alignment settings properly (Bookmarks > Bookmarks > Content alignment).
In fact, they go in reverse:
Left aligned
![Screenshot (3)](https://user-images.githubusercontent.com/52709014/70026587-2368cc80-15c6-11ea-83e0-bcde0440d4d7.png)
Right aligned
![Screenshot (4)](https://user-images.githubusercontent.com/52709014/70026883-c883a500-15c6-11ea-90ab-ec65dffac8f4.png)
The Calendar tile is following the settings properly, the Send tile is going in reverse. Only happens when "Align contents horizontally" is selected.

**Comment by zombieFox** [comment]
Nothing like CSS bugs early in the morning 😄 Thanks for the report. I'll get a fix ready asap.

**Comment by Q-out** [comment]
Updated to v4.1.0 and 
![Screenshot (62)](https://user-images.githubusercontent.com/52709014/70112459-6afd6000-167b-11ea-8e41-948f854d09ba.png)
too much justification.

**Comment by Gerondolom** [comment]
There's also a bug with breaking bookmark names with multiple lines in a way, that they fit their box:

![broken](https://user-images.githubusercontent.com/50837763/70208663-78275700-172e-11ea-8f32-9b7025913ccf.png)

When I change the CSS at `.is-link-item-display-name-show .link-display-name` from `display: block;` to `display: contents;`, it works:

![works](https://user-images.githubusercontent.com/50837763/70208765-ab69e600-172e-11ea-960f-6874c7442179.png)

**Comment by zombieFox** [comment]
I've been testing a few fixes to this. This component makes heavy use of [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) to achieve the customisation of the alignment and order. 

Experiments:
- White dashed line = flex container
- Red box = icon
- Red solid line = examples of different length strings

The current version with `flex-basis: 1%` on the name:
![Kapture 2019-12-05 at 10 05 24](https://user-images.githubusercontent.com/7115017/70226880-8898fb00-1749-11ea-9f5a-9244585f22a6.gif)
Gives us predictable alignment but does not allow for text (with multiple words) length to grow.

A test with no `flex-basis` (so a default of `flex-basis:auto`):
![Kapture 2019-12-05 at 10 21 07](https://user-images.githubusercontent.com/7115017/70227050-d44ba480-1749-11ea-81b7-2c7a75a2c8cc.gif)

But allows for scenarios where, if the name string with multiple words is just long enough to break onto new lines, a large gap can appear:
<img width="201" alt="Screenshot 2019-12-05 at 10 31 13" src="https://user-images.githubusercontent.com/7115017/70227429-79ff1380-174a-11ea-84c6-d33a54b4d04b.png">

It does seem there is no simple solution to this problem as both `flex-basis: auto` or `flex-basis: x%` have downsides. So for now I will remove explicit `flex-basis` declarations. This at least _seems_ to have fewer downsides.

**Comment by Q-out** [comment]
The gap is much more preferable to some tiles getting aligned in reverse order, this is more consistent. Closing the issue. Thanks for explaining the options in detail.
