### ISSUE TITLE
Bug with Grow on hover animation with shadows disabled

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#114]
nightTab v4.0.0
Firefox 70.0.1

Here's a fun looking one.
![540_30_2 13_Dec032019](https://user-images.githubusercontent.com/52709014/70035434-d4786280-15d8-11ea-9f79-ab9fd840d215.gif)
Yeah those artifacts aren't from the gif compression. They're there on the tiles when "Grow on Bookmark hover" is enabled and "Show shadow on Bookmark hover" is disabled.
This is on a windows laptop with Intel iGPU so I'll try to reproduce this on my PC when I get back on it later and post back. In case this is some weird issue somewhere between the iGPU and FF Webrender.

**Comment by zombieFox** [comment]
Yikes, that is odd. Got to be honest, I have no idea what could be causing that. Please do report back when you try it out on the PC.

**Comment by Q-out** [comment]
Yeah it was the integrated GPU. It could maybe get fixed by updates to webrender in Firefox. But either way, it's nothing on nightTab's end. Would have been really strange if it was, tbh.
