### ISSUE TITLE
Feature Request: mass open groups by click

### ISSUE THREAD

**Issue by ronmurphy** [zombieFox/nightTab#115]
Maybe have a way, say, clicking the group name will cause the # of enclosed bookmarks to open up in new tabs.  This would super useful for logging in start of the day and not having to open up several sites.  maybe clicking the name just has a javascript parse the internal bookmarks and 

for x = 0 to group.tab,count
new tab > bookmark.url
next x

sorry for the crappy code example...  :/ 

Thanks for all the hard work that you have done on this!

**Comment by zombieFox** [comment]
> Thanks for all the hard work that you have done on this!

Cheers!

>  ... # of enclosed bookmarks to open up in new tabs. ...

Cool idea. I'll add it to the project board.

**Comment by zombieFox** [comment]
This feature is now live in [v4.44.0](https://github.com/zombieFox/nightTab/releases/tag/v4.44.0)
