### ISSUE TITLE
Page is Blank

### ISSUE THREAD

**Issue by smpldork** [zombieFox/nightTab#117]
When viewing the index.html files from the src folder, the page is blank.

How do you get this working on a self hosted server (nginx)?

**Comment by zombieFox** [comment]
Please refer to the **Development** section of the [readme](https://github.com/zombieFox/nightTab/blob/master/README.md) file. In short, if you wish to self host, build the project using node and gulp. Then move the files to where needed.

**Comment by AlfaJackal** [comment]
That works pretty easy, but seems useless for me unless all preferences are also stored on the hosted server and not locally.
