### ISSUE TITLE
Hover does not disappear

### ISSUE THREAD

**Issue by siomekziomek** [zombieFox/nightTab#118]
How to replicate:
1. Enable "open bookmarks in a new tab" option.
2. Open new tab and click on a tile. Your tab will switch for opened site.
3. Go back to the new tab.
4. Tile you just clicked now has hover until you click something else.
or
2. Open new tab and middle click a tile.
3. Site will open in background, while you will stay in new tab - tile you just clicked now has hover until you click something else.

I think this wasn't supposed to work that way. When you want to navigate to another tile, the last opened one still has hover - as well as the one currently pointed at - which is a bit distracting and confusing.

Cheers

**Comment by zombieFox** [comment]
Hi, this is expected behaviour as bookmark tiles must have a [focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) state. If a link is clicked and gains focus the Bookmark UI changes. The focus will not move unless the user clicks something else.
