### ISSUE TITLE
Feature Request: Custom CSS support

### ISSUE THREAD

**Issue by Excigma** [zombieFox/nightTab#119]
It would be great to allow some people to write their own CSS to be injected into the page, for instance, changing the font, adding shadows to elements etc.

**Comment by Excigma** [comment]
Another request, for Firefox users this extension does not replace the homepage (about:home), which Firefox uses when launching, so when launching, Firefox does not load this extension's age but loads the normal about:home page instead. This is Firefox's problem but can be fixed by setting this:
![image](https://user-images.githubusercontent.com/30280397/70677845-33368e00-1cf5-11ea-84d3-3a3344ad5cda.png)

However people need to paste `window.location` into the console to get this url, it would be nice if the extension could give this to us

**Comment by zombieFox** [comment]
> It would be great to allow some people to write their own CSS to be injected into the page, for instance, changing the font, adding shadows to elements etc.

Hi, I'm not sure I understand the use case for this feature request. If users wish to modify the code the project can be cloned and installed locally. Adding support for custom CSS from the UI seems like a major feature and would be a lot of work. Sorry I don't see this becoming a feature.

---

> Another request, for Firefox users this extension does not replace the homepage (about:home), which Firefox uses when launching, so when launching, Firefox does not load this extension's age but loads the normal about:home page instead. This is Firefox's problem but can be fixed by setting this:
> ![image](https://user-images.githubusercontent.com/30280397/70677845-33368e00-1cf5-11ea-84d3-3a3344ad5cda.png)

This has been brought up before. Firefox addons can not replace the "homepage" but users can manually set to do this. Please see #55 for steps.

> PS: This is easily my favorite new tab page, with tons of options, and ways to export and import the data in case you lose it

Thank you!
