### ISSUE TITLE
Cannot add new bookmarks anymore

### ISSUE THREAD

**Issue by sinankizar** [zombieFox/nightTab#120]
Actually I can add new bookmarks but they don't work as expected. Newly added bookmarks has something like this:
moz-extension://75d246cd-2945-4594-a688-33fc0c284819/192.168.1.100

Actual bookmark is 192.168.1.100 but after adding the bookmark the link converts to that. 

Thanks in advance :)

**Comment by Excigma** [comment]
I'm not sure, but what if you add http:// in front of it? It works for 172.217.167.110 - Google, and 1.1.1.1 - Cloudfare

**Comment by sinankizar** [comment]
Yes if I add http on it, it works. Tried with https and that worked too on another IP.

**Comment by zombieFox** [comment]
Hi, sorry I'm not following the issue. @sinankizar can you provide steps to recreate the problem please? including browser and nightTab versions please.

**Comment by sinankizar** [comment]
> 
> 
> Hi, sorry I'm not following the issue. @sinankizar can you provide steps to recreate the problem please? including browser and nightTab versions please.

FF: 71.0
NightTab: 4.1.3

If you create a bookmark without http:// or https:// the problem creates itself:

![Untitled](https://user-images.githubusercontent.com/28201097/71157454-18af6800-2253-11ea-97f4-a78bf17d4455.png)

**Comment by zombieFox** [comment]
This is expected behaviour as a bookmark is an [anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) and respect the local or absolute paths given to them. So a valid website URL needs the protocol included. It is also stated on the new bookmark modal:

![Screenshot 2019-12-19 at 09 19 32](https://user-images.githubusercontent.com/7115017/71161201-d54bfe00-2240-11ea-81cc-bf3061e4cb1e.png)

**Comment by zombieFox** [comment]
Further: if a protocol is not included in a URL the browser will treat the anchor local to the extension/add on. That is why you are seeing the URL as `moz-extension://.../www.google.com`. Firefox is treating the path as local to the extension/add on install location.

**Comment by sinankizar** [comment]
Thanks for the clarification. This is not an issue then, just the way the nighttab works. Thanks again for this great addon.

**Comment by zombieFox** [comment]
Happy to help. 😺  Closing the issue.
