### ISSUE TITLE
Feature Request: Change background color of the bookmarks

### ISSUE THREAD

**Issue by maxnatt** [zombieFox/nightTab#123]
Currently it is possible to change background color of page and accent color of bookmarks. But because in certain combinations background color of bookmarks will be just out of its place, it would be great to customize bookmark's background as well.

**Comment by zombieFox** [comment]
Already [working on it](https://github.com/zombieFox/nightTab/projects/1#card-30804460):

![Kapture 2019-12-22 at 13 38 45](https://user-images.githubusercontent.com/7115017/71322543-88765a80-24c0-11ea-8588-50efcc4a7a9d.gif)

**Comment by zombieFox** [comment]
nightTab uses a spread of colours derived from one primary colour. The bookmark background is one of the shades from this spread. So this new feature will allow users to pick that primary colour and change the UI colour throughout nightTab.

**Comment by zombieFox** [comment]
Feature is now live in v4.19.2 Naughty Goose 🚀
