### ISSUE TITLE
Nighttab as homepage

### ISSUE THREAD

**Issue by pjhalsli** [zombieFox/nightTab#126]
I want to use nighttab as my homepage/startapge but now it open in every new tab which I don't want. I just want it to be my startpage and tabs open as usual. How can Ifix this.  Right now I'm using the extension in firefox but earlier I had it locally on my computer and then it worked as I wanted it to do.

Also it doesn't work in opera anymore - I had to change to FF to get it to work. But whan I had it locally on my comp it worked fine in opera too.

**Comment by zombieFox** [comment]
Hi, Sorry to say Firefox addons can not replace the "homepage" but users can manually set it to do this. Please see #55 for steps.

**Comment by pjhalsli** [comment]
thanks for your answer.  Will look into it. Closing this now
