### ISSUE TITLE
Not a JSON file. Make sure the selected file came from nightTab.

### ISSUE THREAD

**Issue by 404cn** [zombieFox/nightTab#129]
I export data from my mac and i want use it in my linux pc, but it is not work.

Here is the json file.

[nightTab.json](https://gist.github.com/404cn/a0a691f8ddf85b2dd6a3901f688725a4)

**Comment by zombieFox** [comment]
Hi, thanks for the feedback and providing the sample file.

I've investigated and can see this is a know issues. Please see [issue 106](https://github.com/zombieFox/nightTab/issues/106) for details.

In short, [JSON parse](https://github.com/zombieFox/nightTab/blob/master/src/js/data.js#L209) does not seem to support special characters. I've not resolved this issue as of yet. I'll be continuing to work on this.

I can see the bookmark for `https://www.gamersky.com/` has a character which, when imported, causes the file to not pass as valid JSON. When inspecting the file I can see it as `"letter": "8z"`
