### ISSUE TITLE
Brave Rewards?

### ISSUE THREAD

**Issue by peepoboi** [zombieFox/nightTab#130]
Howdy partner! Absolutely love the design, it's 500x better than the current Brave Browser design they have going on. 

Although, I have a interesting question, and if at all possible.

"Brave rewards" - - [CLICK ME FOR PICTURE](https://i.imgur.com/KdqpmiE.png)
it's a little widget to track your earnings whilst on the brave browser, so it's a _**long shot**_ to request if this could be implemented for those on brave to continue tracking on the new-tab. 

I would attempt myself but I have no clue where to start. 

Thanks regardless! Keen to see the future for this extension.

**Comment by zombieFox** [comment]
Hi, thank you very much!

Sorry to say, I don't know anything about Brave. A quick google and I can't find if the browser allows access to that date or if it has an API. 

Is this a profile specific feature? If so i don't think I will be able to develop a feature around is as nightTab intentionally does not access user information. This is to avoid data protection concerns etc.

Can you provide any documentation of Brave rewards please?

**Comment by zombieFox** [comment]
Closing this issue as it's something I can't follow up on.
