### ISSUE TITLE
Start page is the default Firefox one, not nightTab

### ISSUE THREAD

**Issue by Gagnef03** [zombieFox/nightTab#132]
When you start Firefox, the default start page comes up, not nightTab.

**Comment by Gagnef03** [comment]
Fixed by putting _moz-extension://35e8b9cb-9f6c-4e9c-9318-34986cee0cb2/index.html_ as the "custom URL" in the Firefox settings.

**Comment by zombieFox** [comment]
Hi, Sorry to say Firefox addons can not replace the "homepage" but users can manually set it to do this as you have found. Also see #55 for another solution.
