### ISSUE TITLE
Changing Font - Further Inspection how to get 4.8.3 

### ISSUE THREAD

**Issue by HermesTheDev** [zombieFox/nightTab#133]
Can you add a feature in the menu that allows a user to change the font? Or is there a way to do this in the CSS.

Edit: I have installed the latest Firefox Extension but on further inspection, I see that you have already added this to your latest version. How do I get the latest version in Firefox with the option that allows me to change the font?

I'm running 4.1.3 but I think the latest version is 4.8.3. How do I get 4.8.3 running on my PC

**Comment by zombieFox** [comment]
Hi,

The latest published version to Firefox and Chrome webs stores is v4.1.3. I'm in the middle of developing a host of new Theme bases features, (including changing the font). I am aiming to releasing these features in about a week. (v4.8.3 is tagged as a release on github and a further release is coming soon.) 

Also see issue #134 for more details.
