### ISSUE TITLE
Firefox extension hasn't been updating

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#134]
Still on version 4.1.3 at [AMO](https://addons.mozilla.org/en-US/firefox/addon/nighttab/).

**Comment by zombieFox** [comment]
Hi, the most up to date version of nightTab on Firefox and Chrome is still 4.1.3. I have not published the most recent updates as I am still developing and testing new features. (I'm assuming you have noticed the most recent updates on github) 😉 

I expect updates will be published to Firefox and Chrome in a week or so.

**Comment by Q-out** [comment]
Okay, good to know! I noticed the now-disappeared 4.6 versions too 👀 Changelog looking good.

**Comment by zombieFox** [comment]
> now-disappeared 4.6 versions too
Yup, I messed something up there and had to remove those versions from git tagging. Oops.
