### ISSUE TITLE
[Feature Request] Custom colour for background image opacity

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#138]
Currently Background > Image > Opacity uses the Theme/Custom background colour option which also changes the header colour. I feel like with the new theme options those two colours are better separated.
What I need is to darken the background image; I'd set the new colour to #000000 with the slider at 40/100 or so, and let the background (or rather, the header) retain the colour from the theme.
Or a darken filter slider separate from the opacity filter would also work.

**Comment by Q-out** [comment]
Just noticed [this commit](https://github.com/zombieFox/nightTab/commit/1832e01c1d61ad503a975db9df2bfd4f934ad7a2). Perhaps you've already addressed this issue.

**Comment by zombieFox** [comment]
That is a good idea. It fits with the new theme features to allow the header background to also be controllable. (Also CSS filters does not have a "darken" features, sadly). As such I've added a custom colour control for the header background:

![dev](https://user-images.githubusercontent.com/7115017/72559937-e0c13200-389d-11ea-8205-ed53860dd5a5.png)

> Just noticed this commit. Perhaps you've already addressed this issue.

Sorry, that change is unrelated.

I'll push out another update to the Chrome extension and Firefox addons with this feature asap.

**Comment by zombieFox** [comment]
Feature is now live 🚀
