### ISSUE TITLE
Blank release notes when extension updates on Firefox

### ISSUE THREAD

**Issue by geeknik** [zombieFox/nightTab#139]
When the Firefox extension updates, there are no release notes listed. 

![Screenshot_2020-01-18_10-31-02](https://user-images.githubusercontent.com/466878/72667116-3c133180-3a10-11ea-8476-64c4e07ff4e1.png)

Release notes for other extensions appears to be working okay.

![Screenshot_2020-01-18_10-32-24](https://user-images.githubusercontent.com/466878/72667144-767cce80-3a10-11ea-9e89-b336fe10c6df.png)

**Comment by zombieFox** [comment]
That is really strange as I always put a lot of information in the update field when publishing. I'll investigate.

**Comment by zombieFox** [comment]
This seems to be a problem with Firefox retrieving the data from their servers. The information is included in the release (I include all relevant git commit messages in all releases notes):

<img width="744" alt="Screen Shot 2020-01-22 at 09 22 50" src="https://user-images.githubusercontent.com/7115017/72881555-de753280-3cf8-11ea-9794-38dfa297a3dc.png">

And can see it is working during my tests on Firefox 72.0.2 Mac OSX:

<img width="698" alt="Screen Shot 2020-01-22 at 09 22 59" src="https://user-images.githubusercontent.com/7115017/72881630-05cbff80-3cf9-11ea-86db-461b019e8f4f.png">
