### ISSUE TITLE
[Feature Request] Option for hiding scrollbar

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#142]
Pretty self explanatory; I've only got a few entries in list style overflowing the page, and realistically I'll never bother reaching for the scrollbar with the cursor just to reach those entries.

![Screenshot (12)](https://user-images.githubusercontent.com/52709014/72830286-6aaa3a00-3ca6-11ea-8f95-5bbe973225b1.png)

More importantly, it's ugly on an otherwise beautiful page.

**Comment by Excigma** [comment]
Also it would be nice to have a option for `scrollbar-width: thin;` for Firefox users

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

**Comment by zombieFox** [comment]
I'm not seeing the scroll bars on Mac OS. But I know Windows keeps bars visible most of the time. Using something like `overflow-y: hidden` will break the page and prevent content outside the viewport from being reached by the user.

@Q-out do you have bookmarks filling the page? If so the scroll bars will be displayed by the browsers.

@Excigma I didn't know about that property. I'll see to adding it.

**Comment by Q-out** [comment]
If you check out the `scrollbar-width` property linked by Excigma, you'll see that it also supports the value of `none`. If I force the scrollbar to change by using `* { scrollbar-width: none !important }` in my [usercontent.css](http://kb.mozillazine.org/index.php?title=UserContent.css), it removes the scrollbar but keeps the content scrollable:
![image](https://user-images.githubusercontent.com/52709014/73059718-5049a980-3ebc-11ea-82fa-6b0839a9e8c9.png)
Here's `* { scrollbar-width: thin !important }`:
![image](https://user-images.githubusercontent.com/52709014/73059973-e4b40c00-3ebc-11ea-9d3a-20fef1d26fd6.png)
Only Firefox would support it if you implemented that property though. So I was hoping there was another way to do it for all browsers because feature parity is a nice-to-have. Although, other OS-browser combos may have better looking scrollbars, and Win-FF has that one which is better off hidden (or replaced with the thin one).

**Comment by zombieFox** [comment]
> you'll see that it also supports the value of `none`. 

Excellent! Didn't know "none" was an option. That is a better solution than trying anything funky with `overflow` or measuring the height of the page with JS (which can get expensive fast). I'll work that into the project asap. 

> other OS-browser combos may have better looking scrollbars

Yep, very true.

**Comment by zombieFox** [comment]
Giving this a bit more thought: hiding all scrollbars may bring up accessibility issue so this may not be an active feature all the time but rather an option which can be turned on from the menu.

**Comment by Excigma** [comment]
Yeah, hiding all scrollbars would be feel different for some people who may prefer to have them, OP did ask for it to be an option.
In regards to Chrome, it seems to have:
```css
::-webkit-scrollbar {
    display: none;
}
```
From the top answer of: [https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll](https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll)

**Comment by zombieFox** [comment]
> In regards to Chrome, it seems to have:

Awesome, I [added that](https://github.com/zombieFox/nightTab/blob/master/src/css/layout.css#L49) too. Working well enough in Chrome 79.0.3945.130.

**Comment by Q-out** [comment]
Thanks!
