### ISSUE TITLE
Open search results in new tab?

### ISSUE THREAD

**Issue by nickjcoco** [zombieFox/nightTab#146]
Curious if I might just be missing something in the settings, but is it possible to open the search results from the search bar in another tab? Effectively right now, searching for something other than a bookmark replaces the nightTab window with the search results page. It would be cool to be able to have the results page open in a new tab just like the bookmarks do. I'm using the Firefox addon currently in Firefox v73.0. Not a dealbreaker, but a nice QoL improvment maybe!

**Comment by zombieFox** [comment]
Sounds like a good feature and should be possible. I'll see to what I can do.

**Comment by nickjcoco** [comment]
That would be awesome, thanks! I could hack it out in CSS, but I've not yet touched JS so I wouldn't quite know where to start. :stuck_out_tongue_closed_eyes:

**Comment by zombieFox** [comment]
No probs. I've now [added a feature](file:///Users/kuldeepm/Documents/GitHub/nightTab/dev/index.html#menu-content-header-search) for this. It will be released in the next update.

**Comment by zombieFox** [comment]
No probs. I've now [added a feature](https://github.com/zombieFox/nightTab/commit/926bb35ed543fb62c4c63b64e10dd9ada133f2fa) for this. It will be released in the next update.

**Comment by nickjcoco** [comment]
Great! I'm excited to test it out. Thanks a lot.

**Comment by zombieFox** [comment]
This feature is now live in [v4.44.0](https://github.com/zombieFox/nightTab/releases/tag/v4.44.0)
