### ISSUE TITLE
Saves data to local storage does not support Chinese characters, please fix

### ISSUE THREAD

**Issue by geekbb** [zombieFox/nightTab#147]
Saves data to local storage does not support Chinese characters, please fix

**Comment by zombieFox** [comment]
This is a know issues which is being investigated. A fix is currentley in testing.
Please see #106 for details.

**Comment by zombieFox** [comment]
A fix is now live for this issue on version [v4.44.0](https://github.com/zombieFox/nightTab/releases/tag/v4.44.0). I've been testing with characters listed in this issue as well as others I could find [on this table](http://www.fileformat.info/info/charset/UTF-8/list.htm). It's working for me.

**Comment by geekbb** [comment]
Thank you, Chinese characters are working properly

**Comment by geekbb** [comment]
Thank you, Chinese characters are working properly

**Comment by zombieFox** [comment]
Awesome!
