### ISSUE TITLE
[Feature Request] Font Inner - Outer shadow w/colors

### ISSUE THREAD

**Issue by Henyckma** [zombieFox/nightTab#150]
It's just a nice to have. :D You can close this issue if you think its not necessary.
Thank you so much!

**Comment by Excigma** [comment]
Possible with: 
https://css-tricks.com/adding-stroke-to-web-text/
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke

However it seems to be non-standard, and perhaps you'll need to use text-shadow?

**Comment by zombieFox** [comment]
Sounds interesting. I've looked into this in the past. It was a bit tricky.

@Henyckma I'd like to see what can be done. How did you imagine this working? Like the current shadow control found in the Theme section? 

For good practice, I would like to avoid non-standard styling which might not work on both Firefox and Chrome.

**Comment by zombieFox** [comment]
I've added controls for [bookmark letter and icon shadows](https://github.com/zombieFox/nightTab/commit/819cdf7946dd45534ecced86b33a0191735a6046):

<img width="1468" alt="Screen Shot 2020-06-10 at 23 52 59" src="https://user-images.githubusercontent.com/7115017/84326720-89d23700-ab75-11ea-86d9-c16588f1050e.png">

It's a first pass avoiding non-standard CSS. Colour control of the shadow is out of scope as it's really difficult to build controls for it. It would essentially be building a full blown [CSS text shadow generator](https://css3gen.com/text-shadow/). And I don't believe people need that level of control.

**Comment by zombieFox** [comment]
This feature is now on live 🚀
