### ISSUE TITLE
Cannot add bookmarks of Chrome URL's (Like Apps page or Bookmarks page)

### ISSUE THREAD

**Issue by Henyckma** [zombieFox/nightTab#152]
Hello,

When adding any of the Chrome URL's from "chrome://chrome-urls/" as a new bookmark into nightTab, nightTab is unable to open the Chrome URL, and if opening in a new tab the bookmark from nightTab does not work as well.

I have attached the evidence.
Thank you so much!

[screen-capture (4).webm.zip](https://github.com/zombieFox/nightTab/files/4245369/screen-capture.4.webm.zip)

**Comment by Q-out** [comment]
Pretty sure that's a security feature by the browser, that a browser's own pages cannot be linked to by potentially malicious webpages. You can't open about:support etc on Firefox like this either. I don't think zF can do anything about it.

**Comment by zombieFox** [comment]
This may be a case of protected URLs which can not be accessed by extensions for security reasons: https://stackoverflow.com/a/40364397

> "chrome:// is a privileged origin, and any attempt to open it will result in a redirect to about:blank."

**Comment by zombieFox** [comment]
Closing this issue as there is nothing to fix.
