### ISSUE TITLE
[Feature Request] Show/Hide "Open all" button per group

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#153]
The new Open all button seems really useful. But I don't need it for each and every group.

Leaving the current option to hide that button in Settings > Groups as a "Master" option to hide all the buttons, could you add individual toggles for each group? Maybe they'd make sense here in the edit group popup:
![Screenshot (15)](https://user-images.githubusercontent.com/52709014/75249825-01fe3200-57fd-11ea-927e-15a48587ca9d.png)

**Comment by zombieFox** [comment]
Sounds like a nice enhancement. I'll add this to the project board 👍

**Comment by zombieFox** [comment]
Should be possible by storing a value in the [group object](https://github.com/zombieFox/nightTab/blob/master/src/js/link.js#L3):

```
group: {
  name: "...",
  items: [...],
  openAll: true
}
```

Then adding another check on the [render step](https://github.com/zombieFox/nightTab/blob/master/src/js/link.js#L476):

```
if (state.get.current().group.openAll.show && stagedGroup.group.items.length > 0 && stagedGroup.group.openAll) {
  groupHeader.appendChild(groupHeaderItemOpenall);
};
```

**Comment by zombieFox** [comment]
On master branch!
https://github.com/zombieFox/nightTab/commit/74ea775af1897934ed793dac6f826be72b5a7a6a

**Comment by zombieFox** [comment]
This feature is now live on the extension/addon.
