### ISSUE TITLE
[Question] Is there any way to make your add-on the home page in Firefox?

### ISSUE THREAD

**Issue by Luisoncm** [zombieFox/nightTab#156]
I definitly love your add-on for my work. I already have it in Chrome and Firefox, but I can't make the start page of your extension the home page. 
Do you know how? 

Thanks million for your work!!

**Comment by zombieFox** [comment]
Hi, this has been requested before. Add ons can not replace the "homepage" (see #126 and #55) but there is a solution where the end user sets an Add on as the homepage url. The instructions for the workaround can be found in the [readme](https://github.com/zombieFox/nightTab#setting-nighttab-as-your-firefox-homepage).

**Comment by Luisoncm** [comment]
It works perfect. Sorry I didtn't read the README carefuly before asking you. 

Thanks million!!

**Comment by zombieFox** [comment]
Glad it's working for you 😃
