### ISSUE TITLE
[Feature Request] Allow to change Search Bar Opacity

### ISSUE THREAD

**Issue by Excigma** [zombieFox/nightTab#157]
It would be nice to have an option to change the Search bar opacity, and although I'm happy with the border radius, as it works with Firefox, it would be nice to have a completely rounded sides option for a Chrome-like look

**Comment by zombieFox** [comment]
Hi, the recent 4.44.0 update introduced the Style controls for the search bar, allowing Clear or Box. Are these what you are looking for?

For the border radius, do the controls under Theme > Radius > All corners not fulfil this requirement?

**Comment by Excigma** [comment]
I saw that, but Clear is too transparent, and Box is too opaque
Here's what it looks like now with Box
![image](https://user-images.githubusercontent.com/30280397/75961497-00ccb380-5f27-11ea-9e5c-0c5639a7dcde.png)

**Comment by Excigma** [comment]
I have a few minor feature requests but I don't want to open a lot of new issues, I don't know where to post them

Do you have a Discord server we could easily talk in perharps?
I guess more users are likely to have Discord than Github with Github being focused to programmers, so normal users can request features without creating a Gh account

**Comment by Q-out** [comment]
I came here to request this exact feature. Everything has fine controls and sliders now, opacity for the search bar only has a toggle box. It would make sense for it to have an opacity slider as well.

In the same vein, I was also going to request opacity settings for the bookmark boxes as well. They're the only thing that cannot go transparent or translucent right now, and I think it can be used with certain wallpapers for good effect. I imagine a graphic artist could also whip up a custom wallpaper with custom backgrounds for the bookmarks for themselves (and for sharing with others).

> I don't want to open a lot of new issues

I've seen multiple minor – and some slightly less so – requests in a single issue before. There's one here #25. I guess you could do that.

**Comment by zombieFox** [comment]
I'll see what I can do about opacity controls. The inputs and buttons use global styles so some refactoring might be needed to make that happen. I'll make a ticket for this.

The bookmarks however are made of two sections, the front and back panels (the back being where the edit and url controls live). Adding opacity to them just causes the back panel to show through:

![Kapture 2020-03-09 at 15 26 32](https://user-images.githubusercontent.com/7115017/76229954-e6425500-621a-11ea-9a32-e5b33ed395f6.gif)

This is something I have been investigating for a while now -- more investigating is needed. I've looked into using CSS clip-path to hide parts of the back panel but depending on the browser and system, the rendering may result in a line or gap between the panels.

**Comment by zombieFox** [comment]
> Do you have a Discord server we could easily talk in perharps?
> I guess more users are likely to have Discord than Github with Github being focused to programmers, so normal users can request features without creating a Gh account

I'm sorry, I don't use Discord. I would prefer tickets on github as I don't have time to monitor a chat client. Happy to have a ticket full of small requests/issues as @Q-out mentioned. 

I've consdered making a subreddit (maybe /r/nightTab), but that also is post/ticket styled, like github.

**Comment by Q-out** [comment]
Now I get how the bookmarks work. I guess transparent bookmarks would mess with the bookmark line and url on hover features, which are pretty much the items that defined the original look of nightTab.

Maybe you could make an option that, when enabled, turned those two features off and turned the back panel transparent, while enabling opacity controls for the bookmark tiles.
Would that even work? I don't know. Would people appreciate such an option? I'm not sure. Just an idea.

**Comment by zombieFox** [comment]
I was thinking just that, if an option to change the bookmark opacity is used then bookmark line and the bookmark URL would be set to `false`. 

Or, following the patterns set out in other parts of the settings menu, the bookmark opacity is only available (enabled) when bookmark line and URL is set to `false` by the user. (I'm aiming to avoid chaning settings without the user knowing).

**Comment by zombieFox** [comment]
Ok, working on a `clip-path` heavy solution to bookmark background opacity:

![Kapture 2020-03-25 at 11 31 01](https://user-images.githubusercontent.com/7115017/77532126-285ece00-6e8c-11ea-8043-f81d2502b1a2.gif)

**Comment by zombieFox** [comment]
Some refactoring later, Header Search, Edit/Add, Colour/Accent, Settings Menu and Group Open All controls now [have opacity slider controls](https://github.com/zombieFox/nightTab/commit/1fa622f24d0c9f43395fa52e6d5c7993ee04e276).

**Comment by zombieFox** [comment]
![Kapture 2020-03-27 at 8 59 35](https://user-images.githubusercontent.com/7115017/77739611-b3b19e00-7009-11ea-9162-2763afc507bc.gif)

These features will be out in the next update.

**Comment by zombieFox** [comment]
Opacity controls are now live
