### ISSUE TITLE
Disable Groups

### ISSUE THREAD

**Issue by smaragdus** [zombieFox/nightTab#159]
[nightTab](https://github.com/zombieFox/nightTab) is the best speed dial extension I have ever tested- highly customizable (including a good set of themes), free, open source, it supports both Chromium and Firefox. I did some tests and I find this extension very pleasing so I would like to thank the developer for his good work.

I am still using **Speed Dial 2** ([Website](https://speeddial2.com/), [Chrome Web Store](https://chrome.google.com/webstore/detail/speed-dial-2-new-tab/jpfpebmajhhopeonhlcgidhclcccjcik), [Firefox Extensions](https://addons.mozilla.org/en-US/firefox/addon/new-tab-speed-dial/)) but I would like to switch to **nightTab** as soon as possible since **Speed Dial 2** is not open source and I do not like its [Privacy Policy](https://speeddial2.com/privacy-policy). What I like about it is that all the bookmarks are not grouped and thus much vertical space is saved, screen:

![Cent Browser 4 1 7 182 - 2020-03-10 - 001](https://user-images.githubusercontent.com/9025757/76265672-e28bee00-626d-11ea-915a-a29bd3afb514.png)

My request is an option to disable groups so that all bookmarks would appear ungrouped in a single list. If there is such an option I will immediately switch to **nightTab**. I suppose that disabling groups would not require too much work.

**Comment by Q-out** [comment]
If you disable Group Names, disable Open All button, and set Group Borders to 0 in Settings > Groups, and use a single group for all your bookmarks, all your bookmarks should appear ungrouped.

And with those settings, even if you did use groups, barely any vertical space is wasted:
![Screenshot (18)](https://user-images.githubusercontent.com/52709014/76282577-0f67f180-62be-11ea-83d1-68533edb67ec.png)

**Comment by zombieFox** [comment]
Thank you @Q-out for answering. 

@smaragdus, As described above, using a single Group for all the bookmarks is how to achive what you are after.

**Comment by smaragdus** [comment]
@Q-out 
Excellent tip and screen, thank you!

@zombieFox 
As what I wanted is achievable I will close this issue.

**Comment by smaragdus** [comment]
@Q-out 

I did a brief testing following your instructions and what I achieved is exactly what I desired! I am sorry I overlooked these settings.

BIG THANK YOU!

**Comment by Q-out** [comment]
No problem! nightTab has gotten very feature-rich these days after all. And anybody can miss a setting or two.

**Comment by smaragdus** [comment]
@Q-out 

I was testing **nightTab** not on my default browser but on my test browser and I was hastily switching between them comparing [nightTab](https://github.com/zombieFox/nightTab) with [Speed Dial 2](https://speeddial2.com/). In fact I was searching for a replacement of closed source **Speed Dial 2** extension for quite some time and a couple of days ago I finally come upon what I was looking for by chance. Tonight I will switch from **Speed Dial 2** to **nightTab** in my default browser (I will have to copy all my dial bookmarks in the right order). I tested many similar extensions and none of them was to my liking. Now that I discovered **nightTab** (what a great serendipity!) I am completely satisfied. I am glad that there are helpful users like you! Thank you for taking your time to give me useful tips and to take a screen shot.

Best regards

**Comment by zombieFox** [comment]
@smaragdus glad the project is of use to you!

> ...nightTab has gotten very feature-rich these days after all. And anybody can miss a setting or two.

Yes. There are a lot of options, users can easily hit analysis paralysis. I've been giving this some thought and am still considering other ways to present the options in the menu. (the sub nav section in the menu have been a way to deal with it). I'll continue to work on this.

**Comment by smaragdus** [comment]
@zombieFox 

I finally switched to [nightTab](https://github.com/zombieFox/nightTab), I feel like reborn, I suppose that my browser has the same feelings. Backup/Restore is working well which is great as I will be able to import data from my default browser ([Cent Browser](https://www.centbrowser.com/) - Chromium fork) to my secondary browser ([Iceweasel](https://sourceforge.net/projects/libportable/) - Firefox fork). By the way your [Demo Page](https://zombiefox.github.io/nightTab/) was of great help to me as I was using it to paste data copied from [Speed Dial 2](https://speeddial2.com/) and then to export data to file in order to import settings in my default browser later. By the way I think I came across a tiny glitch- it seems that when the browser window is in non-maximized state the bookmarks thumbnails (in my case- `Bookmark Size - 80`) do not scale down, screen:

![Cent Browser 4 1 7 182 - 2020-03-11 - 003](https://user-images.githubusercontent.com/9025757/76365775-da48b700-6330-11ea-98ef-95b6f6d7f1f7.png)

The size of bookmarks thumbnails is the same in maximized and non-maximized state of browser window. Have you noticed this?

> Yes. There are a lot of options, users can easily hit analysis paralysis. I've been giving this some thought and am still considering other ways to present the options in the menu. (the recent redesigned sub nav section in the menu was a way to address this). I'll continue to work on this.

For me the settings panel is perfect and in my opinion the categories are well-organized. I failed to notice some options because I was very impatient to start using the extension after I had been searching for a good speed dial for so long.

Overall I am very pleased with your extension yet I may suggest some enhancements in the future. I would like to let you know that I never expect all my ideas and suggestions to be implemented.

Many thanks for creating and maintaining this superb extension!

Best regards
