### ISSUE TITLE
Rearrange Bookmarks via Drag&Drop

### ISSUE THREAD

**Issue by smaragdus** [zombieFox/nightTab#160]
I suppose that this might require a lot of work but I would highly appreciate if the bookmarks can be rearranged via drag&drop as this would spare the user the effort to hit Edit and manually set bookmark position.

**Comment by Q-out** [comment]
When you are in edit mode, the second button under the bookmark tiles 
![Screenshot (19)](https://user-images.githubusercontent.com/52709014/76283262-31627380-62c0-11ea-9c85-6016d6a59765.png)
can be dragged around to move the bookmark, and the arrow buttons on left and right to it will move the bookmark one space left or right respectively. Hope that was what you needed.

**Comment by zombieFox** [comment]
Thank you @Q-out for answering again. 

@smaragdus, As described above, each Group and Bookmark has controls to move and sort.

**Comment by smaragdus** [comment]
@Q-out 
Thank you again for the useful tip.

@zombieFox 
What was described above really works but I find drag&drop handier because it does not require use of buttons. If this cannot be implemented feel free to close this issue.

**Comment by zombieFox** [comment]
@smaragdus Sorry I don't understan. nightTab does have drag an drop on each Group and Bookmark. Is this not working for you?

**Comment by smaragdus** [comment]
@zombieFox 

Excuse me, somehow I overlooked that the drag&drop button should be active. I am closing this issue. Thanks.
