### ISSUE TITLE
Clock - Date Format - Dash in stead of Slash

### ISSUE THREAD

**Issue by smaragdus** [zombieFox/nightTab#161]
The clock is already very customizable and this is the closest to my liking, screen:

![nightTab 4 44 0 - 2020-03-10 - 002](https://user-images.githubusercontent.com/9025757/76267741-6c3eba00-6274-11ea-8f9b-995e81ec8ac9.png)

But I will appreciate an option to use dashes in stead of slashes, example:

- **current** - `02:00 10/3/2020`
- **desired** - `02:00 10-3-2020`

Also, I would prefer `10-03-2020` in stead of `10-3-2020`.

Of course this is cosmetic and insignificant but I suppose that such new options would be easy to be implemented.

**Comment by zombieFox** [comment]
Hi, I'm surprised no one has requested this before. I've been expecting it for since I released the first version 😄

I'll add this to the backlog 👍

**Comment by smaragdus** [comment]
@zombieFox 

Thank you for the quick response and for adding this to your to do list. I suppose you will also keep slash option so that the users who prefer slashes won't be disappointed. I really prefer dashes but I suppose that if [nightTab](https://github.com/zombieFox/nightTab) used dashes I would have requested slashes.

**Comment by zombieFox** [comment]
Feature is on master. It will be released in the next update.

<img width="555" alt="Screenshot 2020-03-21 at 17 49 17" src="https://user-images.githubusercontent.com/7115017/77232980-4da5c080-6b9c-11ea-9380-b013ba6145b9.png">

**Comment by zombieFox** [comment]
Feature is now on live
