### ISSUE TITLE
New Search Providers

### ISSUE THREAD

**Issue by smaragdus** [zombieFox/nightTab#162]
The developer may consider adding 3 new search providers to search engine settings:

- [Qwant](https://www.qwant.com/)
- [Wikipedia](https://en.wikipedia.org/wiki/Main_Page)
- [Wiktionary](https://en.wiktionary.org/wiki/Wiktionary:Main_Page)

[Qwant](https://www.qwant.com/) is a good alternative to [DuckDuckGo](https://duckduckgo.com/) while [Wikipedia](https://en.wikipedia.org/wiki/Main_Page) and [Wiktionary](https://en.wiktionary.org/wiki/Wiktionary:Main_Page) are quite common.

It would be very handy if the user could change the search engine from the search box but I do not know whether this is feasible.

**Comment by zombieFox** [comment]
I've had a look at Wiktionary and Wikipedia, they don't seem to support the same search query pattern as the other search engines (eg, `https://www.youtube.com/results?search_query=`). So some investigation would be needed.

**Comment by smaragdus** [comment]
@zombieFox 

This is really not important. If the search providers I mentioned above cannot be added to [nightTab](https://github.com/zombieFox/nightTab) I won't be disappointed at all, I can add these sites as bookmarks too. Also, I use a very useful search extension- [ContextSearch](https://github.com/ssborbis/ContextSearch-web-ext), screen:

![ContextSearch 1 19 2 - 2020-03-10 - 002](https://user-images.githubusercontent.com/9025757/76330318-6093d780-62f6-11ea-9d20-dbc4a4823d27.png)

So searching is not a problem. Please feel free to close this issue at any time.

**Comment by zombieFox** [comment]
Did some more investigating. Wiki just won't work with the project. 

Qwant can be added as a search option using the Custom controls in `menu > header > search > custom`. 

Closing the ticket as I can't do much more.
