### ISSUE TITLE
[Feature Request] Several additions to Data Export and Import

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#163]
Currently the Data export and import features are all about saving your own data for restoring later or on another computer of your own. (And they work flawlessly, saving time and energy, thank you for these.) I was thinking these could be expanded to allow easier sharing of the style and looks of your homepage with others, and importing that of others to your own homepage. 
The important part of this is adding two new "Export" buttons after the button that is present now:

1. Exporting Bookmark and Group data — This would be for personal use, of course. Keeping a backup of your bookmark list is essential in my opinion. It would allow you to erase all data and start over fresh while keeping your bookmarks safe.
2. Exporting Style and Theme data — This would be the one that enables sharing the actual design of your homepage with others. It would work similarly to the current data Export button, but it would _exclude_ Bookmark data, Group data, **loaded wallpaper** data (the one in base64, more on that below), as well as wallpaper list maybe, to keep it short (wallpapers can be shared easily already).
Additionally it would be good if, when this data is imported, the Saved Theme list (in Settings > Theme) is **not** overwritten.

- Optionally, exporting style data to clipboard instead of a JSON file (separate buttons for each method) — This isn't essential, but would make sharing more convenient, otherwise you need to find a place to upload the JSON file then share that link. With this, you can export to clipboard, paste it someplace like in a Reddit post, and others can copy said text and paste it into a textbox in nightTab to import the data.
This would be the other reason to exclude the data I mentioned above. When only exporting the theme and layout data, it would be around 5,000 characters, which should be within most character limits.

And of course the original Import and Export data buttons would be left as they are now, as they would allow importing legacy idata and exporting current data for future versions.
So under Settings > Data, a user will see:
- Good old Import Data button (if it can automatically recognize which kind of exported data it is and if not, then 2 additional buttons for the 2 additional types of data export we've got). And then an Import Data Textbox if you want to implement that.
- Regular Export Data button, then an Export Bookmarks button, then an Export Style button. And then an Export Style To Clipboard button, if you want to implement that.

All this would tie in very well with a /r/nightTab subreddit. The subreddit could host both, issues by users who don't want to make a GitHub account, and posts with screenshots and style data meant for sharing. A link to the sub under Settings > Data and under Settings > nightTab would help.

Sorry for the long post, I don't know how it got so long. It's still just an idea about something that is not primary in nightTab's function.

**Comment by Q-out** [comment]
Oh a couple of typo reports:
- On exporting data, the file is named "nitghTab..."
- Settings > nightTab, it goes "submit an Issues" when it should just be "Issue"

**Comment by zombieFox** [comment]
> Currently the Data export and import features are all about saving your own data for restoring later or on another computer of your own. (And they work flawlessly, saving time and energy, thank you for these.)

Thanks! These are all good ideas. I've thought about sharing the Theme data too, I'll see what I can do.

> On exporting data, the file is named "nitghTab..."
> Settings > nightTab, it goes "submit an Issues" when it should just be "Issue"

Yikes, how did I miss those mistakes?? I've pushed fixes for them as they were simple to correct. Thanks!

**Comment by zombieFox** [comment]
A quick estimate: adding funtionality to the data export is complicated and would require a large amount of refactoring. I considered this a large task. 👍

**Comment by Q-out** [comment]
That's as expected. I wouldn't be surprised if you said it will wait till v10.0.0 or whatever, it does seem laborious if nothing else. I also wouldn't be surprised if you designed and implemented a neater version of this, since your UX decisions have all been on point so far. 🙌

**Comment by zombieFox** [comment]
Thanks for that 😄

**Comment by zombieFox** [comment]
Really like other ideas here so I'll continue to explore them and develop new features. A quick test shows [copying to the clipboard](Clipboard.writeText()
) should be possible.

**Comment by zombieFox** [comment]
Copying from the clipboard is now added too. This is included in the  [v7.x update](https://github.com/zombieFox/nightTab/releases/tag/v7.3.0).

**Comment by zombieFox** [comment]
I looked into more complex exports to only share the Theme data. It proved too difficult to validate on import. I'll close this here as I can't make more changes to the data layer to make this work.
