### ISSUE TITLE
[Bug] Match Header Area and Match Bookmarks Area buttons don't work

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#166]
They reset the width slider to 100 instead of matching to the other item.
![Screenshot (21)](https://user-images.githubusercontent.com/52709014/76726873-75e68700-6778-11ea-829f-c393d532b55f.png)

**Comment by zombieFox** [comment]
Thanks! I spotted this in a recent refactor. it's fixed on master and will be release in the next update.
