### ISSUE TITLE
Backup File Name Pattern

### ISSUE THREAD

**Issue by smaragdus** [zombieFox/nightTab#167]
The current name pattern of exported JSON file is:

`nitghTab backup - time - date`

example:

`nitghTab backup - 07 10 55 - 20.03.2020.json`

I think it would be better the name of the exported JSON file to have the following format:

`nitghTab backup - date - time`

because if the user keeps several backup files they are not sorted in chronological order, example:

- nitghTab backup - 04 44 00 - 13.03.2020.json
- nitghTab backup - 07 10 55 - 20.03.2020.json
- nitghTab backup - 22 27 26 - 11.03.2020.json
- nitghTab backup - 23 56 39 - 10.03.2020.json

so if date precedes time in file name the chronological order would be preserved. The date/time format I prefer is:

`nitghTab backup - 20-03-2020 - 07-10-55.json`

and if such format is used the saved backup files they will be naturally sorted in chronological order, example:

- nitghTab backup - 10-03-2020 - 23-56-39.json
- nitghTab backup - 11-03-2020 - 22-27-26.json
- nitghTab backup - 13-03-2020 - 04-44-00.json
- nitghTab backup - 20-03-2020 - 07-10-55.json

and thus the user would not need to manually rename exported backup files.

**Comment by zombieFox** [comment]
This seems like a good idea. Seems the time and date elements should be arrange from largest to smallest to be listed chronologically: YYYY-MM-DD - HH:MM:SS.

I'll see what I can do.

**Comment by zombieFox** [comment]
This change has now been made.

**Comment by smaragdus** [comment]
@zombieFox 

Thanks!
