### ISSUE TITLE
[Feature Request] Automatically follow system-wide dark mode

### ISSUE THREAD

**Issue by matfantinel** [zombieFox/nightTab#175]
I'd like a clean look that follows my OS' choice for light/dark mode. Currently I toggle between these modes on my OS depending on time of day, which also changes the color of my Firefox chrome. But right now I have to manually open nightTab settings -> Theme -> Saved -> Choose the right one.

Screenshots to illustrate what I'm trying to ask to be done automatically:

System in Light Mode:
![image](https://user-images.githubusercontent.com/24247035/79765042-80a6b580-82fc-11ea-9e9e-c513248f04dd.png)

System in Dark Mode:
![image](https://user-images.githubusercontent.com/24247035/79765140-a03dde00-82fc-11ea-814e-de916c34206f.png)

All of this has changed automatically except for nightTab.

**Comment by zombieFox** [comment]
I've been meaning to address this for some time. CSS [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) can achieve this. 

Got some changes ready to go, just need some testing.

**Comment by zombieFox** [comment]
On [master branch](https://github.com/zombieFox/nightTab/commit/79685343f5d0befae377d4e77f8e8e70b48aa227), will be out in the next release.

**Comment by zombieFox** [comment]
This feature is now on live 🤖
