### ISSUE TITLE
`ctrl alt a` not working to add bookmarks.

### ISSUE THREAD

**Issue by aasutossh** [zombieFox/nightTab#177]
Other shortcuts like `ctrl alt d` working for dark and light background.
`ctrl alt m` and `ctrl alt e` works.

Can't we specify custom shortcuts for different extension actions?

**Comment by aasutossh** [comment]
On that note, why don't we add *+* sign at the end of bookmark list, or after Bookmark List header name.

**Comment by Excigma** [comment]
What Browser? `Ctrl` + `Alt` + `A` works on Firefox 77.
This might also be on conflicting extensions(/addons???) using the same hotkey for things.

**Comment by zombieFox** [comment]
Confirming what @Excigma said. the keyboard shortcuts are working as intended in my tests.

@aasutossh can you confirm you do not have any other extensions using the `ctrl+alt+a` shortcut?

> Can't we specify custom shortcuts for different extension actions?

I'm not aware of any way to do this.

**Comment by aasutossh** [comment]
Sorry people.
I am using Firefox Developer Edition 76.0b8 (64-bit).

I don't get any feedback when I press `ctrl alt a`, so I can't confirm.

Custom extension shortcuts are on extension page (_Manage Extension Shortcuts_).
![image](https://user-images.githubusercontent.com/18498932/81274006-6fd1a000-906f-11ea-84b2-92ca967d4273.png)

**Comment by zombieFox** [comment]
nightTab does not use shortcuts at the browser level (register shortcuts via the manifest.json), only [within the webpage itself](https://github.com/zombieFox/nightTab/blob/master/src/js/keyboard.js). Do you see any other shortcuts on the Manage Extension Shortcuts page using `ctrl+alt+a`?

I downloaded and installed the latest Firefox Developer Edition (77.0b2 (64-bit), MacOS 10.15.4). All the keybaord shortcuts are working as expect in nightTab as far as I can see on a clean install.

Can you try updating to the latest Firefox Developer Edition?

If that does not resolve the issue there might be something specific to your set up which is

**Comment by aasutossh** [comment]
I am using Manjaro KDE (based on Arch), I should have latest version of FF but didn't. Let me update and confirm.

Also, there were none extensions using `ctrl alt a`.

**Comment by zombieFox** [comment]
> On that note, why don't we add + sign at the end of bookmark list, or after Bookmark List header name.

This is a design decsion, I want to keep the bookmark area clear of controls. The same reason the edit, mode, delete bookmark controls are hidden.

**Comment by aasutossh** [comment]
Just updated firefox to `77.0b3 (64-bit)`, still `ctrl alt a` doesn't work.

**Comment by zombieFox** [comment]
Nuts. Was hoping that would resolve the issue. I've been unable to recreate the issue as you desdcribe. 

If the other keyboard shortcuts are working in nightTab then it does indeed sound like something else is using `ctrl+alt+a` and taking precedence.

**Comment by Excigma** [comment]
Might be a bit of an ask, but try disabling all your extensions, or alternatively make a new Firefox profile with only nightTab installed.

It might also be an external program that is causing this?

**Comment by aasutossh** [comment]
I created a new profile, installed `nighttab`, still `ctrl alt a` not working.

> It might also be an external program that is causing this?

Then, I remembered that KDE has billions of shortcuts pre-defined, so I go in KDE settings > Shortcuts > Global shortcuts > Change any shortcut to `ctrl alt a` then it shows that the keybind is bind to a kWin setting called `Activate Window Demanding Attention`, so I disabled it. And now it's working. 

I should have done this before even posting the issue. Sorry for giving you trouble.

**Comment by aasutossh** [comment]
BTW, we gotta have shortcut for `Find Bookmarks or Search Google`. Ability to change the search engine. I didn't want to open a new issue.

**Comment by zombieFox** [comment]
> Ability to change the search engine

These controls can be found under the `settings menu > header > search > search engine`

> gotta have shortcut for Find Bookmarks or Search Google.

What do you mean shortcut? Right now the search bar can do the above.

**Comment by aasutossh** [comment]
> What do you mean shortcut? Right now the search bar can do the above.

Exactly. Why do you have the redundant search bar then?

**Comment by zombieFox** [comment]
Not sure I follow. The search bar in nightTab is optional and can be disabled from the settings menu. If shown, typing in it allows you to find bookmarks added to nightTab or search Google with the enter key.

**Comment by aasutossh** [comment]
I'll just disable the search bar then, more space. Thank you for great work.

**Comment by zombieFox** [comment]
No problem. 🙂
