### ISSUE TITLE
Color picker in Firefox, Windows 10

### ISSUE THREAD

**Issue by rithwikjc** [zombieFox/nightTab#178]
Hey zombieFox,

Great extension you've made. Really love how customizable it is, and how cool it looks.
I have been running into an issue with it on Firefox, Windows 10. I'm using the Firefox add-on.

In your demo videos I found on reddit, the color picker is a really cool, responsive one. However in Firefox I am getting this really old and hard to use windows one. More over it is not responsive, so I have to add a custom color and then press okay to see the change.
I am not sure if I'm the only one with this issue or its something to do with Firefox. Please let me know how to fix this.

![1](https://user-images.githubusercontent.com/25515417/81397562-3d927200-9145-11ea-8742-2992a22cb39c.PNG)

**Comment by zombieFox** [comment]
Hi, thanks! Glad you like the project.

> However in Firefox I am getting this really old and hard to use windows one.

Yes, in the demo videos a [native colour `input`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) brings up a colour window defined by the OS. I am using a Mac. So it looks like this:

<img width="602" alt="Screen Shot 2020-05-08 at 22 17 21" src="https://user-images.githubusercontent.com/7115017/81450197-d8a53f00-9179-11ea-90ab-c0a882235502.png">

The window you see is defined by Windows 10. Using a native colour input is a standar, accessible and future proof approach.

> More over it is not responsive, so I have to add a custom color and then press okay to see the change.

This is because of how Firefox handles the `change` event from the colour `input`. It fires the event when the "OK" is clicked. Chrome (the browser I used in the video) handles the event differently and fires the event every time a colour change occurs from the colour window.

Sorry, not much I can do about that.

**Comment by rithwikjc** [comment]
> The window you see is defined by Windows 10. Using a native colour input is a standard, accessible and future proof approach.

I agree that it's future proof, but it seems like a bad idea to just stick to native OS tools. It's okay for Mac I guess, but not usually for Linux and Windows users. Plus for a tool with so much appeal, in my opinion, it would be good for it be consistent cross platform. 
My experience choosing colors has been horrible thanks to windows native color picker, and the firefox `change` event handling. 

> Sorry, not much I can do about that.

One solution that maybe possible is to use a javascript color picker tool. This would provide consistent experience for all users, and go above and beyond in functionality than the native OS tools.
These are a couple of open source ones I particularly liked.
- https://github.com/Toinane/colorpicker
- https://github.com/Simonwep/pickr

Would it be possible to incorporate such a tool into this?
I think it for such a minimal design page like nightTab, where the most standing out feature is the colors, it is really important to have a good experience/tool to pick out colors.

**Comment by Excigma** [comment]
It is possible, but copying off zombieFox's response in #25 

> The nightTab colour picker uses the native HTML input colour element, so yes the UI picker is defined by the system or browser. This approach is useful to keep overheads and dependencies low, which is the way I prefer to design/develop. I'll look into external colour picker libraries, like spectrum, and make a call.

and also:
> Replace colour picker ❌(won't change)

Although that might be able to be reconsidered?

**Comment by rithwikjc** [comment]
> Alghough that might be able to be reconsidered?

I think it should be. I'll try to do it personally, when I get free time and am familiar with code.
It makes no sense for me to keep using it otherwise when the windows+firefox experience is so bad. 😕

**Comment by zombieFox** [comment]
> It makes no sense for me to keep using it otherwise when the windows+firefox experience is so bad. 😕

Thanks for the input. I'm sorry you feel this way. 

The balance between consistent experience, project file size, engineering effort plus support and keeping dependencies low is quite difficult. I feel there are enough tools in the app, in additinal to the native colour inputs, to help select colours:

![Kapture 2020-05-13 at 18 32 08](https://user-images.githubusercontent.com/7115017/81845487-86349b80-9548-11ea-9b6a-87664fb270bb.gif)

>> Replace colour picker ❌(won't change)

> Alghough that might be able to be reconsidered?

I'm happy for others to develop the idea of a 3rd party colour selector.

**Comment by rithwikjc** [comment]
> The balance between consistent experience, project file size, engineering effort plus support and keeping dependencies low is quite difficult. I feel there are enough tools in the app, in additinal to the native colour inputs, to help select colours:

Very true. 
I really like the section you've shown there. Complete control. 
Only issue was when I was using custom accents to the icons. The windows color picker just sucks. Hehe. But I have been pretty happy after the initial discomfort, since I am done with the setup.

Is it possible to have a window with the color setting you've shown here appear for the custom accents section of the bookmarks also?

**Comment by rithwikjc** [comment]
I think we can close this issue for now, since no active development is happening in this.
Thanks.

**Comment by zombieFox** [comment]
> Is it possible to have a window with the color setting you've shown here appear for the custom accents section of the bookmarks also?

Possibly, I'll look into it.

**Comment by zombieFox** [comment]
Pushed an [update to the master branch](https://github.com/zombieFox/nightTab/commit/33c2ad0496c714581c870687d79e5168beb349ac). It will be out in the next release.

![Kapture 2020-05-21 at 22 11 13](https://user-images.githubusercontent.com/7115017/82607114-1d849900-9bb0-11ea-8c84-26d9ce06351b.gif)

**Comment by rithwikjc** [comment]
Amazing. You rock @zombieFox. 🚀 🎆 🔥

**Comment by zombieFox** [comment]
This feature is now on live 🚀

**Comment by rithwikjc** [comment]
Will update. Thanks again.
