### ISSUE TITLE
what font is this

### ISSUE THREAD

**Issue by KraXen72** [zombieFox/nightTab#181]
![image](https://user-images.githubusercontent.com/21956756/82214773-9e286880-9916-11ea-9933-b5f6d2b62f29.png)

**Comment by zombieFox** [comment]
Hi, the font is [Major Mono Displa](https://fonts.google.com/specimen/Major+Mono+Display). 

It can be seen when selecting the Outrun Preset Theme in the Settings Menu.

**Comment by KraXen72** [comment]
Hi, thank you! i really love this new tab! Thank you for the font
![image](https://user-images.githubusercontent.com/21956756/82308898-b8b81b80-99c2-11ea-9332-eaefc2c9b2a2.png)

**Comment by zombieFox** [comment]
You're welcome. Thanks 😄
