### ISSUE TITLE
[Feature request] Option to set the extension as the browsers homepage (not just new tab)

### ISSUE THREAD

**Issue by davenicoll** [zombieFox/nightTab#183]
Every time I install the extension, I inspect the page load response and obtain the extension URL to index.html so that I can copy and paste it into the browsers Homepage field. It'd be great if there was an option to set this automatically, or at the very least show the extension URL somewhere within the extension so that I could get it from there more easily. Thanks!

**Comment by zombieFox** [comment]
Are you using Firefox? If so have you followed the instructions on the [readme about Firefox homepage settings](https://github.com/zombieFox/nightTab#setting-nighttab-as-your-firefox-homepage)?

**Comment by Excigma** [comment]
Netherless, it would be great to have a button to copy the url only shown for Firefox users.

I'm not sure if many users have Github or will come searching through here to find a fix, though this has been brought up a few times before:

https://github.com/zombieFox/nightTab/issues/119#issuecomment-564823896
(2019.. Wow times flies, doesn't it)

**Comment by davenicoll** [comment]
> Are you using Firefox? If so have you followed the instructions on the [readme about Firefox homepage settings](https://github.com/zombieFox/nightTab#setting-nighttab-as-your-firefox-homepage)?

I hadn't, no - but thanks for that. As @Excigma pointed out, I don't think most users will visit that. A link or button would be nice.

**Comment by zombieFox** [comment]
> Nevertheless, it would be great to have a button to copy the URL to be only shown for Firefox users.

It would, however I'm not sure how to show some controls just for Firefox and hide them for Chrome. I could add some instruction and a link to the Firefox section on the Readme file as that's the simplest solution I can think of.

> (2019.. Wow times flies, doesn't it)

Wow, it really does.

**Comment by Excigma** [comment]
I'm not sure if you can check if `navigator.userAgent.search("Firefox")` returns something higher than -1

**Comment by zombieFox** [comment]
> I'm not sure if you can check if navigator.userAgent.search("Firefox") returns something higher than -1

Tested, that does indeed work. I'll see what I can do with it.

**Comment by zombieFox** [comment]
This feature is now on live
