### ISSUE TITLE
Option to Disable Screen Dimming in Dark Mode

### ISSUE THREAD

**Issue by drgrib** [zombieFox/nightTab#184]
In Dark Mode, if I set the Colour settings for Lightness or Dark shade contrast below a certain point, the entire screen dims when I switch to the New tab then un-dims when I switch away from it. I already have my whole system calibrated to be dark, so this makes my entire screen change from a comfortable dark to difficult to see. Please add an option to disable this feature.

**Comment by zombieFox** [comment]
Hi, I'm not sure I understand the issue. Can you provide a video example or steps to reproduce the issue please?

I have not added any features to "dim" a tab when the browser tab loses focus.

**Comment by drgrib** [comment]
Thanks for asking about the repro. I recorded it and the effect wasn't on the recording. Turns out its some damned unmodifiable feature of my Samsung Q60 when the screen is below a certain level of brightness.

**Comment by drgrib** [comment]
For anyone else who may by small chance experiencing the exact same issue, the fix is to change the input type for your source to the TV from HDMI to PC:
https://youtu.be/44rKmlivRuI

Apparently they have some unpublished modifications to the HDMI source type.
