### ISSUE TITLE
Loading a new tab is a little slow.

### ISSUE THREAD

**Issue by RebeenPJ** [zombieFox/nightTab#185]
I don't know if the problem is on my end but loading a new tab takes a few seconds and doesn't give you that snappy feel. 
If it's on my end how can i fix it?

**Comment by Excigma** [comment]
It takes around 3 seconds for me

**Comment by zombieFox** [comment]
In my tests nightTab loads, depending on system load, in about 0.5 to 2 secs. It will vary for everyone as computer set ups differ.

**Comment by zombieFox** [comment]
The recent [v7.x update](https://github.com/zombieFox/nightTab/releases/tag/v7.3.0) is now out. The improvements added have reduced the load time and removed fade in.
