### ISSUE TITLE
Adding a little bookmarks button on header or allow creation of bookmark with "edge://favorites/" as URL

### ISSUE THREAD

**Issue by rezpower** [zombieFox/nightTab#187]
It would be great to have access to your browsers bookmarks also from the newpage. I tried to add a new bookmark and give "edge://favorites/" as url. But nighttab didn't accept that and needs http:// etc for the url. It would be nice to make it recognize these kind of links so we can set a bookmark.

Other possibility would be to add a new link in the header section for bookmarks.

**Comment by zombieFox** [comment]
> I tried to add a new bookmark and give "edge://favorites/" as url

Some URLs can not be set as bookmarks for security reasons. Please see [issue 152](https://github.com/zombieFox/nightTab/issues/152).

Adding support for accessing user browser bookmarks would require new user permissions and I've tried to avoid requesting user permissions. 

Wouldn't adding a control to access the browser bookmarks be the same as the menu or overflow menu on the browser chrome?

<img width="637" alt="Screen Shot 2020-06-07 at 18 37 46" src="https://user-images.githubusercontent.com/7115017/83975867-0b179880-a8ee-11ea-934d-a9970039714e.png">

Can you flesh out the use case please?

**Comment by rezpower** [comment]
Thanks a lot for your response. I made this suggestion because I was ignorant on the security restrictions you are facing. One thing that seduced me with this extension was the lack of permission demands and I think it's nice and important to keep it this way. Specially when there is no major need for it :)

**Comment by zombieFox** [comment]
> One thing that seduced me with this extension was the lack of permission

I like extensions like that too 🙂
