### ISSUE TITLE
[Feature request] Multiple search bars?

### ISSUE THREAD

**Issue by amitchaudhari9121** [zombieFox/nightTab#188]
Firstly, This is an awesome project. Absolutely loving it !
I often use multiple search engines. I am sure you guys do too.
the multiple search engine feature is not so nice in Firefox as on now.

**So, I propose either one of the following features...**
**1. Multiple search bars.**
**2. Having some sort of Multipurpose single Search bar, (like the Google's press TAB to search feature)**

I would love to tinker around with this project, but I don't know JS well enough...

I tried tinkering with HTML of the page, But this screenshot is obviously a single reload away from destruction... 
Thank you for this awesome project ! 
![Screenshot from 2020-06-08 00-34-54](https://user-images.githubusercontent.com/21289530/83977880-454e5d80-a921-11ea-93ea-5ef37b24540e.png)

**Comment by zombieFox** [comment]
> Firstly, This is an awesome project. Absolutely loving it !

Thanks! Glad you like the project.

> multiple search engine feature is not so nice in Firefox as on now

Sorry, I'm not familiar with this feature.

> 1. Multiple search bars.

I can see what the solution you are after in the screenshot, thanks for providing that. However I'm not clear on the use case. Can you add some details around the problem multiple search bars is solving please?

> 2. Having some sort of Multipurpose single Search bar, (like the Google's press TAB to search feature)

Sorry, again, I'm not familiar with the press Tab to search feature.

**Comment by Excigma** [comment]
>>> Having some sort of Multipurpose single Search bar, (like the Google's press TAB to search feature)

I'm not sure if they mean something like Firefox's url dropdown like this:
![image](https://user-images.githubusercontent.com/30280397/84205801-ff042480-ab01-11ea-9abc-9b5c053a11e7.png)

(The look looks kinda messed up as the UserChrome is for an older version of Firefox, but does OP mean the option to search with different search engines, bookmarks?)

**Comment by Q-out** [comment]
Have you looked into DuckDuckGo's [Bang](https://duckduckgo.com/bang) feature? You can set DuckDuckGo as your Search Engine in nightTab, then use bangs to get to search results with the site you want. 

For example, searching for `!reddit startpages` in nightTab will lead you straight to `https://www.reddit.com/search?q=startpages`
`!g wikipedia` will get you to `https://www.google.com/search?hl=en&q=wikipedia`

It takes about half an extra second as DDG redirects you.

**Comment by amitchaudhari9121** [comment]
>Sorry, again, I'm not familiar with the press Tab to search feature. Can you show me an example please? 

In chrome, There's a feature that will allow user to type the initial letters of a search engine (github in below case), then showing a suggestion to directly search the Website by pressing the tab button.

![Screenshot from 2020-06-11 22-14-09](https://user-images.githubusercontent.com/21289530/84415995-36252380-ac31-11ea-8f12-db27d60eb1b3.png)

It's kind of now a quality of life thing for me now, to skip the step of going to a website and waiting for it to load. This saves a lot of time (a few seconds) when browsing with poor network conditions.

>I'm not sure if they mean something like Firefox's url dropdown like this:

No, that's not what i meant, Sorry to disappoint, I should have included the above screenshot in the first post. 


> Have you looked into DuckDuckGo's [Bang](https://duckduckgo.com/bang) feature? You can set DuckDuckGo as your Search Engine in nightTab, then use bangs to get to search results with the site you want.
> 
> For example, searching for `!reddit startpages` in nightTab will lead you straight to https://www.reddit.com/search?q=startpages
> `!g wikipedia` will get you to https://www.google.com/search?hl=en&q=wikipedia
> 
> It takes about half an extra second as DDG redirects you.

This was really helpful, I did not know about this, and currently I am thinking of switching from default google to DDG, This would require me to learn these "bangs" but in any case they are a good alternative. 

I feel currently the search bar is lower utility that the Main (default) address bar in firefox & chrome. But it is very visually appealing, Hence, with feature addition can rival the main address bar in any browser.

**Comment by metruzanca** [comment]
I think the best solution to this problem would to take a hint from how both firefox and chrome allow you to define shortcuts for search engines so searching. How I've set it up in firefox currently is "y synthwave mix" searches youtube, "g nighttab" searches github etc 
![image](https://user-images.githubusercontent.com/32832892/87101767-39232c00-c250-11ea-9c6d-f2cd9a2b2232.png)
![image](https://user-images.githubusercontent.com/32832892/87101794-50621980-c250-11ea-852e-70dee7110b16.png)
