### ISSUE TITLE
NightTab 5.36.0 completely broken on FF and Chrome

### ISSUE THREAD

**Issue by valynor** [zombieFox/nightTab#190]
Just updated NightTab to 5.36.0 on FF 77.0.1 on Linux Mint, the new tab page is now just a black page with NOTHING on it. 

After deleting and re-installing NightTab it works ... until I reinstall my backup, after that it's just a black page again. 

Please fix urgently!

Edit: Same thing just happened on Chrome, all Bookmarks gone, just an empty black page. 
Worst update ever. :-(

**Comment by zombieFox** [comment]
I can see the update is working for Chrome and Firefox on Mac OS for my tests. 

Do you see any messages in the console?

**Comment by zombieFox** [comment]
While I investigate nightTab Firefox has been rolled back to v5.31.0, Chrome has been rolled back but published as v5.36.1 and is awaiting approval again.

You should be able to re-download the addone and restore previous backups.

**Comment by valynor** [comment]
nightTab version 5.36.0 Zonked Tarsier
nighttab.min.js:24 data version 5.36.0 no need to run update
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/js/nighttab.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
nighttab.min.js:42 Uncaught TypeError: Cannot read property 'trim' of null
    at Object.link (nighttab.min.js:42)
    at nighttab.min.js:42
    at Array.forEach (<anonymous>)
    at nighttab.min.js:42
    at Array.forEach (<anonymous>)
    at l (nighttab.min.js:42)
    at Object.O.all (nighttab.min.js:42)
    at n (nighttab.min.js:42)
    at Object.init (nighttab.min.js:42)
    at nighttab.min.js:51
link @ nighttab.min.js:42
(anonymous) @ nighttab.min.js:42
(anonymous) @ nighttab.min.js:42
l @ nighttab.min.js:42
O.all @ nighttab.min.js:42
n @ nighttab.min.js:42
init @ nighttab.min.js:42
(anonymous) @ nighttab.min.js:51
nighttab.min.js:41 Uncaught TypeError: Cannot read property 'focus' of null
    at nighttab.min.js:41
(anonymous) @ nighttab.min.js:41
load (async)
t.focus @ nighttab.min.js:41
init @ nighttab.min.js:41
(anonymous) @ nighttab.min.js:51

this is from the Chrome console

**Comment by valynor** [comment]
It's working again on FF but not on Chrome: 

nightTab version 5.36.1 Zonked Tarsier
nighttab.min.js:24 data version 5.36.1 no need to run update
nighttab.min.js:42 Uncaught TypeError: Cannot set property 'name' of undefined
    at Object.reset (nighttab.min.js:42)
    at nighttab.min.js:42
    at Array.forEach (<anonymous>)
    at n (nighttab.min.js:42)
    at Object.J.all (nighttab.min.js:42)
    at o (nighttab.min.js:42)
    at Object.init (nighttab.min.js:42)
    at nighttab.min.js:51
nighttab.min.js:41 Uncaught TypeError: Cannot read property 'focus' of null
    at nighttab.min.js:41
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/js/nighttab.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by valynor** [comment]
Deleted & reinstalled NightTab on Chrome, imported backup, **now** it works again.

**Comment by zombieFox** [comment]
Yes, seems a reinstall is needed on Chrome.

**Comment by zombieFox** [comment]
Still not sure why the update works on my Mac but not on Linux. Will continue to investigate.

**Comment by valynor** [comment]
Just put Linux Mint on a live USB stick. ;-)

**Comment by zombieFox** [comment]
I think I found the issue. I made a mistake somewhere and [tried to `.trim()` a `null` value](https://github.com/zombieFox/nightTab/blob/master/src/js/link.js#L988) which wasn't covered by my testing scenario. Who ever said addons/extensions were easy?

Working on a fix.

**Comment by sigzegv** [comment]
same issue on linux with chromium, last update nothing displays, and I haven't made any backup... so, am I f...d ? Is there an automatic backup or sync somewhere ?

**Comment by zombieFox** [comment]
@sigzegv Sorry for this issue. I think I have a temporary fix for someone in your situation. If you have uninstalled nightTab already this won't work. If you still have it installed this could help:

Make sure you have the latest version of nightTab installed (right now on Chrome it's v5.36.1). Open a new tab and [open the console](https://developers.google.com/web/tools/chrome-devtools#open) on the tab. This part sounds sketchy, but it's really not. Here goes, copy and paste this code into the console and hit enter to run it. Hopefully you can see it's not harmful. It loops over any nightTab data found in your browser local storage and fixes a few things:

```

// loop over bookmarks saved to nightTab's local storage data
bookmarks.get().forEach(function(arrayItem, index) {
  arrayItem.items.forEach(function(arrayItem, index) {
    // restore each bookmark accent colors
    arrayItem.accent.color = {};
    arrayItem.accent.color.r = arrayItem.accent.rgb.r;
    arrayItem.accent.color.g = arrayItem.accent.rgb.g;
    arrayItem.accent.color.b = arrayItem.accent.rgb.b;
    // restore each bookmark letter/icon
    arrayItem.display = arrayItem.visual.display;
    arrayItem.letter = arrayItem.visual.letter;
    arrayItem.icon = arrayItem.visual.icon;
  });
});

// restore letter/icon order
state.get.current().link.item.display.letcon = state.get.current().link.item.display.visual
if (state.get.current().link.item.display.order == "visualname") {
  state.get.current().link.item.display.order = "letconname";
} else if (state.get.current().link.item.display.order == "namevisual") {
  state.get.current().link.item.display.order = "nameletcon";
};

// restore link item color
state.get.current().link.item.color.by = "theme";

// save data
data.save();
```

Then reload the page. 
Hopefully that worked, if not sorry, you have to reinstall nightTab and start from scratch.

**Comment by sigzegv** [comment]
Thank you for providing a workaround :)

It seems to not work as I see "undefined" poping after running the code on my browser console. I'll reinstall the extension then.

**Comment by Excigma** [comment]
Not sure if related: ![image](https://user-images.githubusercontent.com/30280397/84611821-03ba4580-af13-11ea-8625-3f14e4bb944c.png)

**Comment by zombieFox** [comment]
> Not sure if related:

Looks like this is a different issues to what caused the previous bug in this thread. 

> Here's my localstorage, which appears to show all my bookmarks are gone

Very odd. Looks like this saved data object was updated to `v5.42.0` (latest on Firefox right now, released yesterday) but has some incorrect keys. I've checked the [update function for the missing keys](https://github.com/zombieFox/nightTab/blob/master/src/js/update.js#L1074) and it is working as expected. @Excigma, Do you remember when your Linux nightTab last updated?

**Comment by valynor** [comment]
5.41 and 5.42 work for me - but it feels like the NTP is opening a bit slower (~1 sec) than before.

**Comment by zombieFox** [comment]
> 5.41 and 5.42 work for me

Awesome!

The load times might vary depending on system load. I'm getting around 0.5 to 2 secs depending on video calls and other activity. Can you run some tests please? eg: how is the load time after a reboot etc

**Comment by tylermeuse** [comment]
Hello, thank you for your awesome work. 

I'm having the same issue with 5.42.0 as @Excigma, using macOS 10.15.4 / Firefox 77.0.1. Upon restarting Firefox to apply an update, I am met with the blank screen issue, and identical error. 

Please let me know if I should open a new issue. Trying to see if a fix can be applied before deleting localstorage and starting from scratch. 

![CleanShot 2020-06-15 at 12 10 19](https://user-images.githubusercontent.com/9298659/84681375-06606f00-af02-11ea-87fb-2acb124bda35.png)

Thank you.

**Comment by zombieFox** [comment]
@tylermeuse Very sorry about this issue. Can you run the following code in the console please: `copy(data.mod.get("nightTab"))`
That will copy the local storage nightTab data to the clipboard. Please open a new issue and include the contents of the clipboard and I will investigate.

**Comment by Excigma** [comment]
I don't think I have booted into Linux for days, so it is likely it was on 3.x or 4.x, though my settings never synced and I left it on the default nightTab configuration

**Comment by talentlessguy** [comment]
Same issue

![image](https://user-images.githubusercontent.com/35937217/84776624-37679f00-afe9-11ea-973b-2f81d94ce516.png)

**Comment by Maskedman99** [comment]
Issue started happening yesterday.
```
Firefox Version 77.0.1 (64-bit)
Ubuntu 20.04
nightTab version 5.42.0 Macabre Caterpillar
```
![Screenshot-20200616194126-1365x288](https://user-images.githubusercontent.com/31368194/84785731-73126100-b009-11ea-8f28-79cee946b246.png)

``copy(data.mod.get("nightTab"))``
```
{"nighttab":true,"version":"5.42.0","state":{"header":{"area":{"width":100,"justify":"center","align":"center"},"item":{"justify":"left"},"greeting":{"show":false,"type":"good","name":"","size":1,"newLine":false},"clock":{"hours":{"show":true,"display":"number"},"minutes":{"show":true,"display":"number"},"seconds":{"show":false,"display":"number"},"separator":{"show":true,"text":""},"meridiem":{"show":true},"hour24":{"show":true},"size":1,"newLine":false},"transitional":{"show":false,"type":"timeanddate","size":1,"newLine":false},"date":{"day":{"show":true,"display":"word","weekStart":"monday","length":"long"},"date":{"show":true,"display":"number","ordinal":true},"month":{"show":true,"display":"word","length":"long","ordinal":true},"year":{"show":false,"display":"number"},"separator":{"show":true,"text":""},"format":"datemonth","size":1,"newLine":false},"search":{"show":true,"style":"box","width":{"by":"auto","size":30},"focus":false,"engine":{"selected":"google","google":{"url":"https://www.google.com/search","name":"Google"},"duckduckgo":{"url":"https://duckduckgo.com/","name":"DuckDuckGo"},"youtube":{"url":"https://www.youtube.com/results?search_query=","name":"YouTube"},"giphy":{"url":"https://giphy.com/search/","name":"Giphy"},"bing":{"url":"https://www.bing.com/search?q=","name":"Bing"},"custom":{"url":"","name":"","queryName":""}},"text":{"justify":"center"},"size":1,"opacity":1,"newLine":false,"newTab":false},"editAdd":{"show":true,"size":1,"opacity":1,"newLine":false},"colorAccent":{"dot":{"show":true},"show":true,"size":1,"opacity":1,"newLine":false},"menu":{"show":true,"size":1,"opacity":1,"newLine":false},"order":["greeting","transitional","clock","date","search","editAdd","colorAccent","menu"],"border":{"top":0,"bottom":0},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"style":"scroll","opacity":0.95,"show":false,"newLine":false},"position":"inline","radius":false},"link":{"area":{"width":100,"direction":"ltr","justify":"center"},"item":{"color":{"hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"by":"theme"},"accent":{"hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"display":{"visual":{"show":true,"letter":{"size":3},"icon":{"size":3},"image":{"size":3},"shadow":{"size":0}},"name":{"show":true,"size":0.9},"gutter":2,"direction":"vertical","order":"letconname","alignment":"centercenter","rotate":0,"translate":{"x":0,"y":0},"letcon":{"show":true,"letter":{"size":3},"icon":{"size":3},"image":{"size":3},"shadow":{"size":0}}},"url":{"show":true},"line":{"show":true},"shadow":{"show":true},"hoverScale":{"show":true},"newTab":false,"size":1,"border":0,"opacity":1},"show":true,"add":false,"edit":false,"style":"block","orientation":"bottom"},"group":{"area":{"justify":"left"},"name":{"show":true,"size":1},"openAll":{"show":true,"size":1,"opacity":1},"border":0,"order":"headerbody","add":false,"edit":false},"layout":{"alignment":"centercenter","order":"headerlink","direction":"vertical","padding":4,"gutter":2,"size":1,"width":80,"scrollPastEnd":false,"scrollbars":"auto","title":""},"theme":{"accent":{"hsl":{"h":221,"s":100,"l":50},"rgb":{"r":0,"g":80,"b":255},"random":{"active":false,"style":"any"},"cycle":{"active":false,"speed":300,"step":10}},"color":{"hsl":{"h":222,"s":14,"l":56},"rgb":{"r":129,"g":138,"b":160},"contrast":{"light":4,"dark":4},"generated":{"negative":{"1":{"r":117,"g":127,"b":151},"2":{"r":107,"g":117,"b":142},"3":{"r":98,"g":107,"b":130},"4":{"r":89,"g":98,"b":118},"5":{"r":80,"g":88,"b":107},"6":{"r":72,"g":78,"b":95},"7":{"r":63,"g":69,"b":83},"8":{"r":54,"g":59,"b":72},"9":{"r":45,"g":50,"b":60},"10":{"r":37,"g":40,"b":48}},"positive":{"1":{"r":141,"g":149,"b":169},"2":{"r":152,"g":160,"b":178},"3":{"r":164,"g":170,"b":186},"4":{"r":176,"g":181,"b":195},"5":{"r":187,"g":192,"b":204},"6":{"r":199,"g":203,"b":213},"7":{"r":210,"g":214,"b":221},"8":{"r":222,"g":224,"b":230},"9":{"r":234,"g":235,"b":239},"10":{"r":245,"g":246,"b":248}}}},"font":{"display":{"name":"","weight":400,"style":"normal"},"ui":{"name":"","weight":400,"style":"normal"}},"style":"dark","radius":0.25,"shadow":0.75,"shade":{"opacity":0.4},"custom":{"all":[],"edit":false}},"background":{"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":{"show":false,"from":"file","file":{"name":"","data":""},"url":"","blur":0,"scale":1,"opacity":1,"grayscale":0,"accent":0,"vignette":{"opacity":0,"start":90,"end":70}}},"edit":false,"pagelock":false,"shade":false,"edge":false,"search":false,"menu":false,"modal":false,"dropdown":false,"autoSuggest":false},"bookmarks":[{"name":{"text":"Cool stuff","show":true},"openAll":{"show":true},"items":[{"visual":{"display":"icon","letter":"AS","image":"","icon":{"name":"dice-d20","prefix":"fas","label":"Dice D20"}},"name":"awesomeSheet","url":"https://zombiefox.github.io/awesomeSheet/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453104010,"display":"icon","letter":"AS","icon":{"name":"dice-d20","prefix":"fas","label":"Dice D20"}},{"visual":{"display":"letter","letter":"AZ","image":"","icon":{"name":"amazon","prefix":"fab","label":"Amazon"}},"name":"Amazon","url":"https://www.amazon.co.uk/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453107633,"display":"letter","letter":"AZ","icon":{"name":"amazon","prefix":"fab","label":"Amazon"}},{"visual":{"display":"letter","letter":"GM","image":"","icon":{"name":"envelope","prefix":"fas","label":"Envelope"}},"name":"Gmail","url":"https://mail.google.com/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453110265,"display":"letter","letter":"GM","icon":{"name":"envelope","prefix":"fas","label":"Envelope"}},{"visual":{"display":"icon","letter":"R","image":"","icon":{"name":"reddit-alien","prefix":"fab","label":"reddit Alien"}},"name":"Reddit","url":"https://www.reddit.com/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453111491,"display":"icon","letter":"R","icon":{"name":"reddit-alien","prefix":"fab","label":"reddit Alien"}},{"visual":{"display":"icon","letter":"N","image":"","icon":{"name":"film","prefix":"fas","label":"Film"}},"name":"Netflix","url":"https://www.netflix.com/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453104460,"display":"icon","letter":"N","icon":{"name":"film","prefix":"fas","label":"Film"}},{"visual":{"display":"letter","letter":"DR","image":"","icon":{"name":"","prefix":"","label":""}},"name":"Drive","url":"https://drive.google.com/drive/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453111953,"display":"letter","letter":"DR","icon":{"name":"","prefix":"","label":""}}]},{"name":{"text":"Dev sites","show":true},"openAll":{"show":true},"items":[{"visual":{"display":"icon","letter":"DEV","image":"","icon":{"name":"code","prefix":"fas","label":"Code"}},"name":"Devdocs","url":"http://devdocs.io/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453101749,"display":"icon","letter":"DEV","icon":{"name":"code","prefix":"fas","label":"Code"}},{"visual":{"display":"icon","letter":"GIT","image":"","icon":{"name":"github","prefix":"fab","label":"GitHub"}},"name":"Github","url":"https://github.com/","accent":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0},"color":{"r":0,"g":0,"b":0}},"color":{"by":"theme","hsl":{"h":0,"s":0,"l":0},"rgb":{"r":0,"g":0,"b":0}},"image":"","searchMatch":false,"timeStamp":1546453108926,"display":"icon","letter":"GIT","icon":{"name":"github","prefix":"fab","label":"GitHub"}}]}]}
```

**Comment by zombieFox** [comment]
@Maskedman99 Thanks for that information. It's helping me greatly. Can you update to the latest nightTab (v5.42.1) on Firefox and see if that issue resolves please? I believe that bug was fixed.

**Comment by zombieFox** [comment]
@talentlessguy thanks for that info. Can you run the following code in the console please: 

`copy(data.mod.get("nightTab"))`

That will copy the local storage nightTab data to the clipboard. Please open a new issue and include the contents of the clipboard and I will investigate as this looks like a different bug to what is in this thread.

**Comment by Maskedman99** [comment]
@zombieFox Thanks it's working now. I lost my previous settings, going to import it from backup. Thanks for solving the issue in such short time.

**Comment by zombieFox** [comment]
@Maskedman99

> I lost my previous settings

Sorry about losing the data. That seems to be an unidentified issue related to a recent roll back. I don't know if that could be fixed but glad that you had a backup.

**Comment by matfantinel** [comment]
I am having blank screen on 5.42.1 too. Any way to backup at this state? I had recently changed my setup and did not have a backup yet :grimacing: 

Firefox 77, PopOS 20.04

**Comment by zombieFox** [comment]
> Any way to backup at this state? 

@matfantinel I'm not sure. Can you follow the steps in one of the earlier posts about copying stored data from the console and paste the information into a new ticket please. I'll investigate.

**Comment by zombieFox** [comment]
Closing this ticket, if people have further issues please open a new ticket with save data so I can investigate.
