### ISSUE TITLE
Can't load URL with -

### ISSUE THREAD

**Issue by scottjl** [zombieFox/nightTab#20]
Trying to go to a URL with a - in the string, this case `https://server.somewhere.com/some-service`

When clicking the URL the server name is replaced with a string `http://bc8cb7701c5b/some-service` and not the actual server name resulting in an error.

Happens in Chrome and Firefox.

**Comment by zombieFox** [comment]
That's interesting, I've tried to recreate the issue but I can't. When add a URL with a `-` it works just fine.

Can you provide more details or provide a URL you have seen changed when entered?

**Comment by scottjl** [comment]
Well the funny thing is, the URL looks fine when you point at it in the start page. It's when I click on it and it tries to actually go to the URL that I end up with the messed-up one in the URL field of the browser. The URL does actually work for me as a bookmark, it is legit.

**Comment by zombieFox** [comment]
I see. I've got the email -- I'll investigate some more. Thanks. Watch this space.

**Comment by zombieFox** [comment]
I've been investigating and I can't replicate the issue described. I've tried a few URLs with a `-` in them and they work as expected. I've even reviewed the code that [takes the value](https://github.com/zombieFox/nightTab/blob/master/js/link.js#L92) from the Add form and saves it to the local storage. It does not modify it.

To help, can you check and review the URLs as they are saved on your browser when viewing nightTab by following these steps:

1. Open nightTab
2. Add the URL to the app using the "Add" control
3. Right click on the page and select "Inspect", this will open the dev tools on Chrome or Firefox
4. Find and select the Console tab in the dev tools
5 Copy and paste this into the Console: `bookmarks.get().forEach(function(item){console.log(item.url)})`
6 Hit enter

This will display all the URLs as nightTab has recorded them. Please check the URLs are correct. If not please report back.

If they are correct then something else is redirecting or changing the URLs.

**Comment by scottjl** [comment]
Just checked, the URLs are stored correctly.

I don't run many extensions and the ones I do shouldn't be doing anything,
but I'll have to try disabling them one-by-one and see if I can find if it
is one of them. Will let you know. Thanks.

--Scott

**Comment by scottjl** [comment]
Spent the weekend doing some extensive testing. Even with no Chrome extensions I still get the undesired behavior. If I take the - out of the URL it works fine, every time. I've created some new URLs with - in them. They all break. Same behavior in Firefox. Same behavior connecting from within my network or from external (using Traefik as a reverse proxy with https). I don't know what else to say other than a - in the URL simply doesn't work for me and nightTab. I can't figure out why this is happening, but it sure is frustrating. I took the - out of my URL as the solution, only thing I could do.

**Comment by zombieFox** [comment]
I have continued trying to recreate the issue but have again been unsuccessful. Along with the sample URL you emailed me, I've been using other test URLs: `https://www.penny-arcade.com/` and `https://www.hbo.com/game-of-thrones` (Both examples of `-`'s in the domain name and path). The all work fine for me and nothing is modifying the URL when stored by nightTab. 

I'm sorry this is not the case for you. However I don't know how to proceed with this issue.

**Comment by scottjl** [comment]
Thanks for your help and investigating the issue. I wish I could figure out more myself. Fortunately all the other URLs work just fine, I just use a bookmark for the troublesome one.

**Comment by zombieFox** [comment]
Unable to replicate or resolve. Closing the issue.
