### ISSUE TITLE
Weather report

### ISSUE THREAD

**Issue by Kreuger** [zombieFox/nightTab#203]
Hey is there a way to add in the ability to display the weather, and maybe have an option to set the source of the weather? I think this would be great to have. Thanks for the hard work!

**Comment by zombieFox** [comment]
Hi

> Thanks for the hard work!

Cheers, glad you like the project.

> add in the ability to display the weather, and maybe have an option to set the source of the weather?

I'm sorry, right now nightTab does not have a weather feature. I decided early on that the project would only focus on bookmarks, so this would be out of scope of the project. 

This is mainly to avoid dealing with user location data and not having to worry about potential GDPR (or the like) issues. As a rule nightTab deals with no user data right now. (There are other reasons but this is the main one.)

Happy for someone to fork and develop such a feature.

**Comment by Kreuger** [comment]
Im quite alright with your reasoning behind not including such a feature. It is not necessary for me. Thank you!
