### ISSUE TITLE
Re-Order Groups Based Day

### ISSUE THREAD

**Issue by ericjoshua** [zombieFox/nightTab#214]
I don't know if it would be possible and if it isn't feel free to close this right away but I was wondering if you could implement a way to auto sort groups based on the day of the week? 

Essentially I want a group or two at the top of the new tab page M-F (for work) but then Saturday and Sunday would have other stuff at the top.

**Comment by metruzanca** [comment]
I've just started working on a newer build of nighttab along with @zombieFox and this very feature came up during our discussion on saturday about what features we're looking to implement. (I'd also like this feature.)

Sadly, the timeline regarding adding such a feature is a bit off for the moment as we're actually rebuilding the app to use React and a more modern and robust build process. Once we're done with the re-write, we'll be able to add new features more quickly, not to mention the fact that there's now two of us working on it ;)

Still in very early development (basically just yesterday so far) but if you want to keep tabs on our progress you can go here => https://github.com/metruzanca/NightTab.

**Comment by ericjoshua** [comment]
Awesome I really appreciate the update, I'll go ahead and close this out since it seems to be on your roadmap anyway. Thanks for the awesome development guys!
