### ISSUE TITLE
Ability to open local chrome:// URLs

### ISSUE THREAD

**Issue by jcayzac** [zombieFox/nightTab#223]
**Is your feature request related to a problem? Please describe.**

Using `chrome://flags`, `chrome://apps`, `chrome://history` or `chrome://settings` as a bookmark URL doesn't work. Clicking on the bookmark triggers an error.

**Describe the solution you'd like**

That using `chrome://flags`, `chrome://apps`, `chrome://history` or `chrome://settings` as a bookmark URL works, and clicking on the bookmark opens the relevant page.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by zombieFox** [comment]
Hi,

Thanks for the feedback. This issues has been discussed in #152. In short those are protected URLs and can not be accessed by an extension.

**Comment by jcayzac** [comment]
Thanks @zombieFox , I did a search in old issues but it seems something went wrong 😆
