### ISSUE TITLE
List of presets

### ISSUE THREAD

**Issue by Sparklytical** [zombieFox/nightTab#226]
# List of some presets from Reddit and GitHub

### Share your own presets on [/r/nightTab](https://www.reddit.com/r/nighttab/)

**How to [import these presets.](https://github.com/zombieFox/nightTab/wiki/Data-backup-and-restore#restore-data)**

| Preset 003 |
|-|
| [![Preset 003](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-003.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-003.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-003.json) |

| Preset 004 |
|-|
| [![Preset 004](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-004.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-004.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-004.json) |

| Preset 005 |
|-|
| [![Preset 005](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-005.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-005.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-005.json) |

| Preset 006 |
|-|
| [![Preset 006](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-006.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-006.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-006.json) |

| Preset 007 |
|-|
| [![Preset 007](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-007.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-007.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-007.json) |

| Preset 008 |
|-|
| [![Preset 008](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-008.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-008.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-008.json) |

| Preset 009 |
|-|
| [![Preset 009](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-009.gif)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-009.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-009.json) |

| Preset 010 |
|-|
| [![Preset 010](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-010.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-010.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-010.json) |

| Preset 011 |
|-|
| [![Preset 011](https://raw.githubusercontent.com/zombieFox/nightTab/master/asset/screenshot/screenshot-011.png)](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-011.json)| |
| [Download preset](https://github.com/zombieFox/nightTab/blob/master/asset/screenshot/screenshot-011.json) |

| Minimal Coffee |
|-|
| [![Minimal Coffee](https://i.redd.it/ymjac7y4pyk51.png)](https://cdn.discordapp.com/attachments/704792091955429426/751129823610667148/zomfox_clean.json)| |
| [Download preset](https://cdn.discordapp.com/attachments/704792091955429426/751129823610667148/zomfox_clean.json) |
| [Reddit post](https://www.reddit.com/r/startpages/comments/ilx53r/minimal_coffee_nighttab/) |

| Persona 5 |
|-|
| [![Persona 5](https://preview.redd.it/hlpg8vel17h71.png?width=1920&format=png&auto=webp&s=122573f705ef80c5a3771ddd4f7c157bef52102a)](https://cdn.discordapp.com/attachments/401099306167435269/875851587971592222/Persona_5_Nighttab_final.json)| |
| [Download preset](https://cdn.discordapp.com/attachments/401099306167435269/875851587971592222/Persona_5_Nighttab_final.json) |
| [Reddit post](https://www.reddit.com/r/nighttab/comments/p3uo9m/first_post_persona_5_inspired_setup/) |

| Random clouds |
|-|
| [![Random clouds](https://preview.redd.it/iqpjg5umxxk71.png?width=960&crop=smart&auto=webp&s=093b0ce3ebbe503ec26c4f5f88502bc987f808b9)](https://gist.githubusercontent.com/metruzanca/07ae0b08d1703bc1b8818c45a35107cb/raw/eb2573eb2dd59843716450a6d0d83367092d7de3/nighttab%2520brkfst.json)| |
| [Download preset](https://gist.githubusercontent.com/metruzanca/07ae0b08d1703bc1b8818c45a35107cb/raw/eb2573eb2dd59843716450a6d0d83367092d7de3/nighttab%2520brkfst.json) |
| [Reddit post](https://www.reddit.com/r/nighttab/comments/pg0rsn/new_work_dashboard_image_is_random_clouds_sky/) |

| Purple Cityscape |
|-|
| [![Purple Cityscape](https://preview.redd.it/wwnm5az8gyk71.png?width=960&crop=smart&auto=webp&s=90870641e5a28252c08f28dd76cadbf92dcbcfa6)](https://gist.githubusercontent.com/zombieFox/200389b6ca7dc5aa35b1109fb2949287/raw/311be126f98a4fe6a1628c406bbedfdf04793831/gistfile1.txt)| |
| [Download preset](https://gist.githubusercontent.com/zombieFox/200389b6ca7dc5aa35b1109fb2949287/raw/311be126f98a4fe6a1628c406bbedfdf04793831/gistfile1.txt) |
| [Reddit post](https://www.reddit.com/r/nighttab/comments/pg325t/purple_cityscape_my_current_set_up/) |

**Comment by zombieFox** [comment]
Updated links 🚀
