### ISSUE TITLE
Remove or reduce blur on wallpaper when scrolling past end

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#228]
The entire point of scrolling past end (Layout > Scroll past end) seems to be to admire the wallpaper, but you might want a blur on the wallpaper so your bookmarks look clearer, so when you scroll past end, there's nothing to look at.

An option that reduces or removes (either gradually or almost instantly) blur scale on the wallpaper as you reach the end of the page would pair very well with the scroll past end option. It might look something like this:
![Screenshot (24)](https://user-images.githubusercontent.com/52709014/103126122-4d020380-46b3-11eb-9904-a888fea5e35c.png)
![Screenshot (25)](https://user-images.githubusercontent.com/52709014/103126128-52f7e480-46b3-11eb-8694-e3309fcca697.png)
![Screenshot (26)](https://user-images.githubusercontent.com/52709014/103126133-568b6b80-46b3-11eb-9af0-b0b24a85e483.png)

It's really not that important, just thought it would look nice.

**Comment by zombieFox** [comment]
I'll look into this and see what can be done once work picks up on this project again. Seems like a good enhancement.

**Comment by zombieFox** [comment]
Took a while but I [found a way to make this possible](https://github.com/zombieFox/nightTab/blob/44fdf247cc4d3d63a88167b65d11dbe595264aae/src/component/layout/index.js#L191). This was tough:

https://user-images.githubusercontent.com/7115017/144768455-ce299dca-55a7-4bd2-8c8e-5a4708136a1b.mp4

**Comment by zombieFox** [comment]
Merged, will be out in the next release.
