### ISSUE TITLE
a way how to make the page load instantly

### ISSUE THREAD

**Issue by KraXen72** [zombieFox/nightTab#230]
i love night tab and i have one suggestion.
you know how it takes like 3 - 5 seconds to load the new tab if you have a really complex setup, with a lot of images, effects, wide and tall tiles etc.

what ift here was a build button.
it would just compile all the js into plain html with a hrefs and css
that would be quick to load and there would be an edit button which would take you to the normal version you could edit and if you happy just build it and have a really nice nighttab and its fast af
what do you think?

**Comment by KraXen72** [comment]
i know quite a lot of js and could probably (?) implement this myself but i am not going to bother unless its something you like and would merge

**Comment by metruzanca** [comment]
@KraXen72 That's implementable only if nighttab is self-hosted. You can't do this with extensions.

**Comment by KraXen72** [comment]
sad but would be really cool

**Comment by zombieFox** [comment]
As mentioned above this extension is already "built". The build process has already happened and the result is already published. To develop what you are describing would be a self hosted startpage which you can control by editing basic HTML, CSS and JS.
