### ISSUE TITLE
help: I can't put an animated background

### ISSUE THREAD

**Issue by michoko999** [zombieFox/nightTab#236]
Hello,
When I put the MP4 video link as background nothing happens
I would like to know which link works to put an animated background

**Comment by zombieFox** [comment]
Hi, sorry you are having a problem with nightTab. Can you provide a few more details please:

- What is the URL of the MP4 you are using?
- Please describe the steps you took to add a video background
- Which browser are you using? Please include the version number
- Which OS are you using?

**Comment by michoko999** [comment]
URL: https://www.youtube.com/watch?v=Gv2ynaXDuOQ
Parameter> Background> Visual> Video> URL
Chrome: Version 90.0.4430.93 (Official build) (64 bits)
Windows

**Comment by zombieFox** [comment]
Thanks for those extra details. I'm afraid youtube videos can't be used as backgrounds. That URL is the address to a youtube page. nightTab only supports direct links to MP4 files, eg: https://pixabay.com/videos/download/video-40581_large.mp4

**Comment by Marcelx8** [comment]
Hi, I found a way that you can make this work, but it's a 'hack-around' and requires VLC. I tested it myself.

I found a forum discussion to get the direct URL from a Youtube video. Here are the steps to follow:

1. Find a video on YouTube and copy the URL from the address bar.
2. In VLC, head to Media > Open Network Stream.
3. Paste the YouTube link in the box and click Play.
4. Under Tools, click Codec Information.
5. In the box that says Location, right-click the block of text and click Select All. Copy this text to your clipboard.
6. Go back to your browser and paste the link in the address bar. This will open the source file directly on YouTube's servers. **(This is the URL that you can paste into the nightTab video background input.)**
7. Right-click the video as it plays and select Save Video As.

Link to the actual discussion:
https://webapps.stackexchange.com/questions/47465/how-to-obtain-the-direct-link-to-a-youtube-video-file

**Comment by zombieFox** [comment]
Great find @Marcelx8! I think you just cracked it.

I think I hit a problem with my [helper function](https://github.com/zombieFox/nightTab/blob/cbed3d11a9286b05bd0897f791978df42b09327a/src/js/helper.js#L268) not working well with the URL when using the method you found. But I might be able to change the way the [`src` attribute](https://github.com/zombieFox/nightTab/blob/cbed3d11a9286b05bd0897f791978df42b09327a/src/js/background.js#L177) is added to the background element to make this work.

I'll see what I can do.

**Comment by Dawid8plc** [comment]
Alternatively, a local file server can be set up that could contain all the backgrounds, images, icons, and other stuff you would like to use, I was able to download the provided video, and put it on an IIS server. Of course, this method requires a lot of setup and it's not exactly simple, just putting it out there, though.

**Comment by Marcelx8** [comment]
@zombieFox I'm glad this helped. :)

**Comment by zombieFox** [comment]
This has been asked before in other posts, (I'm too lazy to dig them out right now). But the tl;dr is because nightTab does not store user data (to a database or an account) it stores bookmarks and theme settings in the [browsers local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). So the space is very limited. 

The background image feature which I added allows a user to search for a local file. That is as much as an extension can do, open local files but not access whole directories. (And in retrospect allowing users to access local images for the background has caused issues with hitting the max space in local storage [along with a few [other issues](https://github.com/zombieFox/nightTab/issues/69)]. Hosting is really the safer option.)

@Dawid8plc suggestion is what I have been recommending in other posts, users who want more videos or images have to host them somewhere. Then link to individual files with URLs. But this requires end users to do some set up on something like a private GitHub repo, or Imgur.

**Comment by Marcelx8** [comment]
@zombieFox 
Interesting, and thank you for your time to explain.

**Comment by RohitHazra** [comment]
I can't tell about YouTube video but I used videos from pixabay.com
Follow these steps to change background video:
1. Open any pixabay videos. Ex: [](https://pixabay.com/videos/tunnel-space-abstract-science-line-23411/)
2. Press **F12** or **Ctrl+Shift+I** to open Inspect menu.
3. Make sure you are in the **Elements** tab and search for this line _<script type="application/ld+json">_. Double click to expand it.
4. There will be a line like this : _"contentUrl": "//player.vimeo.com/external/335603656.sd.mp4?s=56cd3cc3df4d570ada85034d13900b7869243d38&profile_id=164",_
5. Just Copy the link from that line [](player.vimeo.com/external/335603656.sd.mp4?s=56cd3cc3df4d570ada85034d13900b7869243d38&profile_id=164) and paste it in your broswer.
6. You will get a new address. Just copy that and paste it in the NightTab video url.

**Comment by zombieFox** [comment]
@RohitHazra whoa, interesting method! 
No comment on whether hotlininking is ok. 😄

**Comment by Scr0ll3r** [comment]
I found another way to get the animated video background from youtube, a file from your pc or any streamable video.
(requires Discord = https://discord.com/ ):

1. Use a website to download the youtube video ( I used https://www.y2mate.com/en297 )
2. Upload the video to discord. ( If your file is bigger than 8mb try to find a server boosted discord server, i just used Crispy 
    Concord's server: https://discord.gg/fcEAmDxN77 ) (You can upload it to the media tab)
4. Right Click the uploaded video, and click "Copy link".
5. Paste the link in the NightTab settings/Theme/Background/URL
6. You can even delete the video you uploaded to Discord, if you want to. (I haven't had the background for long term yet but I 
    think it'll work.)
    
Message to @zombieFox , maybe try making a discord server where people can upload their files, so they can use the links. (U can have people boost the server for bigger uploads)

**Comment by NotDevName2** [comment]
Background Image not working 
https://pixabay.com/photos/night-stars-light-download-cloud-7162435/

**Comment by metruzanca** [comment]
@NotDevName2 If thats the link you're using, thats not a link to an image. Thats a link to a webpage that has an image. You need a direct link to the image, in this case https://cdn.pixabay.com/photo/2022/04/29/04/01/pasta-7162435_960_720.jpg is the image used on that web page.

To get image urls, its quite simple. Right click on the image and click "copy image link" as show in image below:

![image](https://user-images.githubusercontent.com/32832892/165997584-afe76864-1ce4-4dea-b9f8-e3cb2f211c7e.png)

---
Certain sites, like instagram prevent you from copying images like this so you'll need to dig into the devtools to find image urls.
