### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by SpikeRaxstone** [zombieFox/nightTab#24]
Hey @zombieFox!

**I love this project**, it's by far the best custom start page out there. I think the dark mode is really great but a **light mode** would be nice too. Hopefully, this wouldn't be too difficult to add, just swapping out some of those `--gray`'s for `--white` and maybe creating new variables in the [base.css](https://github.com/zombieFox/nightTab/blob/master/css/base.css) file.

Good luck and keep up the **amazing work**! 👍

**Comment by zombieFox** [comment]
Hi, thank you! I like the idea. I will add a ticket to the Feature Development board.
