### ISSUE TITLE
Theme is resetting to default 

### ISSUE THREAD

**Issue by dakshpahlajani** [zombieFox/nightTab#241]
**Describe the bug**
The theme that i've created, custom background / images for bookmarks etc. it keeps resetting back to the default way it was. i've tried using other themes i've found online, same issue. after a few days, i think chrome crashes and it resets.

**To Reproduce**
Simply import a saved theme, or make a new one. 

**Expected behavior**
The theme should never reset, but it does. after 2 -4 days. 

**Screenshots**
no screenshots 

**Desktop (please complete the following information):**
 - OS: MAC OS 10.15.7 (19H15)
 - Browser Chrome 
 - Version Version 90.0.4430.93 (Official Build) (x86_64)

**Additional context**
i think sometimes when a tab crashes on chrome. it then resets, i havent paid attention cuz i usually have all my tabs open almost 24/7. but i think ive noticed it then.

**Comment by zombieFox** [comment]
Hi, sorry you are having this issue. Thanks for providing all those details. First thought, this could be related to issue #205, where another extension was clearing browser cache on restart. 

Do you have any other extensions installed which clear browser cache or cookies on restart?

Can you share the exported JSON so I can inspect the theme data?

**Comment by dakshpahlajani** [comment]
Ok I understand, in case I do, I should have a backup of my theme.

Perfect thanks for clearing this up 👌🏻

Also really love this extension! I was able to make this theme!

My theme <https://images-ext-2.discordapp.net/external/y5zQD2j6CDolZZqmPk94pXjZ7LHI3k_WXdO0-LHH888/https/i.imgur.com/cm7Rvdg.mp4> that I’ve made, had a recording of it

Regards
Daksh


Daksh
________________________________
