### ISSUE TITLE
Change search engine

### ISSUE THREAD

**Issue by deveagleistaken** [zombieFox/nightTab#245]
**Is your feature request related to a problem? Please describe.**
I'm always annoyed when I search something and it searches on Google instead of DuckDuckGo.

**Describe the solution you'd like**
Add a feature that allows the change of search engine, (eg, DuckDuckGo, Bing, Yahoo, Startpage)

**Comment by zombieFox** [comment]
Hi, have you tried the changing the search engine via the settings menu? 

Controls to change the search engine can be found under the `Settings menu` > `Header` > `Search` > `Search engine`.

Hopefully this works for you.

**Comment by deveagleistaken** [comment]
Yeah. Thanks!
