### ISSUE TITLE
not stating nighttab

### ISSUE THREAD

**Issue by dnldp55** [zombieFox/nightTab#246]
**Describe the bug**
![image](https://user-images.githubusercontent.com/83626074/118246110-890bf880-b4dc-11eb-919e-d6feea99521b.png)
not stating nighttab
npm run dev 
stating initialBackground...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] centos 8

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zombieFox** [comment]
Hi, are you seeing any errors in the console after running `npm run dev`?

After `Starting 'initialBackground'...` appears, do you see a dev copy of the project  in the `/dev/` folder. You should be able to open `/dev/index.html` in a browser to see the project.

**Comment by dnldp55** [comment]
![Clone of CentOS 8 (본체)-2021-05-14-18-12-00](https://user-images.githubusercontent.com/83626074/118248996-e35a8880-b4df-11eb-8438-aaaf2a983426.png)
I enter npm run dev
Starting 'initialBackground'... ( not start to next step )

and i open the /dev/index.html

**Comment by zombieFox** [comment]
That is very strange. You'll need to find out how to view local files in your browser. For me it's opening `index.html`, double clicking it works. The address should be something like this: `file:///Volumes/Drive/Projects/nightTab/dev/index.html`.

**Comment by dnldp55** [comment]
How about open the localhost?
I wanna `http://localhost`

**Comment by zombieFox** [comment]
Sorry, this project is a bit on the old side, it wasn't built with a local server. I might rework the tooling however [all the HTML partials](https://github.com/zombieFox/nightTab/tree/master/src/html) would need to be refactored to work with something like Webpack (which is what I build my projects in these days).

I don't have time to refactor the project on that scale right now.
