### ISSUE TITLE
Pls add more icons

### ISSUE THREAD

**Issue by samrth012** [zombieFox/nightTab#249]
**Is your feature request related to a problem? Please describe.**
Yes I have many websites to bookmark and I don't find icons for them.
 
**Describe the solution you'd like**
Adding of more icons at least those which are famous like gmail or classroom or like Netflix ( the envelope icons looks sus on gmail).

**Describe alternatives you've considered**
I have tried putting the logos matching my color and ascent as images but the thing is they don't get highlighted when u hover over them.

**Additional context**
See this happens and looks really weird and sus while using it. I can help you out with icons and developments please feel free to tag me up.

https://user-images.githubusercontent.com/63335952/118781594-dd332600-b8aa-11eb-8e69-d46b81d4fa2e.mov

**Comment by zombieFox** [comment]
Hi, the icons used in this project are from [Font Awesome](https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free). When the version 6 is released some work will be done to add them. I do not have plans to create new custom icons as this represents a lot of work. I could look into adding different sets, but again this is not a priority for this project.

**Comment by samrth012** [comment]
I can create the new icons and upload them, but I don't have the pro subscription for [Font Awesome](https://fontawesome.com).

**Comment by zombieFox** [comment]
Closing as no there as no fix required.
