### ISSUE TITLE
Customization Enhancements

### ISSUE THREAD

**Issue by SpikeRaxstone** [zombieFox/nightTab#25]
Hey @zombieFox!

**I had a few ideas that might help the progression of this project even if not all of them can be added:**

- As I mentioned in a previous issue, maybe add a light mode.
- Replace the default accent color picker with a [custom one](https://bgrins.github.io/spectrum/) because platforms like Windows have awful UI color pickers:
![image](https://user-images.githubusercontent.com/19519553/55108213-513d5f00-5090-11e9-85e7-72cf150d9f25.png)
- In a tooltip, show the full URL of bookmarks because sometimes long URLs get cut off:
![image](https://user-images.githubusercontent.com/19519553/55108287-89dd3880-5090-11e9-9fac-58643dd9b166.png)
- Allow users to choose the time zone of the clock.
![image](https://user-images.githubusercontent.com/19519553/55107959-c2304700-508f-11e9-9991-8ecc8095b925.png)
- Possibly, hook up the background image system to [Unsplash API](https://unsplash.com/developers) so that users can get a randomized background image.
- Adjustment of the Top Border's width:
![image](https://user-images.githubusercontent.com/19519553/55107666-1edf3200-508f-11e9-8042-a5315c88aa59.png)
- Add customization of the vignette around the outside: 
![image](https://user-images.githubusercontent.com/19519553/55108376-b8f3aa00-5090-11e9-9173-142b26bf5576.png)
- Eventually instead of letters maybe have icons that users can set to show off the bookmark:
![image](https://user-images.githubusercontent.com/19519553/55108522-03752680-5091-11e9-8e57-96b3899269f4.png)
- Allow customization for padding between bookmarks:
![image](https://user-images.githubusercontent.com/19519553/55108692-5949ce80-5091-11e9-8b0e-c93b0f07d00d.png)
- Have an option to show the month number (eg. March = 03) instead of the name:
![image](https://user-images.githubusercontent.com/19519553/55108858-b9407500-5091-11e9-8230-9f27be4de47c.png)
- Also for localization, adding more control over the date ordering. For instance allowing: Month/Date/Year instead of Date/Month/Year.

Hopefully some of these can be added and that I helped contribute in some way!

Cheers,
Spike

**Comment by zombieFox** [comment]
Thanks for all the great feedback! Much appreciated. I'll address these requests in order:

- Light mode is now [in development](https://github.com/zombieFox/nightTab/tree/reverseColour). It's grown into a large task with a lot of changes to the CSS. Watch this space. ⛑ 
- The colour picker uses the native HTML [input colour](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) element, so yes the UI picker is defined by the system or browser. This approach is useful to keep overheads and dependencies low, which is the way I prefer to design/develop. I'll look into external colour picker libraries, like spectrum, and make a call.
- Can do, another [tickets has been made](https://github.com/zombieFox/nightTab/projects/1#card-19523989) for it.
- Dealing with timezones is serious and scary stuff 😨 I'd prefer to not have to develop controls around it. Best to leave it to the users systems time and timezone.
- Sounds fun, I'll investigate randomised background images.
- "Adjustment of the Top Border's width" - I'm sorry, I don't follow, can you please add more details about this one?
- There isn't actually any vignette effect added to the background. A side effect of blurring an image is soft edges revealing nightTabs background colour.
- I'll investigate adding options to substitute "Letters" with icons. [Fontawesome brand set](https://fontawesome.com/icons?d=gallery&s=brands) might be able to help here.
- Padding between bookmarks is tricky as most of the app uses the same variable to control spacing. Will investigate 🔍 
- Month displayed as numbers, [can do](https://github.com/zombieFox/nightTab/projects/1#card-19524235). 
- Date ordering sounds like it falls into localisation. Which, as above, is serious and scary stuff. I'll investigate.

Cheers for all the feedback. There are a lot of good ideas here, it will take some time to investigate, design and develop. Watch the [Project Board](https://github.com/zombieFox/nightTab/projects/1) for updates.

**Comment by SpikeRaxstone** [comment]
Awesome! I'm so glad some of these could be added! Addressing your feedback: (also in order)

- Awesome! I'll look out for Light Mode! 🎉
- Yeah, that's great! I understand what you mean about little dependencies because this by no means, is a necessity, just a small suggestion. 😃
- Great to hear the tooltip can be added!
- Oh, that makes sense. Localization can definitely be difficult.
- Yeah, there are definitely [other options](https://blog.rapidapi.com/top-animation-apis/) but [Unsplash API](https://unsplash.com/developers) by far is the best as you can run unlimited requests all for free, all relatively simple.
- About the "Adjustment of the Top Border's width" comment, I was referring to the slight line at the top of the window which can currently be toggled in the background state region of the header tab in settings:
![image](https://user-images.githubusercontent.com/19519553/55279336-1c6e1980-52d5-11e9-91d6-f1924df217e8.png)
When enabled, it adds a slight border to the top of the window, set to the accent color:
![image](https://user-images.githubusercontent.com/19519553/55279356-61924b80-52d5-11e9-81d1-b19765db6b85.png)
I honestly love this feature and think it adds such a nice touch to nightTab but for me, it feels a bit too wide and if there was some sort of slider to customize how tall it is, that would greatly help! 👍
- 😁 That's funny, I thought it was a vignette all along but being the background makes more sense.
- That sounds perfect! FontAwesome would be great for that! ✔
- Oh alright, understandable.
- Nice! 🌟
- Just swapping the day and date numbers, would be a perfect fix, thanks! 💚

Thanks so much for checking out my feedback! I hope in some way, I could help contribute to the progression of this amazing project! 😁

Cheers,
Spike

**Comment by zombieFox** [comment]
- Light mode ✅ (feature live)
- Replace colour picker ❌(won't change)
- Tooltips ✅ (feature live)
- Timezones ❌(won't change)
- Unsplash - After investigating using the API is costly and difficult. The effect can be achieved with the random Unsplash URL (https://source.unsplash.com/random) ❌(won't change)
- Border width ✅ (feature live)
- Vignette - Behaviour as expected. A new size control has been introduced to scale the image to avoid the vignette. ✅ (feature live)
- Bookmark Icons ✅ (feature live)
- Gutter spacing ✅ (feature live)
- Month date order ✅ (feature live)
- Localisation ❌(won't change)

Closing this issue as all points raised have been address one way or another.
