### ISSUE TITLE
Works really good on safari (Temporary workaround)

### ISSUE THREAD

**Issue by samrth012** [zombieFox/nightTab#250]
On Safari, it works really good all the functions and features work but the workaround is a temporary and just like a forceful way but works really good like original. I would really love if you see to it and reply @zombieFox 

Steps ->
1) Move the file to your home directory. (The builded extension the HTML files) 
![Screenshot 2021-05-19 at 9 00 03 PM](https://user-images.githubusercontent.com/63335952/118840611-3029cf00-b8e5-11eb-9c66-406226f754de.png)
These files ^^^ 

2) Open safari preferences and drag the file into the homepage address, like this and change the "New tabs open with" to homepage.
![Screenshot 2021-05-19 at 9 02 03 PM](https://user-images.githubusercontent.com/63335952/118840953-7a12b500-b8e5-11eb-9049-2e2ae65b9d20.png)

3) This works good now open a new tab and edit your settings.

Really love if you reply and rate my workaround @zombieFox .

Regards:
Samrth

**Comment by zombieFox** [comment]
Looks like a good workaround. I've looked into publishing to Safari in the past but the developer experience is not friendly. Also, at the time (about a year ago) Safari did not support CSS Grid or Flexbox very well. I think it's only now catching up. (Building support for Safari would have needed A LOT of  workarounds/hacks with margins or floats just for to get the bookmark grid to work).

**Comment by samrth012** [comment]
I think you should try adding support for Safari now, as it also supports cross-platform extensions which would make it easier to create an extension using the WebExtension API.

**Comment by dsully** [comment]
+1 to the new compatible APIs for Safari.

**Comment by zombieFox** [comment]
Seems there is no way to develop or test a Safari extension without being a member of the Apple Developer Program. Which itself has a $99 annual fee. I think I'll pass on that since nightTab is a side project freely shared with users on Chrome and Firefox.

**Comment by zombieFox** [comment]
Good reading: [What Apple gives you for $100 as a Safari Extension Developer — and why Reddit Enhancement Suite may cease support for Safari – honestbleeps](https://medium.com/@honestbleeps/what-apple-gives-you-for-100-as-a-safari-extension-developer-and-why-reddit-enhancement-suite-6e2d829c2e52)
