### ISSUE TITLE
Loading duration.

### ISSUE THREAD

**Issue by mysterychemical** [zombieFox/nightTab#254]
I wouldn't say it as bug but loading duration of 700ms seems a bit off. It goes like I press new tab then it goes blank for 400ms and then 200ms for fade in animation of tab. Is there any solution or any existing method to reduce this duration? Or is this normal to have such delay?

https://user-images.githubusercontent.com/73935751/120183780-e075cc80-c22f-11eb-848d-3a9476a40001.mp4

**Comment by zombieFox** [comment]
Hi, yes there is a short fade in animation. I'm planning to remove this going forward. That won't stop the initial delay in loading. That issues is being tackled with ongoing optimisation improvements.

**Comment by zombieFox** [comment]
The recent update is now out. The improvements added have reduced the load time and removed fade in.
