### ISSUE TITLE
NightTab clearing all data randomly

### ISSUE THREAD

**Issue by OofFan** [zombieFox/nightTab#256]
NightTab randomly clears all my settings, bookmarks and everything else. And it wasn't a browser issue.

The bug just happened randomly with no user input or anything like that

 - Windows 10 professional
 - Google chrome
- 91.0.4472.124 Chrome version
- 6.6.0 NightTab version

![image](https://user-images.githubusercontent.com/68186230/124715710-f4d27680-df0b-11eb-86ce-78c5e22161f0.png)

**Comment by Marcelx8** [comment]
@OofFan - do you perhaps have other extensions that might interfere with chrome start-up pages?

@zombieFox - would it help (and if you could) save the current Chrome version when someone creates a backup of their view?

**Comment by zombieFox** [comment]
Thanks @Marcelx8, that is just what I was about to ask. 

Sorry you are having issues @OofFan. Please check to see if you have any other extensions which clear settings, cache or cookies. This will interfere with how nightTab saves your set up.

**Comment by zombieFox** [comment]
> @zombieFox - would it help (and if you could) save the current Chrome version when someone creates a backup of their view?

@Marcelx8 can you explain a bit more about this please? Do you mean saving the Chrome version number in the backup file?

**Comment by Marcelx8** [comment]
@zombieFox Yes, however it's unlikely that most people will back up their view on a weekly basis, it could be helpful, if possible, to be able to log what the difference in chrome versions are when logging a bug. Not 100% how you would troubleshoot it though, so it's just a thought.

**Comment by OofFan** [comment]
Hey I couldn't respond. I didn't have other extensions interfering with nighttab. I didn't delete any cookies or do some thing in the settings. I think chrome interfere with this cause there was some bugs recently. Thanks for reading.

**Comment by andrhua** [comment]
happens to me on the latest firefox as well, no interfering extensions installed

**Comment by zombieFox** [comment]
@OofFan @andrhua Can you check if either of you have the option `Delete cookies and site data when Firefox is closed` turned on in your Firefox settings?

**Comment by andrhua** [comment]
@zombieFox it never was really 
![image](https://user-images.githubusercontent.com/15843809/131250090-b24e7c04-ebce-4b83-b7b3-f47a1e6ec5ba.png)

**Comment by andrhua** [comment]
ok so I found a consistent way to produce this bug on Firefox 91.0.2:

1. visit any site (worked with NY Times, lobsters and Pitchfork)
2. clear site data
![image](https://user-images.githubusercontent.com/15843809/131565182-a2b12162-d888-436b-bd02-492494e02273.png)
3. open new tab and have nighttab with default settings

**Comment by OofFan** [comment]
Hello everyone! I don't have Firefox. I just uninstalled nighttab but I made my tab a lot better.

**Thanks for reading**
