### ISSUE TITLE
Editable Title Icon Input

### ISSUE THREAD

**Issue by Flwnk120** [zombieFox/nightTab#257]
**Is your feature request related to a problem? Please describe.**
The website version on Github has no input for website icon (to the left of the title name). Always bugged me as one of the guy who's really into customizations.

**Describe the solution you'd like**
A simple input for the icon of the website

**Describe alternatives you've considered**
I would rather prefer a fixed icon (like the icon of the Chrome extensions) more than a blank page icon.

**Additional context**
This feature will enhance the professionality of the website.

**Comment by zombieFox** [comment]
The most [recent big update](https://github.com/zombieFox/nightTab/commit/ee4dbc75700af6016a1003f23fbfadda68f15393) to this project has introduced a favicon for browsers that support it (either as an extension or as a [webpage](https://zombiefox.github.io/nightTab/)) This is a [fixed asset right](https://github.com/zombieFox/nightTab/blob/master/src/icon/favicon.svg) now. 

Thanks for this -- feature requests are [still on hold](https://github.com/zombieFox/nightTab/issues/255). Will update when this changes.

**Comment by zombieFox** [comment]
The recent [7.x update](https://github.com/zombieFox/nightTab/releases/tag/v7.3.0) is now out and has a favicon control. This is not supported in every browser but does work in Firefox and Chrome. Marking this as complet.
