### ISSUE TITLE
A small border / clock "issue"

### ISSUE THREAD

**Issue by xzcbvnm** [zombieFox/nightTab#258]
**Is your feature request related to a problem? Please describe.**

A small "issue" or rather an oversight, im using a header border to center my bookmarks and search bar and to make the border nonexistent to the eye, I set it to the same color as my background using the accent color. The problem with that is it makes the spacer for the clock transparent too, and to my knowledge theres no way to change the individual color of the border or the clock spacer without going into the .json file yourself.

**Describe the solution you'd like**

Either a way to change the border color, the clock spacer color, or both. In settings that is.

**Describe alternatives you've considered**

Nope I got nothing I just wanted to say that I really like what your doing and its an amazing project with a ton of great features keep it up! when I get my paycheck next month I play to tip ya guys nicely :)

**Additional context**
![image](https://user-images.githubusercontent.com/88696098/128798619-549066b4-f840-47d9-8901-1b364af281ec.png)
![image](https://user-images.githubusercontent.com/88696098/128799085-805a9470-fcbc-4763-a34d-bc6ad9b7bdf5.png)
![image](https://user-images.githubusercontent.com/88696098/128799410-439770a3-03f2-46f5-bca0-ab8cc3fc876d.png)

**Comment by zombieFox** [comment]
Hi, haven't forgotten about this. 

Yes, for now there is no way to change the colour of the Date or Time separator. The colour is defined by the Theme Accent. 

I have a question, what are you aiming to achieve using the header top border to move the layout? The layout is already centred in the viewport by default:

![9079t57285](https://user-images.githubusercontent.com/7115017/132104522-ef6053b8-2d8e-4f28-ae95-30d5d4285c86.png)

Also to note, Header Border controls have been dropped in v7.0.0. This was dropped to remove overly complex layout issues in favour of a simple divider between the Header and Bookmark area.

**Comment by xzcbvnm** [comment]
Hey! sorry for late response.
If im not mistaken it was acting off a bit when I first installed it and didnt center properly, I restarted my browser and everything worked just fine so as of now its a non issue and Ive not run into any other problem of note.

ps- Amazing product keep up the good work I plan to tip you guys next paycheck I get in.

Cheers

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zombieFox** [comment]
Great to hear it. Thanks!
