### ISSUE TITLE
Support for other protocols

### ISSUE THREAD

**Issue by cnnn666v2** [zombieFox/nightTab#267]
**Describe the solution you'd like**
It would be nice if nightTab would support other protocols like `file://C:/Windows/system32`. Currently it requires you to put http or https in order to make it work. How about not requiring it and fore example link would also work just by typing `youtube.com`?

**Comment by zombieFox** [comment]
Hi, this has been requested before [(1)](https://github.com/zombieFox/nightTab/issues/187) [(2)](https://github.com/zombieFox/nightTab/issues/152). Chrome does not allow extensions to access privileged URLs. Please see [Protected-URLs](https://github.com/zombieFox/nightTab/wiki/Protected-URLs) for details. 

The `https` is necessary for the bookmark tile link to work correctly. All URLs have to have a protocol for the browser to know what to do with the address. I'm don't believe there is any way to make a link without it.

**Comment by cnnn666v2** [comment]
How about a setting that will show a button "copy link" or something like that so we will be able to "open" other protocols?

**Comment by zombieFox** [comment]
If I understand you correctly, this should already be possible. If you right click on a bookmark tile, or any link, you should be able to copy the address to the clipboard.

**Comment by cnnn666v2** [comment]
yeah it works, thanks for the help!
