### ISSUE TITLE
[Query]Edit the text inside the search box?

### ISSUE THREAD

**Issue by onlytanmoy** [zombieFox/nightTab#268]
Hiya, first things first, I totally love your extension, just discovered it today :) great job!

Just a quick query- is it possible to edit the string inside the search box?
![image](https://user-images.githubusercontent.com/48493659/131262133-3c18987f-5fdb-40d3-b5a8-3fa7dfa85892.png)

**Comment by zombieFox** [comment]
Hi, glad you like the project!

There is no way in the current version to make this change. Its [hardcoded into the search module](https://github.com/zombieFox/nightTab/blob/68d38ab099d7287268b019f4528c9fdf0598d45d/src/component/search/index.js#L76). The text is also dynamic, it will display something different depending on the search engine selection and if there are bookmarks saved in the extension. 

What problem would changing this text be solving?

**Comment by onlytanmoy** [comment]
Thanks for your response mate.
No problem, just wanted to customise the text to something fancy like "Search the world..." lol but I now understand doing this will call for significant amount of work so scratch that :)
