### ISSUE TITLE
Edit button glitch (7.0.0)

### ISSUE THREAD

**Issue by badlydrawnface** [zombieFox/nightTab#269]
**Describe the bug**
When I click edit, there is some error that edits the bookmarks, but when you press it again, the group editor appears

**To Reproduce**
1. Click the Edit button on the top of the page, putting the page in edit mode
2. Click the Edit button again, and the page should be in group editing mode (?)

**Expected behavior**
After pressing the edit button in edit mode, the page should go back to the normal view.

**Screenshots**
https://user-images.githubusercontent.com/53501005/131271022-8299bbc8-73e7-45f8-a88a-13bf023fc766.mov

 - OS: macOS 12 Monterey Beta 21A5304g
 - Browser: Firefox Developer Edition 92.0b9
 - nightTab 7.0.0

**Comment by zombieFox** [comment]
Hi sorry you experiencing this bug. This was spotted right away when 7.0.0 went live. A fix was made and released in 7.0.1. If you force Firefox to update this should be resolved.
