### ISSUE TITLE
Make nightTab Works In OperaGx

### ISSUE THREAD

**Issue by SuonimaG** [zombieFox/nightTab#270]
Well I Am Trying Use nightTab On OperaGx But I Dont Know How. I Searched Tutorials, But I Dont Find Anything On Youtube,Chrome,Etc Anyone Knows What To Do?

**Comment by zombieFox** [comment]
Hi!
Please see the wiki page on [browser support](https://github.com/zombieFox/nightTab/wiki/Browser-support). Opera is out of scope of this project as it does not allow extensions to replace the new tab page.

**Comment by SuonimaG** [comment]
Alright, So Opera Is Not Compatible. I Think I Understand

**Comment by Rxdxd56** [comment]
> 

well, im think im changing to chrome
