### ISSUE TITLE
"Background by Theme" not working

### ISSUE THREAD

**Issue by realqdbp** [zombieFox/nightTab#273]
**Describe the issue or bug**
If the setting "Background by Theme" in the "Theme" tab is selected and you have the settings window open, everything is fine. As soon as you close the settings windows, the background color reverts back to the normal dark grey color, or on light mode to the light one.

**To Reproduce**
0. Just if may be conflicted with other settings of mine, here are my export json infos: https://pastebin.com/q0AaFXDA. Normally that shouldn't be a problem.
1. Open a new tab with nightTab installed.
2. Click on the settings icon.
3. If you're not already in the "Theme" tab of the settings window, go there and scroll down until you see the heading "Background". Check that "Background by Theme" is activated.
4. Close the settings window.
5. The background color should have restored itself.

**Expected behavior**
Normally the background should look just like it does in the "preview" if the settings window is still open.

**Screenshots**
Thats how the Background should look like:
![image](https://user-images.githubusercontent.com/85041829/132102988-717c40eb-f36c-41c7-897d-b37fb4288248.png)

Thats how it looks:
![image](https://user-images.githubusercontent.com/85041829/132103014-af175b44-c543-43e6-8c08-272861fc6caf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - nightTab version: 7.0.2

Thanks for help :)

**Comment by zombieFox** [comment]
Hi, thanks for providing details, steps to reproduce and screenshots. Using the provided JSON file I have run some tests -- I can see the background controls are working as expected. 

Just to clarify something, are you referring to the area to the left of the settings menu show here with the white box?  The shade area?

<img width="1267" alt="Screenshot 2021-09-04 at 7 09 16 pm" src="https://user-images.githubusercontent.com/7115017/132104291-9c55530b-3263-4860-84f4-d7a821a9d3e7.png">

(This element won't take on the colour of the Background. It only appears behind the menu or a modal.)

**Comment by realqdbp** [comment]
Hi, thanks for the quick response.
So, I think the shade area is what I mean then. (But only the Background of the shade area xD).

If it's on purpose that the shade area background turns dark again than i'd like you to ask if you could add this feature I meant.

I mean, it's literally already there xD.

For me that would be pretty nice, since I'd love these "milked" background colors that fit the accent.

**Comment by zombieFox** [comment]
Apologies, I do not follow what feature you are asking for.

Yes, the Shade is working as designed, it takes on the Theme Accent colour with a user defined opacity. If you want to, you can hide the Shade but changing: `Settings Menu (gear icon)` > `Theme` > `Shade` > `Shade opacity`. Doing this is a way to see what the Background colour will be without being obscured by the Shade when the Menu is open.

![Kapture 2021-09-06 at 08 58 24](https://user-images.githubusercontent.com/7115017/132182325-cf66714b-4502-4b91-815b-a5ee8c9f5e38.gif)

Does this fulfil your request?

**Comment by realqdbp** [comment]
Ok, I think we are not talking about the same thing :).

Here is what I want:
I want the background to be a "milkier" version of the color my icons (reddit, gdrive....) are. That means, that this color should not be a custom or fixed one that I can set up, it should be as I said, the same color as the "icon color" but milkier / darker.

I'll give you some descriptive screenshots and try to explain what I mean:

This one explains that it is wrong. (btw sry for the small text...)
![wrong](https://user-images.githubusercontent.com/85041829/132217576-f48a5428-4300-4d5d-ad07-8b5ce446a630.png)

Thats how it should look for me.
![right](https://user-images.githubusercontent.com/85041829/132217640-642abdf7-234d-487e-8260-447f85c1d04d.png)

Here with another color. (Reloaded the page)
![image](https://user-images.githubusercontent.com/85041829/132217659-a8cebe70-2f34-4390-a00e-72a4f5e710ef.png)

And again reloaded.
![image](https://user-images.githubusercontent.com/85041829/132217792-026e3e76-4526-43cc-8132-5215b6a18962.png)


Hope that explains it better.

What i meant with settings window open is just that the last three screenshots only have this color as long as the "settings" window is open, here two screenshots.
Thats the correct "background color".
![image](https://user-images.githubusercontent.com/85041829/132217991-a832b3fe-12b2-4f1d-8ddc-2500d5227670.png)

Here I closed the settings window and the "background color" just vanished back to the grey one.
![image](https://user-images.githubusercontent.com/85041829/132218085-20c55cb1-2003-42f0-9ec6-9cd863354edf.png)


Okay, so now I think you understand what I mean :)

And now the question: If it's not a bug, then i'd like to ask you if it'd be possible to add the background color thing that I mean as a feature. 

:) Thanks for the help.

**Comment by Q-out** [comment]
Should be doable right now with custom background image — 
Use this image as a background which is nothing but the colour of the theme background - https://i.imgur.com/hFOn0pW.jpg
![image](https://user-images.githubusercontent.com/52709014/132804076-5858c223-570d-437c-a21f-b34907ed5edd.png)
Set Accent setting to whatever level you like.
![image](https://user-images.githubusercontent.com/52709014/132804146-e21877e2-e9a0-490e-ad6a-12fac00fa994.png)

**Comment by zombieFox** [comment]
> Hope that explains it better.
> What i meant with settings window open is just that the last three screenshots only have this color as long as the "settings" window is open, here two screenshots.
> Thats the correct "background color".

Thanks for providing more details. I think what you are after can be achieved with the current feature set.

The solution by @Q-out seems like a good way to get there. (Thanks @Q-out)

Anther way should be via the `Menu (gear icon)` > `Theme` > `Background` > `Custom colour`

Simply use the colour picked, or copy the hex, of the the current Accent colour. Then adjust from there to your needs. Here is an example:

![Kapture 2021-09-10 at 09 18 48](https://user-images.githubusercontent.com/7115017/132823360-c1fa90bd-2a38-4280-8da8-4d43a26d1aeb.gif)

Now the background colour is the same Hue as the Accent but darker or "milkier".

You can ever go further and change the Theme Colour to better match the Accent by adding a bit of saturation. 

![Kapture 2021-09-10 at 09 16 01](https://user-images.githubusercontent.com/7115017/132823040-30424fd6-01ce-4961-8823-bc16e7fb1115.gif)

**Comment by zombieFox** [comment]
Closing as no fix is needed, or no bug is found.
