### ISSUE TITLE
Missing "scrollbar" string in settings>layout

### ISSUE THREAD

**Issue by metruzanca** [zombieFox/nightTab#278]
Very simply, there seems to be a string missing that should be something along the lines of "Scrollbar" so that people know what `auto, thin, hidden` refers to. 

![image](https://user-images.githubusercontent.com/32832892/132404343-1d08eacc-0bad-4454-8652-d9d0efca0fa9.png)

**Comment by zombieFox** [comment]
Good find! Looks like I forgot to include the `this.label` when the `this.inline` function is called on a `new Control_radio()`. Want me to fix it? Or are you planning something with the `good first issue` label?

**Comment by zombieFox** [comment]
Got this fixed in a [recent commit](https://github.com/zombieFox/nightTab/commit/29ee1bdccfcce3cfcd19a877e24b09268656ba19). 👍🏽
