### ISSUE TITLE
[Query]Display quotations

### ISSUE THREAD

**Issue by onlytanmoy** [zombieFox/nightTab#280]
QQ - do you have any plans to include the option to display famous quotations in the page (that will change on tab reload)?

**Comment by zombieFox** [comment]
Hi, sorry no plans to add such a feature. This project is mainly about bookmarks, so no plans to add quotations, weather or todo lists.

**Comment by onlytanmoy** [comment]
Got it :) cheers mate.

**Comment by zombieFox** [comment]
No probs. Happy for others to fork and make changes for their own needs.
