### ISSUE TITLE
Annoying scroll at the bottom

### ISSUE THREAD

**Issue by chetan0402** [zombieFox/nightTab#283]
![img](https://i.imgur.com/Mdpeesc.png "annoying")

I would request if this could be removed as it's annoying and doesn't look right,
I would appreciate it if there is any fix for this on the client-side.

**Comment by zombieFox** [comment]
Hi, that is strange. There should be no scroll bar along the bottom of the viewport. Can you share details about your set up:

 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
 - nightTab version [e.g. 6.0.0]
 - nightTab export backup JSON

**Comment by chetan0402** [comment]
OS: Windows 10
Browser: Chrome
Version: 93.0.4577.82 (64-bit)
nightTab version: 7.0.2
[nightTab json file](https://pastebin.com/AhjYbUxt)
(The 1,5 bookmark isn't there as it contained private info)

Also i would like to add that this only happened after it auto updated to the newest version. i didn't had this problem previously.

**Comment by Code2dpy** [comment]
![image](https://user-images.githubusercontent.com/84425771/133727867-841beec4-3d39-4d3b-8a69-e30766ae0346.png)
Try this @chetan0402

**Comment by Code2dpy** [comment]
I had this issue too but it went after I did this

**Comment by chetan0402** [comment]
This removes both of the scroll bars. Whereas I only want to remove the x-axis bar and not the y-axis bar.

**Comment by zombieFox** [comment]
Thanks all for the extra info. I think I have a [fix in place](https://github.com/zombieFox/nightTab/commit/eae18f3674a6763f327a768d19a7d16506e5f88f). Should be out in the next release -- Chrome takes a while to check new updates, so it could be about a week before its out.
