### ISSUE TITLE
New Tab randomly not working anymore

### ISSUE THREAD

**Issue by Kojouro** [zombieFox/nightTab#284]
**Describe the issue or bug**
The new tab is completely blank, nothing to click to edit it, inspecting element shows the same, there's nothing on the page.

**To Reproduce**
Open new tab.

**Expected behavior**
It to show my bookmarks and theme.

**Screenshots**
https://prnt.sc/1sm0rbo

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 93.0.4577.82 (Official Build) (64-bit)
 - nightTab version: 7.0.2

**Additional context**
Everything was working fine the past few days, and even earlier today, then it randomly started displaying a black screen as the new tab, the new tab custom name doesn't show, and nothing else shows anymore. Inspecting element shows nothing as well.

**Comment by zombieFox** [comment]
That is very strange. Do you happen to have a JSON backup I can see? As far as I can see nightTab is working in my tests.

**Comment by Kojouro** [comment]
> That is very strange. Do you happen to have a JSON backup you can share here? As far as I can see nightTab is working in my tests.

I sadly don't have a backup, I didn't even edit the theme heavily. Simple color pick from the options available and an animated image background with my bookmarks. Nothing else really changed about it.

**Comment by Kojouro** [comment]
Re-installing the plugin has fixed it for now, still unsure what caused it. If it happens again I will give more detailed updates, and I will be sure to keep a backup to show as well as recover my page.

**Comment by zombieFox** [comment]
Understood. Sorry you got hit with this strange bug. I wish I could work out what is causing it -- the backup file is really important in understanding the end user state when investigating bugs. Thanks for brining it to my attention.
