### ISSUE TITLE
Can't see favicon

### ISSUE THREAD

**Issue by sinankizar** [zombieFox/nightTab#286]
Can,t see the favicon, am I doing womething wrong or is it expected behavior?

Open browser or opening a new tab doesn't show the favicon

**Expected behavior**
Showing up the gorgeous nighttab favicon

**Screenshots**
<img width="727" alt="Screen Shot 2021-09-23 at 08 53 56" src="https://user-images.githubusercontent.com/28201097/134460319-665e5c8d-ab7f-4bc6-beef-6c1acb9282ee.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Brave
 - Version 1.29.81
 - nightTab version 7.0.2

**Comment by zombieFox** [comment]
Hi. Sorry, Brave is [not a support browser](https://github.com/zombieFox/nightTab/wiki/Browser-support) so I don't know why it is not showing a favicon. Each browser handles the new tab favicon differently. For example, Firefox has has shown a favicon for a few version, Chrome only just started showing a favicon. I don't know how Brave handles favicon.

**Comment by sinankizar** [comment]
It is using CHrome and everythng is working so far. I am seeing the favicon on demo page and I am waiting for the 7.1 update then. Thank you so much for your kind support. I will inform you about this when the 7.1 update pushed to store.

**Comment by zombieFox** [comment]
v7.3.0 is now out. Custom favicon is included in this release. 🚀

**Comment by sinankizar** [comment]
Thank you for the headsup and for your work mate. I have uploaded nighttab's favicon to my server and setup in settings but still doesn't show up. I think it is related on brave side you may ignore this issue.

**Comment by zombieFox** [comment]
Yup. Since the new tab page is not technically a website each browser will handle the favicon differently -- or completely ignore it.
