### ISSUE TITLE
Nighttab not working anymore, shows blank page

### ISSUE THREAD

**Issue by Pinback22** [zombieFox/nightTab#287]
Hi @everyone,

on Chrome the Nighttag extension stopped working today.
Browser: Chrome Version 94.0.4606.61 (Offizieller Build) (x86_64)
Using the developer tools I found the following error message:

Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'nightTabBackup' exceeded the quota.
    at Object.set (chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:930358)
    at Object.Wo.backup (chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:932973)
    at Object.Wo.load (chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:933762)
    at Object.Wo.init (chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:935906)
    at chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:942209
    at chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:942385
    at chrome-extension://hdpcadigjkbcpnlcpbcohpafiaefanki/index.5b4567afd5fc3b35d57c.js:1:942389

Anyone with an idea what to do?

Regards,
Pinback

**Comment by zombieFox** [comment]
Hi, sorry you had this happen. This looks like a local storage max limit error. Do you know if your nightTab had a background image set? One loaded from your local files? This could cause an error when a nightTab update is released. 

Do you happen to have a backup JSON file I can inspect?

**Comment by Pinback22** [comment]
Hi @zombieFox ,
yes, I still could fetch a backup.
[nighttab-backup.json.zip](https://github.com/zombieFox/nightTab/files/7241507/nighttab-backup.json.zip)
I can find my background image (m5090Zt.jpg) which is included in the JSON as PNG. 
Can you give me a hint how I can disable the background image in the JSON? After that I could just import the backup again.

**Comment by zombieFox** [comment]
Of course, happy to help. The JSON has the image data saved at this location: `state.background.visual.image.file.data`. If you delete the value at that address and restore the backup in nightTab it should work. 

I've gone ahead and remove the data too and and it worked for me. Here is the modded JSON file: 
[nightTab backup - 2021.09.28 - 08 31 51.json.zip](https://github.com/zombieFox/nightTab/files/7242016/nightTab.backup.-.2021.09.28.-.08.31.51.json.zip)
 
 Sorry you got hit with this bug 🐛

**Comment by zombieFox** [comment]
For some context, this should not be an issue going forward as local background image support was removed in v7.x -- for [reasons like this](https://github.com/zombieFox/nightTab/wiki/Local-background-image). 🤞🏽

**Comment by Pinback22** [comment]
After reinstalling the extension and restoring the modified backup file it works.
Thank you, this is really awesome. 
Enjoy that coffee ;-)

**Comment by zombieFox** [comment]
Glad it's working, thanks! ☕
