### ISSUE TITLE
Video Wallpaper

### ISSUE THREAD

**Issue by Narimanghods** [zombieFox/nightTab#295]
Hi,

I was trying to get a video as my wallpaper but it seems like I cannot in any way I try. I have a MacOS computer and I uploaded my MP4 to Imgur and copied the link there once I posted it on my page. I enter the full link (e.g. https://imgur.com/blahblahblah) but it still doesn't seem to work. I feel like I followed all the step idk why its not working :/

Any help would be appreciated.

Thanks

**Comment by zombieFox** [comment]
Hi, Please add the URL you are using for the video file so I can investigate.

Also include details like:

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
nightTab version [e.g. 6.0.0]
nightTab backup JSON

**Comment by Narimanghods** [comment]
This is the link to the video I want to use: https://imgur.com/FBsgMiA
Using MacOS
Browser is Chrome, Version 94.0.4606.61
NightTab is Version 7.0.2

**Comment by zombieFox** [comment]
Thanks for providing more details. That is a page URL, not a hosted video file. Unfortunately a page URL can not be used as a video background. Please read the wiki page on [setting a video](https://github.com/zombieFox/nightTab/wiki/Setting-a-background-video-or-image#background-video) file as a background.
