### ISSUE TITLE
Ability to change and/or choose the search engine

### ISSUE THREAD

**Issue by AD007xD** [zombieFox/nightTab#309]
A QOL feature that I'd assume many would very much appreciate. 

Personally I use duckduckgo and not google and I find it a bit tedious to search in the browser's search bar instead of nightTab's.
A button in the settings named "Search Engines" which on clicking would let you choose your desired search engine.

**Comment by zombieFox** [comment]
Hi, have you tried changing the search engine via the settings menu?

Controls to change the search engine can be found under the Settings menu > Header > Search > Search engine.

Hopefully this works for you.

**Comment by AD007xD** [comment]
Oh my bad I did not realize it was there. Thanks for clearing it out!
