### ISSUE TITLE
Override accent for specific tiles

### ISSUE THREAD

**Issue by Tritiumnzlol** [zombieFox/nightTab#31]
I'd like to make the accent for some tiles a different color. as the association to a website's branding is quite important.

e.g.
* Facebook tile overwrite the accent to be blue.
* Youtube tile overwrite the accent to be red

I think all you'd need UI wise would be a color picker on the tile's edit pop up would be great.

**Comment by zombieFox** [comment]
Sounds like a good idea. I've added it to the project board. Thanks @Tritiumnzlol  👍

**Comment by Tritiumnzlol** [comment]
Sweet.

**Comment by zombieFox** [comment]
Feature is now live.

**Comment by Tritiumnzlol** [comment]
Sweet! thanks buddy
