### ISSUE TITLE
Chrome extension not working.

### ISSUE THREAD

**Issue by kojofosu** [zombieFox/nightTab#310]
# Have you checked the [nightTab Wiki for support?](https://github.com/zombieFox/nightTab/wiki)

**Please check before posting a question or issue.**

Some frequently asked questions include:
- [Browser support](https://github.com/zombieFox/nightTab/wiki/Browser-support)
- [Protected URLs](https://github.com/zombieFox/nightTab/wiki/Protected-URLs)
- [Resetting when opening the browser](https://github.com/zombieFox/nightTab/wiki/Resetting-when-opening-the-browser)
- [Setting nightTab as your Firefox homepage](https://github.com/zombieFox/nightTab/wiki/Setting-nightTab-as-your-Firefox-homepage)

---

# Still need to report an issue or ask a question:

**Describe the issue or bug**
For a while now, nighttab has not loaded up on my homepage. It just shows a black screen on home screen

**To Reproduce**
1. Open browser

**Expected behavior**
A black screen is shown rather than the nighttab extension on the homepage

**Screenshots**
![Screenshot (83)](https://user-images.githubusercontent.com/20203694/138235186-a7e66491-6b48-456d-b78e-f47883d0c4f6.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [Version 94.0.4606.81 (Official Build) (64-bit)]
 - nightTab version [7.3.0]

**Additional context**

**Comment by zombieFox** [comment]
That is very strange. Do you have a backup JSON I can look at?

**Comment by kojofosu** [comment]
yes, i do

**Comment by kojofosu** [comment]
[nt_backup.txt](https://github.com/zombieFox/nightTab/files/7387778/nt_backup.txt)
