### ISSUE TITLE
add collapse/expand button of the label group

### ISSUE THREAD

**Issue by p5ydn0** [zombieFox/nightTab#314]
Thank you so much for sharing. This product is great.

I hope to add this functions: add collapse/expand button of the label group.

the button this:

![image](https://user-images.githubusercontent.com/25891214/139525808-b92d8877-e7af-43d4-8833-5bc0f119e893.png)

The reason for this idea is that my entire nightTab page has only a few tag blocks, that is, only one tag group. So in this case, the existence of the button: 1 is not practical; 2 is not beautiful.

I tried to find related options in the settings, but I didn't find it. If it already exists, please forgive me, and can you tell me the location of the setting?

Thank you.

**Comment by zombieFox** [comment]
Hi, glad you like the project. I'm sorry, but I'm not sure I follow this issue. Do you mean you would like a way to disable or hide the collapse button on a bookmark group?

If so this can be achieve by editing the bookmark group in question. In the group edit modal, turn off the "Show Collapse" control. E.g:

https://user-images.githubusercontent.com/7115017/139526220-6f594364-73e0-4e62-ab43-e709288caa0e.mp4

**Comment by p5ydn0** [comment]
@zombieFox 

Thank you very much for your answers. Sorry for wasting your time due to my ability. I went directly to the `Settings` button option to find it.

Thanks again. This project is really excellent. It is a product I use every day. Thanks!
