### ISSUE TITLE
i want to know how can we get the link of the image for applying it as the image of the bookmark

### ISSUE THREAD

**Issue by Pranet17** [zombieFox/nightTab#317]
i want to know how can we get the link of the image for applying it as the image of the bookmark,means they say to put the link for persnolized icon for bookmark or shortcut
![Screenshot (6)](https://user-images.githubusercontent.com/94548396/142225952-5d595e43-a419-489e-95e8-a1ae7b27e6cd.png)

**Comment by zombieFox** [comment]
Hi, if I understand your question correctly, the URL for wish to use here depends on where you save your images. I would recommend you upload your images to a GitHub repo or Imgur. Then copy the URL of the image for use in nightTab.

**Comment by Pranet17** [comment]
Ok, thanks, will try
