### ISSUE TITLE
Safari Extension developed

### ISSUE THREAD

**Issue by samrth012** [zombieFox/nightTab#318]
Hey this is Samrth here I wanted to contribute in this since long and I have been working on the safari extension design since some time, today I have finally built the safari extension for nightTab and all the features work perfectly fine, except the data restore, I want to know how the data is imported so that I can fix it.

I would like to add it and contribute, 
You can contact me by mail - samrth012@gmail.com 
And also add me as contributor directly on the same email.

Attaching the screenshots for proof.
![Screenshot 2021-11-19 at 7 03 01 PM](https://user-images.githubusercontent.com/63335952/142631376-89182af4-a6ac-4d3b-86c9-0beac4cfd183.png)
![Screenshot 2021-11-19 at 7 03 55 PM](https://user-images.githubusercontent.com/63335952/142631403-85d23576-1e99-4e0b-9fd7-bbcdcacc5547.png)

**Comment by samrth012** [comment]
Would love to help and do contact me positively.

**Comment by zombieFox** [comment]
Hi. Glad you like the project. I've [looked into supporting Safari in the past](https://github.com/zombieFox/nightTab/issues/250) but the developer experience is very poor. In short I do not have the time or compulsion to build workarounds to pay yearly fees to support Safari. 

Happy for you to fork the project and build a Safari supported version if you wish to.

**Comment by samrth012** [comment]
Sure just want to know how the data is being restored and exported by the extension using json and how is it implemented in the css so that I can fix the problem.

**Comment by zombieFox** [comment]
The application checks the local storage on page load for any saved data. Then the [data module](https://github.com/zombieFox/nightTab/blob/main/src/component/data/index.js) takes over. The order of events is:

[data.init()](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/index.js#L6) starts off the data restore process.

Then [data.restore(data.load())](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/data/index.js#L454) passes in any data fund in [local storage](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/data/index.js#L297).

[data.restore](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/data/index.js#L258) validates the data and if it passes the different chunks of the [state object](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/state/index.js#L5) is sent to the different parts of the app. E.g: [State restore](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/state/index.js#L268) and [Bookmark restore](https://github.com/zombieFox/nightTab/blob/45141b4a1cb5a9fbeddaf98831191aedc011df5e/src/component/bookmark/index.js#L489)

**Comment by samrth012** [comment]
Ok thanks just wanted to ask a few more things, where are these files located in the packed extension ?

**Comment by metruzanca** [comment]
The "packaged extension" is minified code and not meant to be read by a human. You probably want to look at the code before it goes thru webpack instead.

**Comment by metruzanca** [comment]
I know @zombieFox is pretty occupied as of late, so @samrth012 if you need a bit more in depth help with stuff like webpack or getting your fork to pull in updates properly let me know as I've dealt with it with my development fork of nighttab.

**Comment by samrth012** [comment]
Ok @metruzanca thanks for the info, but for the safari extension I need the direct html files for ease of use, will try it with the source code do inform me on how is the code complied for the chrome or Firefox extension.

**Comment by samrth012** [comment]
@metruzanca Any alternative to web pack for compilation.

**Comment by metruzanca** [comment]
@samrth012 
> Any alternative to web pack for compilation?

Yes, there are alternatives but I do not recommend changing build tool for your fork (unless you know what you're doing, but since you had to ask, I'd strongly recommend you didn't).

There's a couple of reasons not to, the primary one being that if we (Zom & I) update nighttab's build process in any way, you'd have to figure out how to do the same exact thing with your build tool and so you'd be creating extra duplicate work. Another reason to stay with webpack is its the most popular and so it's got really good documentation and support.

Earlier you also said:

> for the safari extension I need the direct html files for ease of use

Again, this is going to result in a LOT of extra work. the html and js files are generated by the build tool. If we update nighttab, you'll be on your own updating your fork and probably ending up reverse engineering compiled code from scratch every time.

Source code is always easier to work with so "direct files" is going to make your job MUCH harder.

Correct me if I'm wrong, but from your comments I have a feeling you've never worked with nodejs before (maybe even javascript, idk). If this is the case, I'd highly recommend getting nodejs installed and cloning this repo and try to get it running and then building on your machine.

Then you should see what requirements safari has for extensions and make those changes to the **source code**. 

---

I'm happy to help you get things running if you need. We could even jump into a google meet sometime. The more people who work on nighttab the better :)

**Comment by samrth012** [comment]
Yes thats what I did cloned the repo and builded it locally and I am finding the way I can use the source code directly. And also I am clear on using web pack and I have totally understood it.

And also I have worked around with nodejs and javascript earlier.

> 
> Then you should see what requirements safari has for extensions and make those changes to the **source code**.
> 

Also I also had the same thought and I am working on the same since then.

**Comment by metruzanca** [comment]
> Yes thats what I did cloned the repo and builded it locally and I am finding the way I can use the source code directly. And also I am clear on using web pack and I have totally understood it.

Alright, you've found your way around things. Awesome!

Since feature parity between firefox and chrome is quite important to nighttab, you might want to fork the repo instead of just cloning it. That should help you pull in updates from nighttab more easily since github's intergrations will give you a hand. In mosts cases any changes on nighttab would just require pulling from upstream and a git rebase (or a git merge).

**Comment by metruzanca** [comment]
Forgot to ask if could share your repo with us once you've got something working?

**Comment by samrth012** [comment]
> Forgot to ask if could share your repo with us once you've got something working?

Surely will do it in a while. 

> > Yes thats what I did cloned the repo and builded it locally and I am finding the way I can use the source code directly. And also I am clear on using web pack and I have totally understood it.
> 
> Alright, you've found your way around things. Awesome!
> 
> Since feature parity between firefox and chrome is quite important to nighttab, you might want to fork the repo instead of just cloning it. That should help you pull in updates from nighttab more easily since github's intergrations will give you a hand. In mosts cases any changes on nighttab would just require pulling from upstream and a git rebase (or a git merge).

Got it.

**Comment by zombieFox** [comment]
Thanks @metruzanca for jumping in and providing direction ❤️ 

> I know @zombieFox is pretty occupied as of late

I'll jump in where I can, work and life schedules permitting.

**Comment by metruzanca** [comment]
Been about a month, @samrth012 hows the Safari version going?

**Comment by samrth012** [comment]
Next to final release, just working on a few bug fixes @metruzanca

**Comment by IzzyWorks** [comment]
Has this endeavour died? @samrth012 How's it going?

**Comment by samrth012** [comment]
> Has this endeavour died? @samrth012 How's it going?

It didn't die, i had two deaths in my family back to back, so i have been struck on that since a while, i am trying to come back and start working all over again and continue things that were going great.

**Comment by IzzyWorks** [comment]
> l over again and continue thing

Gezzus. Well take care of you're self, this can wait. If you are actively coding again just shoot me a line as I will likely remain interested in porting over nightTabs. This extension is amazing.

**Comment by IzzyWorks** [comment]
> > Has this endeavour died? @samrth012 How's it going?
> 
> It didn't die, i had three deaths in my family back to back, so i have been struck on that since long, i am trying to come back and start working all over again and continue things that were going great. And also my dog died so technically four deaths

Gezzus. Well take care of you're self, this can wait. If you are actively coding again just shoot me a line as I will likely remain interested in porting over nightTabs. This extension is amazing.

**Comment by samrth012** [comment]
> > > Has this endeavour died? @samrth012 How's it going?
> > 
> > It didn't die, i had three deaths in my family back to back, so i have been struck on that since long, i am trying to come back and start working all over again and continue things that were going great. And also my dog died so technically four deaths
> 
> Gezzus. Well take care of you're self, this can wait. If you are actively coding again just shoot me a line as I will likely remain interested in porting over nightTabs. This extension is amazing.

Surely will do, even i was too excited for this until this happened 😥

**Comment by samrth012** [comment]
> > > Has this endeavour died? @samrth012 How's it going?
> > 
> > 
> > It didn't die, i had three deaths in my family back to back, so i have been struck on that since long, i am trying to come back and start working all over again and continue things that were going great. And also my dog died so technically four deaths
> 
> Gezzus. Well take care of you're self, this can wait. If you are actively coding again just shoot me a line as I will likely remain interested in porting over nightTabs. This extension is amazing.

Hi i am starting from tomorrow, lets see what best get.

**Comment by IzzyWorks** [comment]
Same! Your.extention is probably one of my favourite plugins I've evr. I'd use your safari solution religiously if you ever release it. I have some frontend skills with HTML, Javascript for dom manipulation so if be happy to help take some of the load off if you return to development.

**Comment by samrth012** [comment]
Sure guys have been working on it since long there are some bugs which need sorting will give out the final version soon

**Comment by IzzyWorks** [comment]
Muchas Gracias!

**Comment by nalimovm** [comment]
@samrth012 Hello. Is there any updates?

**Comment by samrth012** [comment]
> @samrth012 Hello. Is there any updates?

Ya just a few changes left, got exams on between so I gave less time to work on it

**Comment by Beay-apb** [comment]
@samrth012 how is it going? I am waiting for almost a year now, since first time I saw this topic. Will we see it anytime soon?

**Comment by samrth012** [comment]
> @samrth012 how is it going? I am waiting for almost a year now, since first time I saw this topic. Will we see it anytime soon?

Hi sorry guys couldn't update for long, the extension build is complete but it is definately unsigned, I don't have an apple developer account anymore so figuring a way around for that as safari ignored unsigned extension by default so u need to enable it again and again in settings.

**Comment by samrth012** [comment]
If anyone has an apple developer account do contact if you would like to contribute

**Comment by samrth012** [comment]
![Screenshot 2023-07-12 at 9 47 04 AM](https://github.com/zombieFox/nightTab/assets/63335952/e1ddc379-8ce3-4a18-94c6-ed659372ac2e)

**Comment by samrth012** [comment]
@zombieFox @metruzanca @IzzyWorks @nalimovm hello everyone thanks a lot for the support and the help provided by everyone.
Finally today I can say its complete the extension is done.
[https://github.com/samrth012/nightTab/releases/tag/Safari](https://github.com/samrth012/nightTab/releases/tag/Safari)
Open safari enable the extension and enjoy!!! 🎉🎉🎊

If anyone is unable to use nightTab after that also make sure in Safari settings newtab is selected to nightTab extension. 

For any other queries do drop a comment.

**Comment by samrth012** [comment]
@zombieFox do add me as collaborator

**Comment by Beay-apb** [comment]
Thanks, mate, it works very well

**Comment by samrth012** [comment]
> Thanks, mate, it works very well

Welcome bro ✌️

**Comment by spawnYzn** [comment]
Unfortunately I ran into two bugs.
First is "open links in new tab" doesn't seem to work, neither by configuring it in the Bookmarks section of the settings of nightTab, neither by trying to cmd + click on a link.
Second is trying to change any appearance settings of the theme reloads the tab. 
Can you look into it please? The theme thing isn't bothering me much, as I imported all settings from my Windows machine, but the link in new tab thing is annoying.

**Comment by samrth012** [comment]
> Unfortunately I ran into two bugs.
> First is "open links in new tab" doesn't seem to work, neither by configuring it in the Bookmarks section of the settings of nightTab, neither by trying to cmd + click on a link.
> Second is trying to change any appearance settings of the theme reloads the tab.
> Can you look into it please? The theme thing isn't bothering me much, as I imported all settings from my Windows machine, but the link in new tab thing is annoying.
> Thank you for your work so far, was really looking forward to this release! :)

I have tested it so far on like 25-30 devices and it seems fine with none of the problems you mentioned and the appearance thing it is working perfectly fine might be some problem with the installation or steps. 
I recommend you trying to reinstall once with the exact steps I mentioned, if it still doesn't work do ping me with the screenshot of the issue or a small recording. 
THANKS FOR THE INFORMATION!

**Comment by samrth012** [comment]
@zombieFox ???

**Comment by zombieFox** [comment]
@samrth012 I highly recommend you fork the project and provide instructions for the Safari workaround there. 

As [mentioned earlier](https://github.com/zombieFox/nightTab/issues/318#issuecomment-974275421) I can not commit to supporting another browser and I much prefer to to develop for browsers that operate the same way, (Firefox and Chrome).

Adding the [instructions](https://github.com/zombieFox/nightTab/issues/318#issuecomment-1631847772) to the readme goes against one of the ideals of the project by making the installation complex. Should I add these instructions I will undoubtedly see an increase in support, issue and bug posts/emails. 

Since you have successfully found a workaround to running nightTab in Safari I will close this issue.

**Comment by samrth012** [comment]
Not  a workaround but extension is complete and thanks for replying.

**Comment by samrth012** [comment]
@metruzanca @zombieFox @IzzyWorks Thanks for the all the support, rethought about the main idea around this project, have worked out a few things, made the installer really simple like any other app on macOS, I will keep updating with every version bump, if you like it please add it in the official page.



It is working as any other extension should work, nothing complex left, only install app open and done, same way apps from App Store or any other side loaded app works on Mac.


I am raising a pull request if you would like to add, it would be great, or if not maybe give a reference to my repo so I can keep maintaining it, and it reaches the users.
