### ISSUE TITLE
Saving configuration outside the browser's local storage (or backing up)?

### ISSUE THREAD

**Issue by zethexx** [zombieFox/nightTab#33]
Is there a way to save the configuration like as a file that you can restore or in the folder of the install? Or maybe get the configuration from the local storage from the browser and be able to restore it into the browser? Because it can be annoying to have to set up the webpage again every time local browser storage is cleared.

**Comment by SpikeRaxstone** [comment]
I agree. This could allow users to transfer their settings between devices or browsers. Maybe it could be stored in a JSON file for easy access?

**Comment by zombieFox** [comment]
Yup, I've had this thought before. If you look at my other project, [awesomeSheet](https://zombiefox.github.io/awesomeSheet/), it does this quite well. Controls to export data as JSON which can be imported later:

![Screenshot 2019-04-23 at 5 13 06 pm](https://user-images.githubusercontent.com/7115017/56597816-2ab90800-65eb-11e9-8167-ac9f4a0c7b4f.png)

I will add this to the project board. But fair warning, it's a large task and will take a while for me to design and build it. 🙂

**Comment by zombieFox** [comment]
As a workaround, for now, it is possible to achieve this with nightTab in two ways:

1. If you are familiar with Chrome Dev Tools. Under `Application > Local Storage` you can copy the current state of nightTab to the clipboard. Then on another browsers (in Dev Tools again) paste it into the same location. If on either computers there is nothing listed under `Local Storage` just make a change to nightTab and the app will make a fresh save:  ![Screenshot 2019-04-23 at 5 19 23 pm](https://user-images.githubusercontent.com/7115017/56598472-76b87c80-65ec-11e9-960b-a014469ad4ba.png)
2. Alternatively, edit [state.js](https://github.com/zombieFox/nightTab/blob/master/js/state.js) and [bookmarks.js](https://github.com/zombieFox/nightTab/blob/master/js/bookmarks.js) on your copy of nightTab and share that between computers. 

These are not ideal solutions and controls on the UI would be better. I'm just listed the options available right now before new work on this feature request begins.

**Comment by zombieFox** [comment]
Feature is now live.
🚀

**Comment by adrianmihalko** [comment]
Any way to read "database" from a file? I have many devices and it's not easy to import/export/sync data to every device. It would be so great such a feature.

**Comment by zombieFox** [comment]
@adrianmihalko Do you mean syncing data between devices on the same chrome account?

I came across this recently: [https://developer.chrome.com/extensions/storage](https://developer.chrome.com/extensions/storage).

I've opened a new ticket ([93](https://github.com/zombieFox/nightTab/issues/93#issue-500293341)) to explore this more.
