### ISSUE TITLE
Custom search engine really doesn't work.

### ISSUE THREAD

**Issue by tzargar8** [zombieFox/nightTab#332]
**Describe the issue or bug**
Adding a custom search engine is broken. I managed to get it to work a few times, but then after the first search the nightTab settings were automatically updated to a configuration that doesn't work anymore. At the moment I can't get it to work even 1 time with the same settings anymore. Either I'm directed back to nightTab-new-tab-page or to Startpage-front-page.

Here's what I've tried:
Search engine>>Custom>>URL as:
- "https://www.startpage.com/do/search?q="
- "https://www.startpage.com/do/search?q=%s"
- "https://www.startpage.com/do/search?q=%s&segment=startpage.brave"

Search engine>>Custom>>Name attribute as:
- "" (blank)
- "%s"
- "%s&segment=startpage.brave"
- "&segment=startpage.brave"

And all combinations of these.

Like I said, when I did manage get it to work then the settings changed automatically to such that it didn't work anymore.

Working combination was (IIRC):
- URL as: "https://www.startpage.com/do/search?q="
- Name attribute as: "&segment=startpage.brave"
But then it was changed automatically to:
- URL as: "https://www.startpage.com/do/search?q=%s&segment=startpage.brave"
- Name attribute as: ""
Which directs to the Startpage front page or back to nightTab.

**To Reproduce**
1. Go to: Settings>>Header>>Search>>Search engine
2. Click on: Custom
3. Add: Name such as "Startpage"
4. Add: URL such as "https://www.startpage.com/do/search?q="
5. Add: Name attribute such as "&segment=startpage.brave"

**Expected behavior**
I expect the search results page of Startpage to open with the given string as the query.

**Desktop (please complete the following information):**
 - OS: W10 10 Pro N (build: 19044.1415)
 - Browser: Brave
 - Version: 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
 - nightTab version: 7.3.0

**Comment by zombieFox** [comment]
Hi, sorry you are having issues. As far as I can test this feature is working as expected. 

The values you need to enter to use `startpage` search is:

Name: 
anything

URL: 
https://www.startpage.com/do/search

Name attribute:
q 

https://user-images.githubusercontent.com/7115017/148544742-86fcc854-f462-44a6-8ef6-31a9d7aaf114.mp4

**Comment by tzargar8** [comment]
It works now, but the documentation clearly needs improving

**Comment by f-x1-1** [comment]
I have the same problem, the solution doesn't work for me. 
I'm using brave search engine.
https://search.brave.com/

**Comment by metruzanca** [comment]
With URL: `https://search.brave.com/search` and Name: `q` it works.

The page is indeed unclear as when the name attribute is left blank it would appear as if q is being used by default, however it actually isn't. This is definitely something we can improve.

**Comment by f-x1-1** [comment]
> With URL: `https://search.brave.com/search` and Name: `q` it works.
> 
> The page is indeed unclear as when the name attribute is left blank it would appear as if q is being used by default, however it actually isn't. This is definitely something we can improve.
> 
> EDIT: Seems I can't reopen issues or change the name :( @zombieFox.
> 
> But do note I'll see what I can do about this and open up a PR soon (weekend probably)
> 
> @f-x1-1 just to make sure you see the fix to get brave search working

Thank you!
