### ISSUE TITLE
Custom background images don't display themselfs after relaunching the browser sometimes

### ISSUE THREAD

**Issue by RaptaG** [zombieFox/nightTab#353]
**Describe the issue or bug**
After closing and opening and closing the browser 2 ore more time, the image doesn't show itself, even with refreshes and new tab opening

**To Reproduce**
1. Add a custom image
2. Relauch 2 times the browser
3. See error

**Expected behavior**
The background image being showed all the time

**Screenshots**
_none_

**Desktop (please complete the following information):**
 - OS: Garuda Linux
 - Browser: FireDragon (Firefox fork)
 - Version: Latest
 - nightTab version: 7.3.0

**Additional context**
The image is on a private GH repo

**Comment by zombieFox** [comment]
Hi, sorry you are having issues. But only Firefox and Chrome is supported by this project. I can't assure the performance or stability of nightTab on other browsers. Please see the [wiki](https://github.com/zombieFox/nightTab/wiki/Browser-support) for more details.

**Comment by RaptaG** [comment]
> Hi, sorry you are having issues. But only Firefox and Chrome is supported by this project. I can't assure the performance or stability of nightTab on other browsers. Please see the [wiki](https://github.com/zombieFox/nightTab/wiki/Browser-support) for more details.

Hello and thanks for responding! I did check the wiki, but I couldn't find anything that could possibly help. I also checked what was said about the cache etc., but still nothing. Also, my browser is basically Firefox, but on a modified edition..
