### ISSUE TITLE
'Randomize Now' button does not change accent bubble color.

### ISSUE THREAD

**Issue by FunkFrog** [zombieFox/nightTab#37]
https://funkfrog.me/sV892hRd4k.png

Pressing 'randomize now' does not change the accent bubble color, as seen above.

**Comment by zombieFox** [comment]
Hi, that does "bubble color" refer to? The image shared does not seem to load. Can you upload the image this issue in another comment please?

**Comment by FunkFrog** [comment]
Fixed now, I messed up my DNS settings lol

The accent button's color display circle is what I'm referring to

**Comment by zombieFox** [comment]
Understood! I see now. Yes you are right, this seems to be a bug introduced in v2.22.0. I'll address it asap! Thanks for the bug catch 🐞

**Comment by zombieFox** [comment]
Bug fix rolled out in [v2.22.1](https://github.com/zombieFox/nightTab/releases) 🚀
