### ISSUE TITLE
Bookmark bug 

### ISSUE THREAD

**Issue by iggnaT** [zombieFox/nightTab#370]
When opening bookmark in new tab with middle click bookmark becomes selected and does not unselect until somewhere else clicked.

1. Add any bookmark
2. Middle click it

It should open desired page in new tab and become like unselected bookmark

https://user-images.githubusercontent.com/81556468/169245891-f0df0c98-d6ea-4679-a9bc-82fa13fc6c4a.mp4

PC:
 - OS: Windows 11
 - Browser Google Chrome
 - Version 101
 - nightTab version 7.3.0

sorry for bad english

**Comment by zombieFox** [comment]
Hi, this is working as intended. The Bookmark links retain the `:focus` state when clicked. This state is similar to then `:hover` state.
