### ISSUE TITLE
How do i turn off military time on nighttab

### ISSUE THREAD

**Issue by MintyDraws** [zombieFox/nightTab#371]
how do i turn it off bec i dont understand most of it

**Comment by metruzanca** [comment]
Open settings, click on `header` from the side menu and scroll down to `Clock`(or click from the header again). Then just untick `24 Hours`. 

![image](https://user-images.githubusercontent.com/32832892/170368719-6e7fb8dd-5077-4b04-9146-316e237ab5c6.png)

**Comment by MintyDraws** [comment]
ty

> Open settings, click on `header` from the side menu and scroll down to `Clock`(or click from the header again). Then just untick `24 Hours`.
> 
> ![image](https://user-images.githubusercontent.com/32832892/170368719-6e7fb8dd-5077-4b04-9146-316e237ab5c6.png)

ty

**Comment by zombieFox** [comment]
Thanks @metruzanca !
