### ISSUE TITLE
Theme not working 

### ISSUE THREAD

**Issue by createvi** [zombieFox/nightTab#372]
**Describe the issue or bug**
Can't use this theme on Opera. i just installed Opera and  added the extention but nothing is working.

**To Reproduce**
1. Install Opera
2. Add Nighttab on Opera through Chrome Web Store
3. Open a new tab

**Expected behavior**
NIghtag should be showing

**Desktop (please complete the following information):**
 - OS: Zorin OS 16.0 
 - Browser Opera 
 - Version 87.0.4390.36
 - nightTab version  7.3.0

**Comment by zombieFox** [comment]
Hi, sorry but Opera does not allow extensions to replace the new tab page. Please see the [Browser support wiki page](https://github.com/zombieFox/nightTab/wiki/Browser-support) for details.
