### ISSUE TITLE
Pywal Integration

### ISSUE THREAD

**Issue by Retr0astic** [zombieFox/nightTab#375]
Is it possible for nightTab to set themes based on pywal settings?

**Comment by metruzanca** [comment]
Currently, theres not pywal integration. I don't see a pywal extension for chrome, so its unlikely that a pywal integration will be created as we prefer to keep feature parity.

If this becomes a highly requested feature, it might be worth adding an integrations tab in the settings menu.

**Comment by Retr0astic** [comment]
> Currently, theres not pywal integration. I don't see a pywal extension for chrome, so its unlikely that a pywal integration will be created as we prefer to keep feature parity.
> 
> If this becomes a highly requested feature, it might be worth adding an integrations tab in the settings menu.

Thank you very much for you reply, I see your point!
