### ISSUE TITLE
Wide or tall bookmark tiles appearing as regular "small box" tiles when using horisontal page alignment

### ISSUE THREAD

**Issue by Pixel-Clay** [zombieFox/nightTab#376]
**Describe the issue or bug**
When trying to set the bookmark tile size as tall/wide with horizontal page alignment, these tiles show as regular "small box" tiles

**To Reproduce**
1. Go to settings
2. Click on Layout
3. Scroll down to Alignment
4. Click on Align horizontal
5. Close the settings
6. Enable edit mode
7. Click on an Edit button of a bookmark tile
8. Click on Layout
9. Scroll down to Wide tile
10. Click on the Wide tile checkbox
11. See error

**Expected behavior**
Bookmark tiles which had been set up as wide or tall tiles should appear as wide or tall tiles when using horisontal page alignment

**Screenshots**
How it looks (youtube bookmark should be wide)
![New Tab - Google Chrome 14 06 2022 21_07_38](https://user-images.githubusercontent.com/80592654/173624860-2139f580-7b8a-4b14-bdda-6582cac60090.png)

How the youtube bookmark is set
![New Tab - Google Chrome 14 06 2022 21_08_08](https://user-images.githubusercontent.com/80592654/173625006-43550796-6120-443c-b1db-c8e13e439c0d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 102.0.5005.63 (x64)
 - nightTab version 7.3.0

**Comment by zombieFox** [comment]
Hi, yes @metruzanca is correct -- [we have logic in place to make](https://github.com/zombieFox/nightTab/blob/a779ffd6d697f35ef43af52eb45a29a57d421992/src/component/layout/index.js#L31) sure there is enough room inside the bookmark container to accommodate "wide" and "tall" bookmark tiles. If the container is too narrow the bookmark tiles reduce down to the default size. This was needed to avoid strange edge cases with different sized bookmark tiles and small viewport or container sizes.

You should be able to see this in action by changing the "Layout area width":


https://user-images.githubusercontent.com/7115017/173730191-6e73b484-d15b-4c80-9b9b-223810c218e1.mp4

 
Sorry but this is working as intended.

**Comment by zombieFox** [comment]
@Pixel-Clay You could try reducing the "Global size" and then increasing the "Layout area width" to make more room for the bookmark tiles.

**Comment by Pixel-Clay** [comment]
oh ok thanks i'll try this

**Comment by Pixel-Clay** [comment]
Yeah, it works now! thanks!

**Comment by Pixel-Clay** [comment]
![image](https://user-images.githubusercontent.com/80592654/173797216-9f65d043-50c3-4b07-8894-db1ad5dc34fd.png)
