### ISSUE TITLE
Brave Search doesn't work (only keeps refreshing the page)

### ISSUE THREAD

**Issue by p0yskaa** [zombieFox/nightTab#377]
I tried adding Brave search as the default search engine but upon searching something I only get brought back to NightTab
![image](https://user-images.githubusercontent.com/68812119/174659125-f2a3c4fd-0ea7-4f69-a185-cf3a087ef858.png)

![test](https://user-images.githubusercontent.com/68812119/174660977-c8aad96b-5577-48ed-9c06-57dfbee33f5c.gif)

I tried several different search strings such as
```
https://search.brave.com/search?q
https://search.brave.com/search?q=
https://search.brave.com/search?q=%
https://search.brave.com/search?q=%s
```

Nothing changes

**Comment by zombieFox** [comment]
Hi, this is working as expected. To get `search.brave.com` to work you must also inout the "Name attribute" value as `q`. So these values:


"Name": Anything you like
"URL": `https://search.brave.com/search?q=`
"Name attribute": `q`

Using these settings I am able to perform a search on `search.brave.com`. Hope that helps.

https://user-images.githubusercontent.com/7115017/174668588-ecefacf7-3d53-45cb-987f-b700dcd724e9.mp4

**Comment by p0yskaa** [comment]
Yes, thank you. That appears to have solved it.
