### ISSUE TITLE
Publish Chrome Extension / Installation

### ISSUE THREAD

**Issue by Tritiumnzlol** [zombieFox/nightTab#38]
Hi, loving the extension.

Is it possible for you to pack and publish it to the chrome web store? loading the unpacked extension periodically displays:

>**Disable Developer Mode Extensions**
>Extensions running in developer mode can harm your computer. If you're not a developer, you should disable these extensions running in developer mode to stay safe.

With no options to repress the message.

An official packaged extension published to the webstore that I can install from would be the ideal fix :)

**Comment by zombieFox** [comment]
I think that makes sense. However I'd like to get the project into maintenance mode before publishing it  in different places to avoid having to maintain the code in multiple places.

Right now I'm developing new features every week which is very time consuming. Once v3 is stable and most of the big features are developed and out of the way I will look into publishing to the Chrome Web Store.

**Comment by zombieFox** [comment]
Extensions for Chrome and Firefox are now live:

### [Chrome Extension](https://chrome.google.com/webstore/detail/nighttab/hdpcadigjkbcpnlcpbcohpafiaefanki)
### [Firefox Add On](https://addons.mozilla.org/en-GB/firefox/addon/nighttab/)

**Comment by Kreuger** [comment]
Hey man. Im using Vivaldi (based on Chrome) on Linux and I can't figure out how to set nightTab as my start page, or open it at all really.

**Comment by QyuriLa** [comment]
@Kreuger Did you solve the problem? I had the same issue and googled how to fix it.
Go `Settings - Tab - New Tab Page`, check `Controlled by Extension` below `Start Page` option and it will work!
