### ISSUE TITLE
theme after the research?

### ISSUE THREAD

**Issue by Manix80** [zombieFox/nightTab#391]
Hello 
I'm trying to keep the theme (nord) after the search result, however my multiple tries send me back to the home page.

under Header/search even the example address does not work.

I would have liked for example to have this theme result (duckduckgo) after the search:
https://duckduckgo.com/?q=nightab+github&k1=-1&k7=232831&k8=d8dee9&k9=d8dee9&kaa=4c566a&kae=d&kak=-1&kao=-1&kap=-1&kaq=-1&kau=-1&kax=-1&kj=232831&kx=4c566a&k21=242831&t=h_&ia=web

would someone have an idea ? thank you

**Comment by Manix80** [comment]
hello,
to make it simple, I try not to have the theme of the search engine result by default. (duckduckgo)

for example on duckduckgo we can change the theme of the search engine here: https://duckduckgo.com/settings#appearance

i guess the changes should be done in header/search/custom...

this is maybe impossible from your extension ?

5.19.13-zen1-1-zen (archlinux) 
Firefox 105.0.3 (64 bits)
http://0x0.st/oyhV.json

**Comment by zombieFox** [comment]
Are you asking if nightTab can change the theme of the search engine result page when you land on DuckDuckGo?

If so I don't think it is possible. At the very least this would require the nightTab extension to request a lot of new permissions from the use and make changes to webpages when they load. This is very much out of scope of this project.

**Comment by Manix80** [comment]
`Are you asking if nightTab can change the theme of the search engine result page when you land on DuckDuckGo?`

this is exactly what I am looking for!

`If so I don't think it is possible. At the very least this would require the nightTab extension to request a lot of new permissions from the user and make changes to webpages when they load. This is very much out of scope of this project.`

but if this is not possible, then I stay with your extension and "normal" duckduckgo
Thank you for your quick reply.
