### ISSUE TITLE
nightTab doesn't open as default page when I Open my brave browser

### ISSUE THREAD

**Issue by JymxB28** [zombieFox/nightTab#393]
**Describe the issue or bug**
So I have a 'Continue where I left off' configuration in my Barve, and I always keep a new window open and exit my browser. Earlier, when I used to open Brave, I was getting my nightTab page, but now for some reason, it opens up as brave's default homepage, and I have to click the home button to get my nightTab bookmarks. Afterward opening a new tab or getting to the homepage works as normal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave Browser v1.44.112 ( Chromium 106.0.5249.119.)
 - nightTab version 7.3.0

**Comment by zombieFox** [comment]
Hi, sorry but this project only supports Chrome and Firefox. I do not test on Brave browser. Please see the wiki on [browser support](https://github.com/zombieFox/nightTab/wiki/Browser-support) for more details.

I know some people have had success running nightTab on Brave - my guess would be that the browser has changed how extensions can override the home page.
