### ISSUE TITLE
NightTab backup file compatability between Chromium & Mozilla

### ISSUE THREAD

**Issue by TheAssurer2009** [zombieFox/nightTab#394]
I exported settings from Chrome & they properly import into Edge.  However, they do not import **_AT ALL_** into Firefox.  I then manually recreated the settings in Firefox and exported them to a Firefox specific file.  Comparing the 2 JSON files, the only difference I can find is each "bookmark" defined under Chrome has a setting that says "Vertical," which under the Firefox version says "Horizontal."

1. Why is there a difference?
2. Since the Chromium & Firefox versions "recognize" & reject the difference, can a "compatability switch" be added?

I have attached the 2 JSON files.
[NightTab_Backups.zip](https://github.com/zombieFox/nightTab/files/9861507/NightTab_Backups.zip)

**Comment by metruzanca** [comment]
Went ahead and tested both of your configs in firefox, both work just fine.,

Can you try again to import the chromium one into firefox but this time check the browser console(F12) for error messages? (I'd recommend for both our sakes that you clear the console before atempting to import)

Next would be nice to have some system information e.g. OS and browser version.

**Comment by TheAssurer2009** [comment]
THIS TIME it worked🤔.  The only thing different from the "last time" I
tried; was before, I immediately tried importing the Chrome backup after
installing the Firefox addon; on top of whatever example setup came with
it... I never got the dialog, the first time.

**Comment by zombieFox** [comment]
I've also test the files and both are working as expected.

> THIS TIME it worked🤔. 

Glad it's working now.
