### ISSUE TITLE
ability to add a bookmark to open a local file

### ISSUE THREAD

**Issue by skri11-2k** [zombieFox/nightTab#395]
I'd like the ability to add a local file as a bookmark that I open often.
Currently, it only allows https:// links, adding the option for file:// for opening files would be highly appreciated.
e.g. opening a pdf file that I read daily as a bookmark

**Comment by zombieFox** [comment]
Hi, I'm afraid this is not possible as `file://` is a protected URL. Check out the wiki on [Protected URLs](https://github.com/zombieFox/nightTab/wiki/Protected-URLs) for more information.
