### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by Nandicre2** [zombieFox/nightTab#4]
I tried to package it for myself and it just worked out of the box. If you want to do it :

- [Zip your repo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_). Exclude the screenshot folder, it's useless and huge (from 10MB to 1.1MB)

- Publish and sign it via [AMO](https://addons.mozilla.org/en-US/developers/addon/submit/distribution)

- You're done ! :smiley: 

I did one for myself, you can find it [here](https://github.com/Nandicre2/nightTab/releases/tag/v2-firefox). It's the xpi file.

Thanks for this amazing startpage !

**Comment by zombieFox** [comment]
I just tried this with nightTab v2 and it works as expected! Thanks for the info 👍
