### ISSUE TITLE
Search suggestions idea

### ISSUE THREAD

**Issue by Ultimatechno** [zombieFox/nightTab#403]
It would be nice to have an option for search suggestions as you type in the search bar like in google. ![(Reference picture)](https://user-images.githubusercontent.com/81396442/216797171-26c03093-69d5-4541-95cb-c7b59636347a.png)
An idea on how to do this could be by using google's autocomplete link and add %s at the end like this:
https://www.google.com/complete/search?client=chrome&q=%s
(it takes the search between "q=" and "%s"and save the suggestions in a txt file) 
then extracting the text from the txt and taking the suggestions and putting them in a vertical layout below the search bar (like on Google) every time a letter is added in the search bar.
Sorry if this is not clear, but I don't know JavaScript so can't give an example, but I believe it shouldn't be TOO hard to code, idk.
Thanks.

**Comment by zombieFox** [comment]
Answered in [Search autocomplete #288
](https://github.com/zombieFox/nightTab/issues/288)

In addition, sharing data with google search would be outside the scope of the [project principals](https://github.com/zombieFox/nightTab/wiki/Respecting-your-privacy).
