### ISSUE TITLE
Disable Remove bookmark setting

### ISSUE THREAD

**Issue by Munkenmo** [zombieFox/nightTab#41]
When editing a bookmark I accidentally removed one & now have to modify 30 bookmarks to achieve the layout I had.

Would it be possible to add a "disable remove button" setting to protect people like me from myself?

**Comment by zombieFox** [comment]
A valid point. However I don't feel like hiding controls would be the best way to tackle this kind of pain point. A confirmation when clicking the remove button is a more common UX pattern. I'll add this to the Projects Board.

**Comment by zombieFox** [comment]
Just merged a feature update to provide a solution for this issue.
