### ISSUE TITLE
Home Page not working will not stick keeps going to blank

### ISSUE THREAD

**Issue by thorrrr** [zombieFox/nightTab#420]
HI Guys
I have followed the FAQ Support but having been trying for 2hours getting it to stick to url as home page it keeps reverting to blank?

Firefox does not allow addons to replace the "homepage". However there is a workaround:

    Open a new Firefox window
    Open Firefox Preferences and open a new tab (nightTab)
    In Firefox preferences under Home, change Homepage and new windows to Custom URLs...
    Then click Use Current Page.

nightTab will now appear as the homepage.

THis does not work for me ?

**Comment by thorrrr** [comment]
Fixed it

**Comment by daFoggo** [comment]
Bro how did you fix that ?
