### ISSUE TITLE
Unsplash URL requests no longer function, must use API

### ISSUE THREAD

**Issue by gbcox** [zombieFox/nightTab#422]
Hello:

https://source.unsplash.com requests no longer function effective June 27, 2023.  I sent an email to unsplash support and received this reply:

Thank you for reaching out to us about [source.unsplash.com](http://source.unsplash.com/)! We do want to let you know that [source.unsplash.com](http://source.unsplash.com/) was created before the Unsplash API. Unfortunately, Unsplash no longer provides any support for [source.unsplash.com](http://source.unsplash.com/). We only left up this option for legacy developers who had been using [source.unsplash.com](http://source.unsplash.com/) before the Unsplash API was created. If you plan to use Unsplash images, it can only be through the Unsplash API since that is all we support at this time.
 
You can find more information about the Unsplash API here:

    [Unsplash API](https://unsplash.com/developers): here's where you can sign up and check out the API
    [API Guidelines](https://help.unsplash.com/en/collections/1451694-api-guidelines)
    [API Documentation](https://unsplash.com/documentation)

**Comment by zombieFox** [comment]
Yes the Unsplash API is the only supported way to use images from Unsplash. This project does not use any third part API to pull images. Instead it only use image (or video) URLs. This keeps the complexity and cost down. I don't have any plants to build in support for third part image connections.

**Comment by gbcox** [comment]
> Yes the Unsplash API is the only supported way to use images from Unsplash. This project does not use any third part API to pull images. Instead it only uses image (or video) URLs. This keeps the complexity and cost down. I don't have any plans to build in support for third part image connections.
> 
> I can see the URL function still works. I am able to use a Unsplash image URL without issue.

Yes, it is working again.  Not sure exactly what they are doing.  In any event, I have a workaround and just host images myself and access via URL.  That way I don't have to rely on Unsplash.  Thanks for making Nighttab!
