### ISSUE TITLE
Black night

### ISSUE THREAD

**Issue by Kamal2829** [zombieFox/nightTab#462]
# Have you checked the [nightTab Wiki for support?](https://github.com/zombieFox/nightTab/wiki)

**Please check before posting a question or issue.**

Some frequently asked questions include:
- [Browser support](https://github.com/zombieFox/nightTab/wiki/Browser-support)
- [Protected URLs](https://github.com/zombieFox/nightTab/wiki/Protected-URLs)
- [Resetting when opening the browser](https://github.com/zombieFox/nightTab/wiki/Resetting-when-opening-the-browser)
- [Setting nightTab as your Firefox homepage](https://github.com/zombieFox/nightTab/wiki/Setting-nightTab-as-your-Firefox-homepage)

---

# Still need to report an issue or ask a question:

**Describe the issue or bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - nightTab version [e.g. 6.0.0]

**Additional context**

**Comment by 26lake** [comment]
This should be closed. This is not a bug. If you're uploading a theme upload it to [r/nightTab](https://www.reddit.com/r/nighttab)
