### ISSUE TITLE
Data Restore not working

### ISSUE THREAD

**Issue by 10la5-Veygarn** [zombieFox/nightTab#472]
# Have you checked the [nightTab Wiki for support?](https://github.com/zombieFox/nightTab/wiki)

**Please check before posting a question or issue.**

Some frequently asked questions include:
- [Browser support](https://github.com/zombieFox/nightTab/wiki/Browser-support)
- [Protected URLs](https://github.com/zombieFox/nightTab/wiki/Protected-URLs)
- [Resetting when opening the browser](https://github.com/zombieFox/nightTab/wiki/Resetting-when-opening-the-browser)
- [Setting nightTab as your Firefox homepage](https://github.com/zombieFox/nightTab/wiki/Setting-nightTab-as-your-Firefox-homepage)

---

# Still need to report an issue or ask a question:

**Describe the issue or bug**
Whenever I use the data restore option, it does nothing. I first tried it on the normal, default page, nothing happened. Then, I uninstalled and re-installed it, but nothing happened. Then, I cleared all the bookmarks, but nothing is happening. It shows that the file upload is successful, and the file recognized, but nothing else.

**Expected behavior**
I expected that it would show the dialog box to select what I wanted to change.

**Screenshots**
[nightTab backup - 2024.11.21 - 10 57 20.json](https://github.com/user-attachments/files/17873792/nightTab.backup.-.2024.11.21.-.10.57.20.json)

**Desktop:**
 - OS: Windows
 - Browser: Zen, a fork of Firefox.
 - Version 1.0.1-a.19 (Firefox version 132.0.1)
 - nightTab version 7.3.0

**Additional Context**
As of 20 November, 2024, nightTab was functioning as normal. I imported a file (which worked) and also exported one, to be safe. Now, it is the same file, albeit renamed, which is not working

**Comment by phere-x** [comment]
Same thing happened with me. First I posted about Firefox not working over 1.5 Years ago. Now I see it doesn't work on a Chromium based browser like MS Edge too.

**Comment by 10la5-Veygarn** [comment]
It finally worked! Turns out it was a problem with the file, not the extension. I tried the original file from Reddit, and it functioned as normal. Also, I was using Zen Browser, which is based on Firefox, not a Chromium based browser.
