### ISSUE TITLE
request: 'folder/stacks' feature

### ISSUE THREAD

**Issue by ronmurphy** [zombieFox/nightTab#49]
So, a request idea, is it possible to implement a Windows 10 Start Menu like feature, as where you can take tiles, drag and drop them on another tile, and a 'folder/stack/group' is made that has just the dropped links in there? say that middle-clicking would open the folder, say, have the main bookmarks area slide off to the side, and the bookmarks show up in the area, and have a 'return' button to go back to the main page/area...   this would make organizing the links easier, and also help keep the main page cleaner.  

a secondary, and less important idea for the folder/stack/group, is that if you middle-click on the folder, have the page open all of the links in the folder in new tabs.  i realise that this may be harder to implement, maybe having the page parse the folder's links file for that stack and then do a  for x = 0 to link.max; opentab link.x; next x .... just an idea.

**Comment by zombieFox** [comment]
Thanks for the details, I'll try to break this down into manageable blocks of features.

**Comment by zombieFox** [comment]
See update comment on issue #62
