### ISSUE TITLE
URL unreadable when darker accent color is selected. 

### ISSUE THREAD

**Issue by jlant33** [zombieFox/nightTab#51]
URL text on hover stays black, so when a darker accent color is selected, it is hard to read.

**Comment by jlant33** [comment]
I should clarify, I have both light accent colors and dark accent colors. So when I select the dark text on "URL on hover" option, it is hard to read them on the dark colors, and when I select light text on "URL on hover", it's hard to read them on the light accent colors.

**Comment by zombieFox** [comment]
Good catch, I've been investigating this. I think this [invert library](https://github.com/onury/invert-color) would address this issue well.

**Comment by zombieFox** [comment]
Feature is now live in release version 3.20.1 🚀
