### ISSUE TITLE
Default customization

### ISSUE THREAD

**Issue by BradPerbs** [zombieFox/nightTab#53]
Hello, I was wondering where is possible to change the default settings like background-colors, colors and default bookmarks.

Cheers.

**Comment by zombieFox** [comment]
Hi, a lot of the core styles can be changed in the [variables.css](https://github.com/zombieFox/nightTab/blob/master/src/css/variables.css) and [base.css](https://github.com/zombieFox/nightTab/blob/master/src/css/base.css) files. The default bookmarks can be edited in [bookmarks.js](https://github.com/zombieFox/nightTab/blob/master/src/js/bookmarks.js)

But what are you trying to achieve? The bookmarks can be edited right on the page when the extension is installed.

**Comment by zombieFox** [comment]
Closing issue as there isn't anything to resolve. Hope that helped.
