### ISSUE TITLE
request: startup tab

### ISSUE THREAD

**Issue by ronmurphy** [zombieFox/nightTab#55]
can there be an option to make nightTab the default startup tab?  first tab that opens when you start firefox/chrome?

**Comment by zombieFox** [comment]
Current Firefox shows the "homepage" on start if no tabs or previous sessions is restored. And as far as I know there is no way to override the "homepage".

It does look like Chrome lets you set the homepage button to show the "new tab" page, which would allow an extension like nightTab to show on start up:
<img width="693" alt="Screen Shot 2019-06-30 at 20 18 21" src="https://user-images.githubusercontent.com/7115017/60401110-a9df3500-9b74-11e9-994d-6ed438290daf.png">

**Comment by Q-out** [comment]
I know the FF extension is out now, but in case you don't want to use an extension for some reason, here's what I use to make NightTab my new tab page: https://www.reddit.com/r/FirefoxCSS/comments/bcsmsy/startpage_as_new_tab_page/ektagz7/  while you can set home page natively in FF options.

**Comment by Q-out** [comment]
@ronmurphy What you have to do is install nightTab, close all tabs except the new tab with nightTab in it, then open Firefox options in second tab, go to Homepage options, click "Use current tabs".

**Comment by zombieFox** [comment]
The steps @Q-out describes works from my tests. Thanks for the input.
Closing the ticket.

**Comment by ronmurphy** [comment]
works great, thanks!
