### ISSUE TITLE
[proposal] Migrate to Gulp and minimize the files.

### ISSUE THREAD

**Issue by sytone** [zombieFox/nightTab#58]
Not really a issue but a proposal.

I noticed there were a lot of files, any issues implementing gulp and a dist folder so the project can be minimized for release?

**Comment by zombieFox** [comment]
The project started life as a very simple HTML file with some CSS so there was never a need for any build tools. But you are right, it's pretty complex now and needs some work to organise. 

I'm pretty familiar with Grunt -- but not Gulp. Gulp looks better so will look into the documentation. 

Will do 👍

**Comment by sytone** [comment]
Good example to work with at this repo: https://github.com/pschfr/start

**Comment by zombieFox** [comment]
Done!
