### ISSUE TITLE
Save preferences?

### ISSUE THREAD

**Issue by claudioruiz** [zombieFox/nightTab#6]
Maybe it's a silly question, but is there a way to save the customized bookmarks? Using v1, without a reason I lost my configuration.

**Comment by zombieFox** [comment]
Hi, sorry to hear you lost your customised bookmarks. I have a few questions to help me understand the problem:

- What browser are you using?
- Do you access nightTab via the url (eg https://zombiefox.github.io/nightTab/) or did you download a copy and run it locally? 
- Did you recently try running nightTab v2?

**Comment by claudioruiz** [comment]
* Firefox
* I cloned the repo
* I'm trying it now after I lost it all :(

**Comment by zombieFox** [comment]
That is very strange. I've been testing with Firefox and haven't replicated what you describe. Did you by chance clear your browser cache at all? The data to customise the app is all stored in local storage. If not you might be able to recover your bookmarks by using the console. 

Try running `state.get();` in the console.

**Comment by Exxmixx** [comment]
I'm having the same issue actually. Using Firefox, Cloned the repo. When I load the page, I do a test by removing some bookmarks, add some bookmarks, changing accent color, and a few settings. If I refresh it'll stay for a few, but if I close my broswer completely and open it again, it revert to normal.

**Comment by zombieFox** [comment]
Thanks @Exxmixx for the additional info. 

I've been running more experiments with Firefox (Firefox Quantum 64.0 Mac) and I've not been able to recreate what you describe. When I open new tabs, close Firefox and reopen etc my settings persist every time.

I would really appreciate knowing what version of Firefox and OS you are running. Along with the steps you follow in your tests.

**Comment by Exxmixx** [comment]
I'm on Firefox 64.0(Quantum as well) testing on Windows 10, Kubuntu 18.04, and even tested it on my personal web server that's running Ubuntu Server 16.04.

It does seem to be ok with Chrome though. If I open it in chrome and close it out, it works fine. BUT if I make changes in chrome, close it and open it in firefox, it doesn't show the saved changes. I did notice that no matter what changes I make, the files, bookmarks.js for example, doesn't change. It still has all the bookmarks from when I first cloned it.

**Comment by Nandicre2** [comment]
The changes are in the local storage, so if you configured your firefox to clean cookies, etc... or you use some kind of container, it maybe cleaned the local storage. I tried it in a new profile and it worked perfectly. Can you list us your addons ?

**Comment by zombieFox** [comment]
That is correct @Nandicre2. nightTab uses [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to save all preferences bookmarks. Which means the following:

- If you save something in nightTab on Chrome those changes are only available to Chrome and no other browsers.
- If you save something in nightTab on a particular computer those changes are only available to that  particular computer and no other computer. (The same is true for containers, dockers and any other kind of virtual machine magic.)
- If your browser clears cache or temporary internet files or local storage when closing down all preferences  saved to nightTab will be lost. 

nightTab is a small personal project. I have no access to databases or infrastructure to support saving user preferences to a server etc. I may look into adding import and export controls to move preferences and bookmarks between devices. I've done this before with other projects.

**Comment by Munkenmo** [comment]
Not sure if I should add this here or make it a separate issue:

When upgrading versions (eg. from 2.3 to 2.5) is there a way we can save our bookmarks / migrate them across versions?

**Comment by zombieFox** [comment]
@Munkenmo The bookmarks are all saved locally in local storage. Whenever there is an update to nightTab it will access local storage and migrate all bookmarks saved there. Can you describe the steps you are going through when you update and details on your browsers and the computer environment please?

**Comment by Munkenmo** [comment]
@zombieFox :

Windows 10
Firefox 64.0.2
I downloaded the 2.5.0 in .zip form, extracted the zip to a new folder (called : nightTab-2.5.0), opened the index.html file inside that folder (which has all the default settings) and then set that to be my new home page & new tab page.

**Comment by zombieFox** [comment]
@Munkenmo I understand now. 
Firefox treats every site you visit with a different address as distinct and keeps a unique instance of local storage for it.

So if you open nightTab from `c:/path/to/file/nightTab-2.3.0/index.html` it is treaded differently to `c:/path/to/file/nightTab-2.5.0/index.html` because the url is different (...2.3.0... vs ...2.5.0...).

To update from one version of nightTab to another I recommend you unzip to the same location as the last version.

Eg:
Download and unzip `nightTab-2.3.0.zip` to `c:/path/to/file/whatever-folder/index.html`.
Later on download and unzip a new version `nightTab-2.5.0.zip` to the same location of `c:/path/to/file/whatever-folder/index.html`. This should tell Firefox to use the same local storage. 

Your bookmarks are all still located at the last url. So in theory if you unzip the contents of `nightTab-2.5.0.zip` to the same location you should be able to see them in Firefox. 

I hope that helps.
