### ISSUE TITLE
White flash

### ISSUE THREAD

**Issue by Schanzation** [zombieFox/nightTab#60]
Every time I open a new tab with this extension is installed I get a brief white flash. Is there a way to fix that? I don't get that quick white flash when I don't use the extension.

**Comment by zombieFox** [comment]
I'm been aware of this for some time. Will look into this. The flash might be resolved by reducing the initial load time -- which ties into code minification and concatenation. So connected to [issues/58](https://github.com/zombieFox/nightTab/issues/58)

**Comment by Schanzation** [comment]
Ok thank you. I'm using shadow fox maybe that's why I don't get the flashes without extensions.

https://overdodactyl.github.io/ShadowFox/
