### ISSUE TITLE
Make items groupable

### ISSUE THREAD

**Issue by Gerondolom** [zombieFox/nightTab#62]
Please add the ability of grouping several tiles to provide a better optical structuring of the page. For example I would like to group all bookmarks for dictionaries, blogs/forums, social networks etc. in seperate areas each, which are separated by greater gaps or line breaks.

To illustrate this I photoshoped an example based on my own startpage with sperate areas for forums, dictionaries, encyclopedias and video pages.
![suggestion](https://user-images.githubusercontent.com/50837763/60641976-7b8c7e80-9e2e-11e9-823d-23dd5601f5b2.png)

The groups could arrange themselves in rows or columns and float freely over the page (like the tiles do at the moment) as long as the gap is sustained. The items should be draggable between groups. Additionaly there could be the ability to add headlines to the groups or different group accents or background shades.

**Comment by zombieFox** [comment]
Thanks for the feedback and all the details. I'll see what I can do. This may be close to (issues/49)[https://github.com/zombieFox/nightTab/issues/49].

**Comment by zombieFox** [comment]
#49 #74 

Thought I would give an update. Still a WIP. I have a branch with a new feature called Groups. Also have a basic version of sorting via drag and drop between groups.

Issues and breaking changes to resolve:
- Sorting via the menu (name, icon and letter) needs to be redesign to support groups
- Dealing with empty groups when all bookmarks are dragged out

Demo:

![Kapture 2019-10-04 at 11 23 08](https://user-images.githubusercontent.com/7115017/66201373-1e0d0580-e69b-11e9-9e7c-78ab85042a02.gif)

![Kapture 2019-10-04 at 11 35 19](https://user-images.githubusercontent.com/7115017/66201374-1ea59c00-e69b-11e9-8e59-213c968e2b79.gif)

**Comment by Vinetos** [comment]
I'm thinking of a folder system. 
As Discord do, you create an item and when you click on it, it makes visible the category. 

For example, you can use these categories you made and just make it visible when you click on the specific item.

**Comment by Gerondolom** [comment]
> Like Discord, you create an item and when you click it, it deploys the category.
> 
> For example, you can use categories that you have created and make them visible when you click on a specific item.

I think it should be accomplished with the least possible amount of clicking. I always liked calling up my start page and seeing all items on first sight to choose the desired page with a minimal loss of time.

That was the actual reason for my request. I want the start page to be more distinct by grouping similar items, so I could find and access shortcuts even faster and optimize my workflow.
The current Windows 10 Start Menu, where you can create individual groups to organize the tiles, seems like a good example for this.

**Comment by zombieFox** [comment]
> I think it should be accomplished with the least possible amount of clicking.

I agree with this. The intention of this feature is to solve the problem of organisations on screen. The WIP solution will simpler to implement than folders. As folders will require greater thinking around the UX of hiding and revealing bookmarks.

This is not to say folders are not going to happen. It just won't happen yet.

This current feature is proving difficult and timing consuming but needs to be developed first.

**Comment by zombieFox** [comment]
Feature is live in v4.0.0
