### ISSUE TITLE
Page header background color for use with VivaldiFox

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#63]
Kind of a niche use case here I guess.
Since the earliest versions of NightTab I've been able to use VivaldiFox ([Github](https://github.com/nt1m/vivaldi-fox)) ([AMO](https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/)) to color the browser's toolbars the same color as NightTab's header shade.
![Screenshot](https://user-images.githubusercontent.com/52709014/60899623-68433e00-a288-11e9-8e5c-132d185f0fbd.png)
With the latest version though, assuming because of the header logic or layout control changes, VivaldiFox fails to load the right color, selecting some grey shades apparently picked while NightTab is still loading.

If I may suggest a workaround, VF still seems to load the accent color as the toolbar color when there is a border on top of the shade. So maybe a toggle for the border color to switch between accent color and the shade's natural color (before taking into account the opacity settings)?
This should make sense with the new layout options so you can have, for example, a transparent shade below the bookmarks with the dark grey borders on top and/or bottom.

**Comment by zombieFox** [comment]
I'm new to VivaldiFox so I will investigate. I'll see if I can learn how VivaldiFox detects the colour to use. A quick bit of digging suggests it may use the `<meta name="theme-color" content="#000000">` meta tag. 

Will investigate more.

**Comment by Q-out** [comment]
Thank you. 
I can't tell what the default setting "Use colors defined by the web page when available" exactly uses but when that setting is unticked (or when the colors aren't defined, I assume):
![Screenshot (73)](https://user-images.githubusercontent.com/52709014/60968093-df84da80-a339-11e9-8ce6-e02990a42e93.png)
It looks like VF picks the color from the center pixel:
![Screenshot (72)](https://user-images.githubusercontent.com/52709014/60969173-7783c380-a33c-11e9-8325-e41952e17103.png)
That's how my VF is set up, and it used to work well before v3.30.6 (now it picks up the white from the white flash that happens before page loading is complete). With that, depending on the method VF uses to detect that page-load is complete, this issue might be related to page load / white flash issues.

**Comment by Q-out** [comment]
Seems to be working almost consistently now when header shade is shown on top and is opaque. When it isn't, the behavior isn't consistent, It will load the dark theme color on first load, 
![First Load](https://user-images.githubusercontent.com/52709014/61628379-bf410e00-ac9f-11e9-9025-f25c9d8e0f7b.png)
then pick up the wallpaper color on refresh,
![On Refresh](https://user-images.githubusercontent.com/52709014/61628427-de3fa000-ac9f-11e9-8111-b9eb2aa4c847.png)
sometimes improperly. Rarely even when header shade is opaque and on top:
![Like that](https://user-images.githubusercontent.com/52709014/61628471-0b8c4e00-aca0-11e9-821f-07dbf33e36e1.png)

But, matching the header shade was all I needed, so I'm closing the ticket. Thanks for working on this.

**Comment by zombieFox** [comment]
Understood. I'll continue to look into this behaviour nonetheless.
