### ISSUE TITLE
Icons have stopped working (Firefox V68.0)

### ISSUE THREAD

**Issue by Munkenmo** [zombieFox/nightTab#64]
Firefox Version : 68.0
nightTab Version : 3.30.6

[Icons have stopped working](https://i.imgur.com/674x9JD.png) after the most recent Firefox update. 

Icons were working on previous Firefox versions & still work if I roll back to an older version of Firefox.

**Comment by zombieFox** [comment]
Thanks for the feedback and alerting me to this issue. I've ran some tests using the following conditions: 
- MacOS 10.14.5
- Firefox 68.0
And I can not replicate this issue. Icons and fonts are loading correctly.

It looks like you may be using Windows 10(?), unfortunatly I don't have access to a Windows computer so can't investigate.

Can you please open the [developer tools](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console). From there make sure you are looking at the Console tab. Can you see any errors or warnings?
Thanks for helping.

**Comment by Q-out** [comment]
There's 14 warnings, 1 for each file in the fonts directory. They all go like this.
>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Firefox%20Homepage/src/fonts/fjalla-one/fjalla-one-regular.ttf. (Reason: CORS request not http).

Icons load fine when I load NightTab from the extension (I used a separate profile in FF to check).

**Comment by zombieFox** [comment]
Just so I am clear, these errors only appear/icons and fonts don't load when using nightTab locally from a file and not as an installed add on?

**Comment by Q-out** [comment]
Yes, that's correct. Maybe @Munkenmo can confirm if they're also loading from a file.
For the record, I'm on 

- Windows 10 1809
- Firefox Version 68.0
- nightTab Version 3.30.6

The warnings link to this page https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

**Comment by Munkenmo** [comment]
Can confirm I also have a manual installation, not the add-on.

**Comment by zombieFox** [comment]
Understood. So this is a security feature used by Firefox (and maybe other browsers) which prevents loading of certain files when run locally. As nightTab grows in complexity some features might only be available when installed as an addon/extension. 

My advice would be to install nightTab through the web-stores:
[Chrome Extension](https://chrome.google.com/webstore/detail/nighttab/hdpcadigjkbcpnlcpbcohpafiaefanki)
[Firefox Add On](https://addons.mozilla.org/en-GB/firefox/addon/nighttab/)

You should be able to export your data using the built in JSON export controls in the menu. And then reload then when the addon/extension is installed.

**Comment by Munkenmo** [comment]
I don't mind swapping over to the add on, I'd only stuck with manual install out of habit.

It appears that the background picture now has to be loaded from a url?  I've tried loading my old background : 

file:///C:/Users/Documents/NightTab/background/Background.png 

and it seems nothing happens at all, not even an error in the dev console.  Is local hosting the background image still possible?

**Comment by zombieFox** [comment]
Yes that is correct. Local images became difficult or impossible due to Extension/Add On security restrictions. So I removed the feature. 

As it happens I've been working on an [alternative solution (still a WIP)](https://github.com/zombieFox/nightTab/tree/localImage). Loading local files and setting it as a background as Base64 encodings. It's still in the works but will be done in a few days. 

I'll aim to release an update in a week or so. Hopefully after the white [flash issue](https://github.com/zombieFox/nightTab/issues/65) is resolved too.

**Comment by Munkenmo** [comment]
Awesome, I'll keep an eye out for the next release.

Thanks for all your work on this, the progress has been amazing.

**Comment by zombieFox** [comment]
- Icon issue was related to loading nightTab locally and can't be resolved as this is a browser security restriction.
- Selecting a local file as a background is now live in v3.61.0 on Chrome and Firefox extension.

Closing this issue ticket.
