### ISSUE TITLE
Page Title resets to "New Tab" on a refresh.

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#70]
Windows 10, Firefox 68.0.1
NightTab 3.61.0 Extension

Page title gets reset to "New Tab" on refresh. In Settings>Layout it correctly reflects what I've set it to before. If I type something in there, the page title updates properly, but gets reset again on refresh / opening new tab.

**Comment by zombieFox** [comment]
Good catch! Thanks -- this is a bug I must have created in the recent major refactor. [I've fixed it now](https://github.com/zombieFox/nightTab/commit/edb07efe5453c7f9b44cebb2a8e0c21b1f098103). I'll aim to push out an update soon to release this and a few other bug fixes.
