### ISSUE TITLE
Feature Request: Category support

### ISSUE THREAD

**Issue by rcreasey** [zombieFox/nightTab#74]
somewhat related to #49, it would be great to have the ability to group a collection of bookmarks into separate sections/categories.

I was just thinking having each section having their own subheader/icon/grouping to have a more visually partitioned UI.

**Comment by zombieFox** [comment]
Thanks for the feedback. Yes I can see this being very useful. Also yes, Similar to #62 and #49.

I've been working plans to deliver this feature but it is a large task so will take some time. Some of the smaller issues and bugs are taking a priority right now. Please refer to the [Project board](https://github.com/zombieFox/nightTab/projects/1) to check the status of the issues.

**Comment by Vinetos** [comment]
Hello :) 
I'll  try to have a look

**Comment by zombieFox** [comment]
See update comment on issue #62

**Comment by zombieFox** [comment]
Feature is live in v4.0.0
