### ISSUE TITLE
Data Setting missing in Firefox

### ISSUE THREAD

**Issue by dogskool** [zombieFox/nightTab#77]
Firefox crashed and upon restarting the computer nightTab was reinstalled. I went to import my backup and the 'Data' tab in the Settings menu is missing.

Any way to get that back?

**Comment by zombieFox** [comment]
I discovered this today too. Seems Firefox have rolled the addon back to v3.14.0. I'm working to roll it forward again. Please be patient, I'm waiting on a mod to review the latest build.

**Comment by zombieFox** [comment]
Update, still waiting on a mod to review the latest build on the Firefox web store.

**Comment by zombieFox** [comment]
v3.69.0 has now been reviewed by a Firefox mod and is live on the web store. All features are present. Please check you `about:addons`  (add settings) page and check for updates.
