### ISSUE TITLE
Export Data button not working

### ISSUE THREAD

**Issue by dogskool** [zombieFox/nightTab#78]
Using Firefox 68.0.1 and nightTab 3.72.0:

I am trying to backup my data and the button does not work at all.

**Comment by zombieFox** [comment]
Very strange. No changes have been made to [data.js](https://github.com/zombieFox/nightTab/tree/master/src/js) in 14 days. Seems the temporary [link](https://github.com/zombieFox/nightTab/blob/master/src/js/data.js#L44) used to export the data does not register in Firefox unless it is appended to the body. I've made a change which I'm testing now. Should be live in a few hours as a bug fix.

**Comment by zombieFox** [comment]
Bug fix is live on nightTab 3.73.0. Should be live on Firefox now. 👍
