### ISSUE TITLE
Home page doesn't load NightTab

### ISSUE THREAD

**Issue by adriencarbonaro** [zombieFox/nightTab#79]
When I open Firefox, the Home Page is not NightTab. It is the default newtab. The same when I open `about:newtab` : 

![16-08-2019_1208_1525x774](https://user-images.githubusercontent.com/32357019/63160949-44a9ab00-c01f-11e9-8653-cf3493a373a7.png)

But when I press `ctrl` + `T`, the (beautiful) NightTab page opens : 

![16-08-2019_1208_1596x871](https://user-images.githubusercontent.com/32357019/63160999-5f7c1f80-c01f-11e9-94d5-ca860020158c.png)

I've seen that in the preferences, the New Tab section is controlled by NightTab but not the Home Page.

Do you know how to fix this ? I would love to have your page as home page.

**Comment by zombieFox** [comment]
Hi. Can you confirm you had tried to follow the steps described by @Q-out in [issue 55](https://github.com/zombieFox/nightTab/issues/55#issuecomment-510100072) please?

**Comment by adriencarbonaro** [comment]
No I didn't try it. I will and let you know

**Comment by zombieFox** [comment]
Awesome!
