### ISSUE TITLE
Search with other engine

### ISSUE THREAD

**Issue by adriencarbonaro** [zombieFox/nightTab#80]
The search section is always performed by Google.

Would it be possible to search with something else, like DuckDuckGo ?

**Comment by zombieFox** [comment]
Hi, can you confirm you have chosen a new search engine under the `settings > header > search > search engine` options?

Can you also provide which version of nightTab, browser and OS you are using please?

**Comment by adriencarbonaro** [comment]
I didn't see this option. It might be time that I get new glasses!
I'll try and let you know.

**Comment by adriencarbonaro** [comment]
Thanks, works like a charm !

**Comment by zombieFox** [comment]
Glad to hear!
