### ISSUE TITLE
[Visual Bug] 1 pixel wide vertical offset on a hovered tile shadow.

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#84]
Occurs with "List" style with "Grow on tile hover" enabled. It's not noticeable when either "Tile line" or "URL on hover" is enabled.
![Screenshot (83)](https://user-images.githubusercontent.com/52709014/63648943-dd91a200-c754-11e9-8843-5f64d11a1bb2.png)
Also occurs with "Block" style with "Grow on tile hover" _and_ "Tile line" enabled and "URL on hover" disabled.
![Screenshot (84)](https://user-images.githubusercontent.com/52709014/63649076-c358c380-c756-11e9-8e52-f635c1a833de.png)

This is super important, really.

**Comment by zombieFox** [comment]
Critical bug alert 🚨🚨🚨

I suspect this is due to how different browsers render css [transform scale](https://github.com/zombieFox/nightTab/blob/f3695f3bd2f3f3831ed5a3ecf13e4bbf15fa5b92/src/css/link.css#L74) for the hover state.

I was aware of this on some old version of Firefox but it went away on Mac OS Firefox a few versions ago. 

I'll see if I can't replicate this. But I don't know if there is much that can be done. It comes down to how some browsers handle transform scale.

**Comment by zombieFox** [comment]
Correction: _I think_ comes down to how some browsers handle transform scale **and box shadows**.

**Comment by Q-out** [comment]
So it's (likely) only happening with Win10 FF? Win10 and FF seems to be the worst combination when it comes to using NightTab haha. Please close the issue if you find that there's nothing you could do about it. At the very least the new border option tends to mask the bug a bit.

**Comment by zombieFox** [comment]
Yea, I have tried a few times to recreate this and been unsuccessful. Not having Win10 is hindering me. Setting this to "Help Wanted", hopefully someone with the right combo of hardware can help solve it. (It's worth keeping open.)

**Comment by Q-out** [comment]
I see. I'm still finding it strange that it'd happen _only_ on Windows Firefox. Or is it maybe only on my end for some reason?. Maybe someone with Win10/FF can confirm this happens to them too?

**Comment by zombieFox** [comment]
Any update on this issue? Is the rendering bug still appearing? I'm still not seeing it and still not sure what can be done about it.

**Comment by Q-out** [comment]
I tried the offending combination of settings again and no, it is not appearing any more. Did a little test with some more fiddling with different settings but didn't manage to recreate the issue, though I suppose it's possible some very specific combination will make it turn up again.

Glad to see this ultra critical bug get quashed.

**Comment by zombieFox** [comment]
> Glad to see this ultra critical bug get quashed.

I suspect improvements in browser rendering and nightTab CSS over the months has played a hand in quashing it.
