### ISSUE TITLE
clear out data?

### ISSUE THREAD

**Issue by scottjl** [zombieFox/nightTab#88]
how can i clear out nighttab's data from chrome (and firefox would be handy to know too)? something is wrong with my config, i have a complete blank page now. i tried removing the extension and re-adding it, but still have a blank page. i'm suspecting my data is corrupt. can't find any cookies for it.

thanks!

**Comment by zombieFox** [comment]
Removing nightTab and adding it again should clear all data as nothing is saved when an extension/add on is removed.

Still, using the `Menu > Data > Clear data` button will do this. nightTab stores all data in the browser [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). The Clear data button wipes it all out.

If you can't see nightTab and it's menu you can open up the local storage for your browser and remove everything manually by following these steps:

[Chrome local storage](https://developers.google.com/web/tools/chrome-devtools/storage/localstorage) 
 or [Firefox local storage (scroll down to "Find out which sites use Web Storage")](https://www.ghacks.net/2015/02/05/how-to-clear-web-storage-in-your-browser-of-choice/)

Once there find anything to do with "nightTab" (there should only be one entry) and delete it.

Another way is to run `localStorage.clear();` in the console when the tab is open to wipe everything out.

Are you seeing any errors in your browser console when you open a new tab?
