### ISSUE TITLE
backfround color

### ISSUE THREAD

**Issue by pjhalsli** [zombieFox/nightTab#91]
I messed up this post - new post below

edited:   tried to delete it but found no option for it

**Comment by pjhalsli** [comment]
I'm wondering if it's possible to change the background color and not just the accent color?
I know I can have a bg picture but I use only terminals so it would be nice to have nighttab to use my terminal colors - so my terminal bg color would also be my nighttab bg color. I hope I you understand whtat I mean.

I've used tons of startpages over the years but none have even come close to this- so thank you for all the time and efffort you've put into this. Much appreciated.  NightTab FTW

**Comment by Q-out** [comment]
Are you using the latest version of the extension? The option for custom background color exists, look in
Settings > Background > Color > Custom background color

**Comment by pjhalsli** [comment]
I'm not using an extension. I git cloned it locally. But I guess thst's the same?

**Comment by Q-out** [comment]
Should be the same. Make sure you've pulled the latest changes. Background color options were added around [two months ago](https://github.com/zombieFox/nightTab/commit/cc40feee5e7d7d7220ba2cc172f5b991959f7b76) for version [3.69.0](https://github.com/zombieFox/nightTab/releases/tag/v3.69.0).

**Comment by pjhalsli** [comment]
ok. I tried it as an extension too now - on firefox and it works great that way too.
I'll close this now. Thx for your answers

**Comment by zombieFox** [comment]
Thanks @Q-out for addressing this. 👍
