### ISSUE TITLE
Visual bug with a certain Bookmark border width

### ISSUE THREAD

**Issue by Q-out** [zombieFox/nightTab#92]
Easiest to just show you: https://i.imgur.com/udzwyxr.mp4
Win10 FF v69.0.1

**Comment by zombieFox** [comment]
Whoa! What is going on there??
I'm trying to recreate this, how did you get that to happen?

**Comment by Q-out** [comment]
Try 
 - Bookmarks > Border > level 3 (where the initial level is 0)
 - Theme > Style > Radius > level 1 (likewise)

No other setting seems to be effecting this bug, It's only this combination (as far as I have seen).

**Comment by Q-out** [comment]
I don't see this anymore in v4. Love the finer controls on the sliders btw.

**Comment by zombieFox** [comment]
Glad it was resolved with the recent updates. Never did find the cause of this issues. Oh well.
