### ISSUE TITLE
hosting site

### ISSUE THREAD

**Issue by rpoovey** [zombieFox/nightTab#94]
Is anything extra required to host this site on an nginx server? 

I've run the npm install run inside the src folder along side installing gulp... I dont get a new build/run folder though. (I didn't on my Mac either). And I'm making a /location in nginx that has an alias to the folder on my server. But I just get a blank blue page that looks like its trying to run.

**Comment by zombieFox** [comment]
I'm not familiar with nginx servers but...
> run inside the src folder
You should run npm install in the root of the project, not the `/src/` directory. Then run `npm run build` from the root too.

**Comment by hartk1213** [comment]
did you ever get yours hosted on your nginx server?

**Comment by zombieFox** [comment]
Closing issue as no follow up was provided.
