### ISSUE TITLE
Export Data Not Working on Chrome

### ISSUE THREAD

**Issue by sheldonhull** [zombieFox/nightTab#97]
Chrome Version: `Version 77.0.3865.120 (Official Build) (64-bit)`
nightTab Version: `Version 3.80.0`

Export Data button is not working

**Comment by zombieFox** [comment]
That is odd. It's working for me on that version. Can you add more details of your set up please? Or the steps you take in detail?

Are there any errors appearing in the console when you try to export?

**Comment by zombieFox** [comment]
Closing issue as no follow up was provided and am not able to recreate the issue.
