### ISSUE TITLE
Dragging Bookmarks

### ISSUE THREAD

**Issue by BRod79** [zombieFox/nightTab#99]
Wish it worked the same way to the left as it does to the right.

When moving a block to the right, it highlights the first position <-- great!    but when dragging to the left, you have to drag 2 positions to get it one block away, if it makes sense.

**Comment by zombieFox** [comment]
Thanks for the feedback. I think I know what you mean, however I am having success when dragging to sort left or right. Can you provide more details or a video of the the difference you are seeing?

The drag sorting is achieved by [html5sortable](https://github.com/lukasoppermann/html5sortable). As such I can't do much to improve it. html5sortable builds on native HTML drag and drop, so is a good candidate for this feature.

**Comment by zombieFox** [comment]
Closing this issue as html5sortable is used as a dependency and works well enough as an enhancement to the existing sorting control arrows.

I will version bump html5sortable if it updates.
